/**
 * THE 50 WARS — the fixed, chronological season slate.
 *
 * Each card is a military problem, not a re-enactment: your anachronistic army is
 * dropped into the war's defining challenge ("establish and supply a beachhead"),
 * never "defeat <population>". Jokes punch at your army's dysfunction, not at victims.
 *
 * Boundaries: conventional warfare only, nothing after 1991, no WMD, no active
 * conflicts, no cards whose defining mechanic is atrocity. See README.
 */
import type { CampaignKind } from './types'

export const SLATE: CampaignKind[] = [
  {
    id: 'greco-persian',
    name: 'The Greco-Persian Wars',
    subtitle: 'The Hot Gates',
    era: '480 BCE',
    objective: 'Hold an impossible chokepoint, then win the sea.',
    role: 'defender',
    tags: ['mountain', 'naval'],
    tests: ['defense', 'coalition', 'naval'],
    weights: { atk: 0.15, def: 0.25, grit: 0.3, int: 0.15, mob: 0.15 },
    baseD: 6.8,
    winTemplates: [
      'The pass held, the strait held, and {unit} spent the victory feast retelling it at increasing volume.',
      'A coalition of armies that hate each other agreed on exactly one thing, once, at the perfect moment: {unit} goes in front.',
    ],
    lossTemplates: [
      'The chokepoint was magnificent until someone found the goat path. There is always a goat path.',
      'Your coalition met the enemy with unity, courage, and eleven different signal systems. {unit} attacked a friendly flank by noon.',
    ],
  },
  {
    id: 'peloponnesian',
    name: 'The Peloponnesian War',
    subtitle: 'The Thirty-Year Argument',
    era: '431 BCE',
    objective: 'Win a generation-long duel between land power and sea power.',
    role: 'attacker',
    tags: ['naval', 'urban'],
    tests: ['naval', 'blockade', 'intel'],
    weights: { atk: 0.2, log: 0.25, grit: 0.25, int: 0.3 },
    baseD: 7.0,
    winTemplates: [
      'You refused every battle you could lose and accepted the one you couldn’t, thirty years in. {unit} called it patience; everyone else called it a siege of the calendar.',
      '{unit} understood the whole war was a shipping ledger and quietly audited the enemy into surrender.',
    ],
    lossTemplates: [
      'Your grand expedition sailed over the horizon with the fleet, the treasury, and the plan. None of the three returned.',
      'Thirty years of strategy, undone by plague, faction, and one assembly vote taken while angry.',
    ],
  },
  {
    id: 'alexander',
    name: 'Alexander’s Persian Campaign',
    subtitle: 'The Long March East',
    era: '334 BCE',
    objective: 'Sustain a conquering army three thousand miles from home.',
    role: 'attacker',
    tags: ['desert', 'open'],
    tests: ['logistics', 'expedition'],
    weights: { atk: 0.25, mob: 0.3, log: 0.25, grit: 0.2 },
    baseD: 6.4,
    winTemplates: [
      'Every river crossed, every satrapy folded, and {unit} kept asking if there was anything past the maps. There wasn’t. You checked.',
      '{unit} marched further than the couriers carrying news of the victories, which caused administrative chaos and three premature statues.',
    ],
    lossTemplates: [
      'The army was unbeatable; the distance was not. Somewhere past the second desert, the supply line filed for independence.',
      'Your veterans, three thousand miles from home, respectfully requested a war closer to the war they signed up for.',
    ],
  },
  {
    id: 'punic',
    name: 'The Second Punic War',
    subtitle: 'The Elephant in the Room',
    era: '218 BCE',
    objective: 'Win deep in enemy country with no reinforcements coming.',
    role: 'attacker',
    tags: ['mountain', 'open'],
    tests: ['logistics', 'intel'],
    weights: { atk: 0.25, mob: 0.2, int: 0.3, log: 0.25 },
    baseD: 7.6,
    boss: true,
    winTemplates: [
      'You crossed the impossible mountains, won the impossible battles, AND held the peace after — the one part history never managed. {unit} takes the laurel.',
      'The double envelopment worked so perfectly that war colleges will teach it for 2,000 years. {unit} was the hinge.',
    ],
    lossTemplates: [
      'You won every battle and lost the war, which is this card’s signature move. {unit} has questions for the home government, which never sent reinforcements.',
      'Fifteen years undefeated in enemy territory, undone by one bad afternoon on home soil.',
    ],
  },
  {
    id: 'han-xiongnu',
    name: 'The Han–Xiongnu Wars',
    subtitle: 'The Horizon Subscription',
    era: '129 BCE',
    objective: 'Project power into the open steppe and keep it supplied.',
    role: 'attacker',
    tags: ['steppe'],
    tests: ['logistics', 'terrain'],
    weights: { mob: 0.35, log: 0.3, atk: 0.2, grit: 0.15 },
    baseD: 6.5,
    winTemplates: [
      'Your columns found the enemy in an ocean of grass, which is like finding a rumor in a library with no walls. {unit} did the finding.',
      '{unit} out-rode the steppe itself, and the frontier moved a thousand li in your favor.',
    ],
    lossTemplates: [
      'The enemy was everywhere your army wasn’t, which, on the open steppe, is most places.',
      'Your supply train reached the rendezvous on schedule. The war had moved 400 miles. It usually has.',
    ],
  },
  {
    id: 'gallic',
    name: 'The Gallic Wars',
    subtitle: 'The Wall Around Everything',
    era: '58 BCE',
    objective: 'Defeat a dispersed enemy, then out-engineer the siege of your life.',
    role: 'attacker',
    tags: ['open', 'urban'],
    tests: ['siege', 'irregular'],
    weights: { atk: 0.25, def: 0.2, log: 0.25, tech: 0.15, grit: 0.15 },
    baseD: 6.3,
    winTemplates: [
      'Besieging a fortress while being besieged yourself is showing off, and {unit} did it with a straight face.',
      '{unit} built a wall around the problem, then a wall around the wall. The problem surrendered to the carpentry.',
    ],
    lossTemplates: [
      'Each tribe you defeated politely introduced you to two more. The map ran out of your army first.',
      'Your circumvallation was flawless except for the relief army arriving on the outside of it, which is the part circumvallation is for.',
    ],
  },
  {
    id: 'red-cliffs',
    name: 'Red Cliffs',
    subtitle: 'The River of Fire',
    era: '208 CE',
    objective: 'Stop an overwhelming force at the river with cunning and flame.',
    role: 'defender',
    tags: ['naval', 'night'],
    tests: ['naval', 'intel', 'defense'],
    weights: { atk: 0.2, int: 0.3, tech: 0.2, grit: 0.3 },
    baseD: 7.2,
    winTemplates: [
      'The enemy chained their ships together for stability, and {unit} sent them a fire with excellent balance.',
      'A borrowed wind, a false defection, and one match: {unit} turned the river into the largest lantern in history.',
    ],
    lossTemplates: [
      'The wind changed sides before your admirals did. The fireships returned to sender.',
      'Your ruse required the enemy to be arrogant on schedule, and they were regrettably humble that week.',
    ],
  },
  {
    id: 'yarmouk',
    name: 'Yarmouk',
    subtitle: 'The Desert Verdict',
    era: '636 CE',
    objective: 'Beat a larger, richer army with speed, morale, and desert mastery.',
    role: 'attacker',
    tags: ['desert', 'open'],
    tests: ['blitz', 'terrain'],
    weights: { mob: 0.3, grit: 0.3, atk: 0.25, int: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'Six days of feints, then the whole battle folded in an afternoon. {unit} used the desert as a door.',
      'The enemy anchored their line on a ravine, and {unit} filed the ravine under “ours.”',
    ],
    lossTemplates: [
      'Your army treated the desert as an obstacle. The enemy treated it as a colleague. The desert noticed.',
      'The decisive cavalry sweep swept decisively into a dust storm and out of the historical record.',
    ],
  },
  {
    id: 'heathen-army',
    name: 'The Great Heathen Army',
    subtitle: 'The Uninvited Fleet',
    era: '865 CE',
    objective: 'Raid, winter over, and conquer with an army that arrives by river.',
    role: 'attacker',
    tags: ['naval', 'winter'],
    tests: ['amphibious', 'irregular'],
    weights: { mob: 0.3, atk: 0.25, log: 0.2, grit: 0.25 },
    baseD: 6.6,
    winTemplates: [
      'Every river was a highway and every monastery a supply depot. {unit} never technically stopped moving for nine years.',
      '{unit} arrived by water, wintered uninvited, and by spring owned the guest room, the house, and three kingdoms.',
    ],
    lossTemplates: [
      'The locals finally learned the trick: burn the bridges, buy the winter, and wait for your fleet to miss the tide.',
      'An army that lives by the raid starves by the fortified burh. They built 33 of them.',
    ],
  },
  {
    id: 'norman-conquest',
    name: 'The Norman Conquest',
    subtitle: 'The Channel Crossing',
    era: '1066',
    objective: 'Land across a contested channel and win the one battle that decides everything.',
    role: 'attacker',
    tags: ['naval', 'open'],
    tests: ['amphibious', 'naval'],
    weights: { atk: 0.3, log: 0.25, mob: 0.2, grit: 0.25 },
    baseD: 6.4,
    winTemplates: [
      'You landed unopposed because the enemy was busy winning a different invasion 250 miles north. {unit} sent a thank-you note.',
      'One channel, one landing, one hill, one arrow’s worth of luck — and {unit} standing exactly where the kingdom changed hands.',
    ],
    lossTemplates: [
      'The invasion fleet was perfect; the weather window was three weeks of “no.” The enemy used the time to stop being tired.',
      'The feigned retreat was so convincing that it became a real one somewhere around the second hedge.',
    ],
  },
  {
    id: 'first-crusade',
    name: 'The First Crusade',
    subtitle: 'The Longest Walk',
    era: '1096',
    objective: 'March a fractious coalition 2,000 miles and take a fortified city at the end of it.',
    role: 'attacker',
    tags: ['desert', 'urban'],
    tests: ['logistics', 'supply', 'siege', 'coalition'],
    weights: { log: 0.35, grit: 0.3, atk: 0.2, int: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'Eight rival commanders, one starving march, and somehow the wall came down anyway. {unit} held it all together with rope and glares.',
      '{unit} solved the siege the honest way: build the towers, take the wall, argue about credit for a century.',
    ],
    lossTemplates: [
      'The army defeated every enemy except the itinerary. Two thousand miles ate it one ration at a time.',
      'Your coalition’s princes agreed on the destination and nothing else, including, eventually, the destination.',
    ],
  },
  {
    id: 'khwarazm',
    name: 'The Mongol Conquest of Khwarazm',
    subtitle: 'The Horizon Comes For You',
    era: '1219',
    objective: 'Coordinate converging armies across a continent-sized front.',
    role: 'attacker',
    tags: ['steppe', 'urban'],
    tests: ['blitz', 'intel', 'siege'],
    weights: { mob: 0.35, int: 0.25, atk: 0.25, log: 0.15 },
    baseD: 7.7,
    boss: true,
    winTemplates: [
      'Four armies, one timetable, zero radios — and every column arrived like it had read the others’ minds. {unit} was the tempo.',
      'The enemy defended every city. You attacked every city. Their plan required you to pick one. {unit} declined.',
    ],
    lossTemplates: [
      'Your converging columns converged on schedule, which was the enemy’s schedule, in the enemy’s valley.',
      'An empire-sized front needs empire-sized couriers, and yours delivered last month’s war.',
    ],
  },
  {
    id: 'hundred-years',
    name: 'The Hundred Years’ War',
    subtitle: 'The Century of Overtime',
    era: '1337',
    objective: 'Sustain a war effort across four generations without going bankrupt.',
    role: 'attacker',
    tags: ['open', 'urban'],
    tests: ['siege', 'logistics'],
    weights: { atk: 0.3, def: 0.2, log: 0.25, grit: 0.25 },
    baseD: 6.5,
    winTemplates: [
      'The sky went dark at the usual o’clock, and {unit} collected another impossible field victory. The accountants won the rest.',
      'You out-lasted three enemy kings, two plagues, and one financial collapse. {unit} aged extremely well.',
    ],
    lossTemplates: [
      'You won the famous battles and lost the boring decades, which is where this war keeps its actual scoring.',
      'A teenager with a banner turned the entire momentum of the century, and your side spent the rest of it explaining that.',
    ],
  },
  {
    id: 'constantinople',
    name: 'The Fall of Constantinople',
    subtitle: 'The Thousand-Year Wall',
    era: '1453',
    objective: 'Break the most famous fortifications on Earth.',
    role: 'attacker',
    tags: ['urban', 'naval'],
    tests: ['siege', 'naval'],
    weights: { atk: 0.35, tech: 0.3, log: 0.2, grit: 0.15 },
    baseD: 6.7,
    winTemplates: [
      'The walls had a thousand-year warranty, and {unit} voided it in seven weeks.',
      'When the boom blocked the harbor, {unit} moved the fleet overland on greased logs, which the defenders correctly rated as “unfair.”',
    ],
    lossTemplates: [
      'The great gun cracked on day nine, the walls did not, and the math of the siege quietly reversed.',
      'A thousand years of masonry asked your army one question — “how, exactly?” — and held the silence.',
    ],
  },
  {
    id: 'ethiopian-adal',
    name: 'The Ethiopian–Adal War',
    subtitle: 'The Highland Firewall',
    era: '1529',
    objective: 'Fight a firearms-age war across mountain country with imported everything.',
    role: 'defender',
    tags: ['mountain'],
    tests: ['terrain', 'coalition', 'defense'],
    weights: { grit: 0.3, atk: 0.25, tech: 0.25, mob: 0.2 },
    baseD: 6.3,
    winTemplates: [
      'Muskets from one continent, allies from another, terrain from the moon — {unit} made the mixture hold.',
      'The highlands are a fortress with weather for walls, and {unit} garrisoned every cloud.',
    ],
    lossTemplates: [
      'Your matchlocks arrived without powder, your allies without orders, and the pass without a second exit.',
      'Every ridge you held had a brother you didn’t. The war moved ridge by ridge, and so did your luck.',
    ],
  },
  {
    id: 'sengoku',
    name: 'The Sengoku Jidai',
    subtitle: 'The Job Interview With Swords',
    era: '1560',
    objective: 'Unify a country of rival warlords, castles, and brand-new firearms.',
    role: 'attacker',
    tags: ['urban', 'night'],
    tests: ['siege', 'intel'],
    weights: { atk: 0.25, tech: 0.25, int: 0.25, grit: 0.25 },
    baseD: 7.2,
    winTemplates: [
      'Volley fire behind field stockades ended the age of the charge in one afternoon, and {unit} pulled the trigger on schedule.',
      '{unit} took the castles the modern way: rotate the muskets, mind the weather, betray precisely once.',
    ],
    lossTemplates: [
      'You unified two-thirds of the map, which history records as “not unifying the map.”',
      'A night assault in a mountain pass ended your bid — the classic Sengoku exit interview.',
    ],
  },
  {
    id: 'imjin',
    name: 'The Imjin War',
    subtitle: 'The Turtle Toll',
    era: '1592',
    objective: 'Strangle an invasion by cutting its sea lanes.',
    role: 'defender',
    tags: ['naval'],
    tests: ['naval', 'blockade', 'defense'],
    weights: { atk: 0.3, def: 0.25, log: 0.25, int: 0.2 },
    baseD: 6.6,
    winTemplates: [
      'The invasion had a magnificent army and a supply line made of hope. {unit} sank the hope.',
      'Thirteen ships against the horizon, and the horizon lost. {unit} was flying the flagship’s colors.',
    ],
    lossTemplates: [
      'The straits stayed open a season too long, and the war walked up the peninsula on schedule.',
      'Court politics beached your best admiral at the exact moment the sea needed him. The sea holds grudges.',
    ],
  },
  {
    id: 'thirty-years',
    name: 'The Thirty Years’ War',
    subtitle: 'The Everyone War',
    era: '1618',
    objective: 'Keep an army alive through decades of marching, foraging, and shifting alliances.',
    role: 'attacker',
    tags: ['open'],
    tests: ['logistics', 'coalition', 'irregular', 'propaganda'],
    weights: { log: 0.3, grit: 0.25, atk: 0.25, def: 0.2 },
    baseD: 6.8,
    winTemplates: [
      'Your army was the only one in Europe that ended the war better fed than it started, which is the entire victory condition. {unit} ran the kitchens like a siege.',
      '{unit} mastered the era’s true weapons: the pike square, the pamphlet, and the punctual payroll.',
    ],
    lossTemplates: [
      'Your unbeatable army ate the province, then the next province, then the alliance.',
      'After a decade, nobody could remember the war aims, but everyone remembered what your cavalry did to the granaries.',
    ],
  },
  {
    id: 'maratha',
    name: 'The Mughal–Maratha Wars',
    subtitle: 'The Hill Fort Subscription',
    era: '1680',
    objective: 'Beat an empire with mobility, mountains, and a hundred small fortresses.',
    role: 'defender',
    tags: ['mountain', 'jungle'],
    tests: ['irregular', 'terrain', 'siege'],
    weights: { mob: 0.3, int: 0.25, grit: 0.25, log: 0.2 },
    baseD: 6.6,
    winTemplates: [
      'The empire took a fort a month; {unit} took two forts back every new moon. The subscription auto-renewed for 27 years.',
      'Light cavalry that lives off speed against an army that lives off baggage — {unit} kept choosing the mountain’s side of the argument.',
    ],
    lossTemplates: [
      'The great siege train ground through your hills one wall at a time, and this month it did not run out of months.',
      'Your raiders out-rode everything except the season the wells went dry.',
    ],
  },
  {
    id: 'vienna',
    name: 'The Siege of Vienna',
    subtitle: 'The Doorstep of Europe',
    era: '1683',
    objective: 'Hold a breached city until the relief army arrives — then time the charge.',
    role: 'defender',
    tags: ['urban', 'open'],
    tests: ['defense', 'siege', 'coalition'],
    weights: { def: 0.3, grit: 0.25, atk: 0.25, log: 0.2 },
    baseD: 7.1,
    winTemplates: [
      'The walls held by a rumor’s width, and then the hills produced the largest cavalry charge in history. {unit} rode the crest of it.',
      'Sixty days of mines and counter-mines, and on day sixty-one, {unit} arrived exactly as late as legends require.',
    ],
    lossTemplates: [
      'The relief army came over the hills at dawn — a dawn too late, one bastion short.',
      'The mine under the wall was heard, mapped, and dug out twice. The third one wasn’t.',
    ],
  },
  {
    id: 'great-northern',
    name: 'The Great Northern War',
    subtitle: 'General Winter’s Audition',
    era: '1700',
    objective: 'March an unbeaten army into the north and survive what the map does next.',
    role: 'attacker',
    tags: ['winter', 'open'],
    tests: ['logistics', 'supply', 'terrain'],
    weights: { log: 0.3, grit: 0.3, mob: 0.2, def: 0.2 },
    baseD: 6.8,
    winTemplates: [
      'You did what the textbook says is impossible: invaded the endless country, kept the army fed, and left before the punchline. {unit} watched the thermometer like a hawk.',
      'The scorched-earth retreat found nothing to scorch — {unit} carried the earth along.',
    ],
    lossTemplates: [
      'The coldest winter in a century met the longest supply line on the continent. They got along famously.',
      'Your undefeated field army marched into the deep country undefeated, and came out as a story.',
    ],
  },
  {
    id: 'seven-years',
    name: 'The Seven Years’ War',
    subtitle: 'World War Zero',
    era: '1756',
    objective: 'Fight a coalition on five fronts across three oceans without dropping one.',
    role: 'defender',
    tags: ['open', 'naval'],
    tests: ['coalition', 'naval', 'logistics', 'expedition'],
    weights: { atk: 0.2, def: 0.2, mob: 0.2, log: 0.2, int: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'Surrounded by three empires, you marched on interior lines like a commuter with one train pass. {unit} never missed a connection.',
      'The war was won on every continent at once, mostly by {unit} being on the correct one each season.',
    ],
    lossTemplates: [
      'Five fronts, four allies, three oceans, two treasuries — one of these numbers hit zero first.',
      'You held brilliantly everywhere except the theater where the peace treaty was being drafted.',
    ],
  },
  {
    id: 'am-rev',
    name: 'The American Revolution',
    subtitle: 'The Long Odds',
    era: '1775',
    objective: 'Outlast a superior military until the politics break your way.',
    role: 'defender',
    tags: ['open', 'winter'],
    tests: ['irregular', 'coalition', 'propaganda', 'defense'],
    weights: { grit: 0.35, int: 0.25, log: 0.2, mob: 0.2 },
    baseD: 6.4,
    winTemplates: [
      'You lost the cities, kept the army, and won the argument. {unit} understood which one was the war.',
      'An enemy fleet arrived at the decisive moment flying a friendly flag — {unit} had been writing those letters for years.',
    ],
    lossTemplates: [
      'The cause survived every defeat except the winter the army’s shoes didn’t.',
      'Your insurgency needed one great-power ally, and the great powers kept asking to see another win first.',
    ],
  },
  {
    id: 'napoleonic',
    name: 'The Napoleonic Wars',
    subtitle: 'The Everything Campaign',
    era: '1805',
    objective: 'Beat coalition after coalition without marching one country too far.',
    role: 'attacker',
    tags: ['open', 'winter'],
    tests: ['logistics', 'coalition', 'blitz'],
    weights: { atk: 0.25, mob: 0.25, log: 0.25, grit: 0.25 },
    baseD: 7.6,
    boss: true,
    winTemplates: [
      'Six coalitions formed against you; six coalitions attended the peace conference as spectators. {unit} was the difference and knows it.',
      'You did the thing he couldn’t: won everything AND stopped at the border with the weather on it. {unit} hid the maps of the east.',
    ],
    lossTemplates: [
      'The army group that entered the endless country was history’s finest. The one that left fit in a footnote.',
      'You beat every army in Europe until Europe stopped sending armies and started sending winters.',
    ],
  },
  {
    id: 'war-1812',
    name: 'The War of 1812',
    subtitle: 'The Lake Effect',
    era: '1812',
    objective: 'Win a frontier war decided by lakes, forts, and who burns whose capital.',
    role: 'attacker',
    tags: ['naval', 'winter'],
    tests: ['naval', 'absurd'],
    weights: { atk: 0.25, def: 0.25, log: 0.25, grit: 0.25 },
    baseD: 6.6,
    winTemplates: [
      'Whoever builds ships faster owns the lakes, and {unit} turned the shoreline into a shipyard with opinions.',
      'The war ended in a tie everyone claims to have won. Yours is the only claim with {unit}’s receipts attached.',
    ],
    lossTemplates: [
      'Your invasion of the northern frontier went precisely as far as the first fort and exactly no farther.',
      'The peace treaty was signed before your greatest victory, which is the most this-war thing that could have happened.',
    ],
  },
  {
    id: 'crimean',
    name: 'The Crimean War',
    subtitle: 'The Siege With Commentary',
    era: '1853',
    objective: 'Run a year-long modern siege at the end of a very bad road.',
    role: 'attacker',
    tags: ['urban', 'winter'],
    tests: ['siege', 'logistics', 'trench'],
    weights: { log: 0.3, tech: 0.25, def: 0.25, grit: 0.2 },
    baseD: 6.6,
    winTemplates: [
      'The trenches crept forward yard by yard for 340 days, and {unit} kept the yards coming and the scurvy going the other way.',
      'You built a railway to the siege, which is cheating, which is why {unit} did it.',
    ],
    lossTemplates: [
      'The valley had guns on three sides, someone blundered, and the light cavalry made history in the worst available way.',
      'Winter reached the trenches before the supply corps did, and the newspapers reached the capital before either.',
    ],
  },
  {
    id: 'acw',
    name: 'The American Civil War',
    subtitle: 'The Railway War',
    era: '1861',
    objective: 'Win a continental war with railways, rivers, and industry.',
    role: 'attacker',
    tags: ['open', 'urban'],
    tests: ['logistics', 'naval', 'siege'],
    weights: { log: 0.3, atk: 0.25, tech: 0.25, grit: 0.2 },
    baseD: 6.7,
    winTemplates: [
      'The rivers became highways, the railways became arteries, and {unit} understood the war was won at the junctions.',
      'The anaconda squeezed for four years, and {unit} was the coil that never loosened.',
    ],
    lossTemplates: [
      'You won the battles with flags in them and lost the ones made of timetables.',
      'The siege of the river citadel broke your calendar: the enemy could reinforce by rail in days; your columns had mud.',
    ],
  },
  {
    id: 'boshin',
    name: 'The Boshin War',
    subtitle: 'The War Between Centuries',
    era: '1868',
    objective: 'Win a civil war where one side has rifles and the other has tradition.',
    role: 'attacker',
    tags: ['urban', 'open'],
    tests: ['intel', 'absurd'],
    weights: { tech: 0.35, grit: 0.3, atk: 0.2, int: 0.15 },
    baseD: 7.4,
    winTemplates: [
      'A war where centuries fight each other head-on — your entire roster nodded in recognition. {unit} felt extremely seen.',
      'Modern rifles, ancient banners, and {unit} translating between them: the future won, but it saluted the past on the way past.',
    ],
    lossTemplates: [
      'Your army brought the wrong century to the decisive battle, which in this war is the entire scoreboard.',
      'The last cavalry charge against the repeating rifles was magnificent, brave, and over in four minutes.',
    ],
  },
  {
    id: 'franco-prussian',
    name: 'The Franco-Prussian War',
    subtitle: 'The Timetable Blitz',
    era: '1870',
    objective: 'Mobilize faster than the enemy can think.',
    role: 'attacker',
    tags: ['open'],
    tests: ['logistics', 'blitz'],
    weights: { mob: 0.3, log: 0.3, tech: 0.2, atk: 0.2 },
    baseD: 6.5,
    winTemplates: [
      'The war was won by the railway clerks three weeks before the first shot, and {unit} was reading their schedules.',
      'Two enemy field armies, two encirclements, six weeks. {unit} kept the tempo like a metronome with a grudge.',
    ],
    lossTemplates: [
      'Your mobilization order reached the depots as the enemy’s corps reached the border. The war aged a decade in its first fortnight.',
      'Your army entrenched at the fortress city to regroup, which is how it became a fortress full of prisoners.',
    ],
  },
  {
    id: 'anglo-zulu',
    name: 'The Anglo-Zulu War',
    subtitle: 'The Horns of the Buffalo',
    era: '1879',
    objective: 'Defend your homeland against a modern invader using speed, terrain, and discipline.',
    role: 'defender',
    tags: ['open'],
    tests: ['irregular', 'terrain', 'blitz', 'defense'],
    weights: { mob: 0.35, grit: 0.3, int: 0.2, atk: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'The horns closed at a sprint before the invader’s square could form, and {unit} was the tip of the left horn.',
      'An army with rifles walked into a country that runs fifty miles before breakfast. {unit} set the pace.',
    ],
    lossTemplates: [
      'The first great victory taught the invader everything, and the second battle was fought against your own lesson.',
      'Courage closed to spear-length on schedule; the volley fire had other appointments for it.',
    ],
  },
  {
    id: 'pacific-1879',
    name: 'The War of the Pacific',
    subtitle: 'The Driest War',
    era: '1879',
    objective: 'Fight over the world’s driest desert, where the sea is the only road.',
    role: 'attacker',
    tags: ['desert', 'naval'],
    tests: ['naval', 'blockade', 'supply', 'logistics'],
    weights: { log: 0.35, atk: 0.25, mob: 0.2, grit: 0.2 },
    baseD: 6.6,
    winTemplates: [
      'Whoever owns the water owns the desert, and {unit} owned both oceans of it — the salt one and the drinking kind.',
      'Every offensive was an amphibious landing in disguise, and {unit} stopped bothering with the disguise.',
    ],
    lossTemplates: [
      'Your army crossed the driest place on Earth and arrived as a very committed line of thirst.',
      'The enemy monitor controlled the coast for one season too many, and the desert did the rest pro bono.',
    ],
  },
  {
    id: 'russo-japanese',
    name: 'The Russo-Japanese War',
    subtitle: 'The Modern Siege Preview',
    era: '1904',
    objective: 'Win the fortress, survive the trenches, and settle it at sea.',
    role: 'attacker',
    tags: ['urban', 'naval'],
    tests: ['siege', 'naval', 'trench', 'logistics'],
    weights: { atk: 0.25, tech: 0.25, log: 0.25, grit: 0.25 },
    baseD: 6.8,
    winTemplates: [
      'The fortress fell, the fleet that sailed around the world arrived to find no reason to have, and {unit} wrote the century’s syllabus.',
      '203 Meter Hill cost everything and bought the harbor below it. {unit} carried the observation post that ended a navy.',
    ],
    lossTemplates: [
      'The fortress guns and the barbed wire previewed the next fifty years, and your assault columns attended the preview at full price.',
      'Your relief fleet completed history’s longest voyage in time for history’s shortest battle.',
    ],
  },
  {
    id: 'ww1-west',
    name: 'The Western Front',
    subtitle: 'The Mud Ledger',
    era: '1914',
    objective: 'Break a continuous fortified front that has no flanks.',
    role: 'attacker',
    tags: ['open'],
    tests: ['trench', 'siege', 'logistics'],
    weights: { def: 0.3, grit: 0.3, log: 0.2, tech: 0.2 },
    baseD: 7.0,
    winTemplates: [
      'Bite, hold, repeat: {unit} perfected the only arithmetic the trenches respect, and the front finally moved like a glacier deciding to run.',
      'Creeping barrage, stormtroop infiltration, tanks in the mist — your army skipped to the 1918 chapter in 1915, with {unit} on point.',
    ],
    lossTemplates: [
      'The plan took the first trench line by lunch. The war lives in the second line, and it kept living there.',
      'Your breakthrough advanced four miles into a salient shaped exactly like a mistake.',
    ],
  },
  {
    id: 'gallipoli',
    name: 'Gallipoli',
    subtitle: 'The Beach With Opinions',
    era: '1915',
    objective: 'Force a defended strait with an amphibious landing under the cliffs.',
    role: 'attacker',
    tags: ['naval', 'mountain'],
    tests: ['amphibious', 'naval', 'coalition'],
    weights: { atk: 0.25, log: 0.3, grit: 0.25, int: 0.2 },
    baseD: 7.1,
    winTemplates: [
      'The beach was a shooting gallery and the cliffs were the gallery’s management — {unit} bought the building in one night assault.',
      'You did what the whole 1915 plan couldn’t: got off the beach on day one. {unit} refused to dig in and dug forward instead.',
    ],
    lossTemplates: [
      'The landing seized precisely the amount of beach a beach towel requires, and held it with valor for eight months.',
      'The navy declined the strait, the army declined the ridge, and the whole peninsula declined the plan.',
    ],
  },
  {
    id: 'russian-civil',
    name: 'The Russian Civil War',
    subtitle: 'The Armored Train Timetable',
    era: '1917',
    objective: 'Control a collapsing country the size of a continent via its railways.',
    role: 'attacker',
    tags: ['winter', 'steppe'],
    tests: ['logistics', 'irregular', 'absurd'],
    weights: { mob: 0.3, log: 0.3, grit: 0.2, int: 0.2 },
    baseD: 6.5,
    winTemplates: [
      'Whoever holds the junctions holds the continent. {unit} ran the armored trains on time, which no one else managed in any direction.',
      'Eleven time zones, forty factions, one working timetable — {unit}’s. The rest is mopping up.',
    ],
    lossTemplates: [
      'Your front existed wherever your trains were, and the partisans discovered rails have bolts.',
      'You advanced a thousand miles along the railway into a country that kept being a thousand miles deeper.',
    ],
  },
  {
    id: 'chaco',
    name: 'The Chaco War',
    subtitle: 'The Thirst War',
    era: '1932',
    objective: 'Win a war where water is the ammunition that matters.',
    role: 'attacker',
    tags: ['desert', 'jungle'],
    tests: ['logistics', 'supply', 'terrain', 'absurd'],
    weights: { log: 0.4, grit: 0.3, mob: 0.2, int: 0.1 },
    baseD: 6.7,
    winTemplates: [
      'Two armies fought over a wilderness rumored to contain oil. It contained thorns. {unit} won the only resource that was real: the wells.',
      'Every advance was measured in canteens, and {unit} ran the water convoys like a heist crew.',
    ],
    lossTemplates: [
      'Your offensive died of thirst within sight of the enemy’s water point, which had been the entire war all along.',
      'The trucks sank, the wells were dry, and the thorn forest kept both armies as pets.',
    ],
  },
  {
    id: 'spanish-civil',
    name: 'The Spanish Civil War',
    subtitle: 'The Dress Rehearsal',
    era: '1936',
    objective: 'Hold a besieged capital while the next war’s weapons are tested on you.',
    role: 'defender',
    tags: ['urban'],
    tests: ['defense', 'siege', 'coalition', 'propaganda'],
    weights: { grit: 0.3, def: 0.3, int: 0.2, tech: 0.2 },
    baseD: 6.5,
    winTemplates: [
      'The city held through the winter with sandbags, slogans, and {unit} plugging every breach before the newsreels finished narrating it.',
      'Half the world sent weapons, the other half sent volunteers, and {unit} welded the chaos into a garrison.',
    ],
    lossTemplates: [
      'The capital held the line but not the map, and wars are unfortunately printed on maps.',
      'Your foreign allies shipped rifles from four countries with ammunition from a fifth.',
    ],
  },
  {
    id: 'winter-war',
    name: 'The Winter War',
    subtitle: 'General Winter’s Home Game',
    era: '1939',
    objective: 'Defend a small country against a giant one at forty below.',
    role: 'defender',
    tags: ['winter', 'night'],
    tests: ['defense', 'irregular', 'terrain'],
    weights: { grit: 0.3, def: 0.25, mob: 0.25, int: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'Ski troops in white ghosted between frozen lakes cutting columns into pockets, and {unit} moved like the forest had opinions.',
      'The invader owned the roads; {unit} owned everything that wasn’t one, which in that country is the country.',
    ],
    lossTemplates: [
      'Heroism kept the line for a hundred days; arithmetic arrived on day one hundred and one.',
      'The cold fought for both sides, and the enemy could afford the tuition.',
    ],
  },
  {
    id: 'fall-of-france',
    name: 'The Fall of France',
    subtitle: 'The Six-Week Argument',
    era: '1940',
    objective: 'Win the campaign in the enemy’s decision cycle, not on their line.',
    role: 'attacker',
    tags: ['open', 'air'],
    tests: ['blitz', 'airsup', 'intel'],
    weights: { mob: 0.35, tech: 0.25, int: 0.2, atk: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'The armored spearhead went through the forest everyone had marked “impassable,” and {unit} reached the coast before the enemy reached a decision.',
      'The war was won at the map table: every enemy order answered a move {unit} had made two days prior.',
    ],
    lossTemplates: [
      'Your spearheads outran fuel, air cover, and instructions, in that order, and stopped precisely where a counterattack was waiting.',
      'You attacked the strongest sector at the speed of 1918, and the defense answered at the speed of 1940.',
    ],
  },
  {
    id: 'atlantic',
    name: 'The Battle of the Atlantic',
    subtitle: 'The Convoy Ledger',
    era: '1940',
    objective: 'Keep the sea lanes alive against the wolfpacks — every month, forever.',
    role: 'defender',
    tags: ['naval', 'night'],
    tests: ['naval', 'blockade', 'intel', 'logistics', 'air'],
    weights: { int: 0.3, tech: 0.25, log: 0.25, def: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'The war was a spreadsheet with weather: tonnage built minus tonnage sunk. {unit} flipped the sign and never let it flip back.',
      'Decrypted headings, escort carriers, centimetric radar — {unit} turned the dark ocean into a well-lit office.',
    ],
    lossTemplates: [
      'The gap in the middle of the ocean stayed dark one year too long, and the ledgers drowned quietly.',
      'The convoys zigged where the codebooks said, and someone else was reading the codebooks.',
    ],
  },
  {
    id: 'north-africa',
    name: 'The North African Campaign',
    subtitle: 'The Fuel Gauge War',
    era: '1941',
    objective: 'Attack across a desert where every mile forward weakens you.',
    role: 'attacker',
    tags: ['desert', 'air'],
    tests: ['logistics', 'supply', 'terrain', 'air'],
    weights: { log: 0.35, mob: 0.25, atk: 0.2, tech: 0.2 },
    baseD: 6.8,
    winTemplates: [
      'The desert is a quartermaster’s duel with tanks for punctuation, and {unit} punctuated at El-everywhere.',
      'You advanced exactly as far as your fuel, which, thanks to {unit}, was for once exactly as far as the enemy.',
    ],
    lossTemplates: [
      'Your brilliant armored sweep ended at a fuel gauge, 40 miles short of everything.',
      'Every mile forward made you weaker and the enemy stronger, and your plan contained 400 miles of forward.',
    ],
  },
  {
    id: 'eastern-front',
    name: 'The Eastern Front',
    subtitle: 'The Deep Winter',
    era: '1941',
    objective: 'Survive the largest land war ever fought — scale, weather, and attrition.',
    role: 'defender',
    tags: ['winter', 'open'],
    tests: ['logistics', 'terrain', 'defense'],
    weights: { log: 0.3, grit: 0.3, atk: 0.2, def: 0.2 },
    baseD: 7.5,
    boss: true,
    winTemplates: [
      'You traded space for time, moved the factories over the mountains, and came back with winter as a co-belligerent. {unit} held the door at the river city.',
      'The front was a thousand miles of arithmetic, and {unit} was the number that wouldn’t reduce.',
    ],
    lossTemplates: [
      'The salient became a pocket, the pocket became a museum exhibit, and the airlift that was promised weighed one-tenth of the promise.',
      'Your army group won every summer and lost every winter, and the war was scored in winters.',
    ],
  },
  {
    id: 'carrier-war',
    name: 'The Pacific Carrier War',
    subtitle: 'The Empty Horizon',
    era: '1942',
    objective: 'Win fleet battles where the fleets never see each other.',
    role: 'attacker',
    tags: ['naval', 'air'],
    tests: ['naval', 'airsup', 'intel'],
    weights: { int: 0.3, tech: 0.3, atk: 0.25, log: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'The codebreakers called the ambush, the dive bombers found four flattops in five minutes, and {unit} owned the five minutes.',
      'Two fleets fought to the horizon’s edge without sighting a mast — {unit} saw everything anyway.',
    ],
    lossTemplates: [
      'Your scout planes radioed “nothing to report” from directly above the enemy task force.',
      'The strike launched at extreme range, found clouds, and returned to a carrier that was busy being on fire.',
    ],
  },
  {
    id: 'island-campaigns',
    name: 'The Island Campaigns',
    subtitle: 'The Ten Thousand Beaches',
    era: '1943',
    objective: 'Take fortified islands one landing at a time, supplied across an ocean.',
    role: 'attacker',
    tags: ['naval', 'jungle'],
    tests: ['amphibious', 'naval', 'logistics', 'air'],
    weights: { atk: 0.25, grit: 0.3, log: 0.3, tech: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'You learned the amphibious trade island by island until the ocean itself was a supply route, with {unit} first ashore each time.',
      'Leapfrog the strongpoints, starve the garrisons, keep the beachhead fed — {unit} made an ocean campaign into a conveyor belt.',
    ],
    lossTemplates: [
      'The reef ate the landing craft at low tide, and the second wave arrived as spectators.',
      'You took the beach in three days and the island in three months, and there were forty more islands.',
    ],
  },
  {
    id: 'normandy',
    name: 'Normandy',
    subtitle: 'The Stormed Shore',
    era: '1944',
    objective: 'Land a coalition on a fortified coast and win the buildup race.',
    role: 'attacker',
    tags: ['naval', 'air'],
    tests: ['amphibious', 'coalition', 'air', 'logistics'],
    weights: { log: 0.3, atk: 0.25, tech: 0.25, int: 0.2 },
    baseD: 7.1,
    winTemplates: [
      'Five beaches, three airborne divisions, two artificial harbors, one inflatable decoy army — and {unit} making the whole orchestra play in key.',
      'The defenders knew you were coming; {unit} made sure they knew it 150 miles from where you came.',
    ],
    lossTemplates: [
      'The weather window closed on the fleet mid-channel, and the second-largest amphibious force in history returned to port in the rain.',
      'The beachhead held; the buildup race didn’t. Their panzers took the interior lines and your harbors took a storm.',
    ],
  },
  {
    id: 'indochina',
    name: 'The First Indochina War',
    subtitle: 'The Valley Trap',
    era: '1946',
    objective: 'Never garrison a valley the enemy can put artillery around.',
    role: 'defender',
    tags: ['jungle', 'mountain'],
    tests: ['irregular', 'terrain', 'logistics', 'air'],
    weights: { log: 0.3, int: 0.25, grit: 0.25, atk: 0.2 },
    baseD: 6.8,
    winTemplates: [
      'The enemy invited you to a set-piece battle in a mountain bowl, and {unit} RSVP’d “no” — the rarest victory in this war.',
      'Your airlift kept every outpost fed while {unit} refused every valley with a scenic overlook.',
    ],
    lossTemplates: [
      'The fortified camp was impregnable from every direction except up, and the enemy carried artillery up.',
      'The airstrip closed on day three of a fifty-six day siege. The rest was arithmetic with monsoons.',
    ],
  },
  {
    id: 'korea',
    name: 'The Korean War',
    subtitle: 'The Yo-Yo Peninsula',
    era: '1950',
    objective: 'Survive four reversals of fortune in mountains, in winter, with allies.',
    role: 'defender',
    tags: ['mountain', 'winter'],
    tests: ['terrain', 'coalition', 'airsup', 'defense'],
    weights: { grit: 0.3, mob: 0.25, log: 0.25, def: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'From the perimeter to the landing to the reservoir and back, {unit} treated whiplash as a maneuver element.',
      'The amphibious left hook at the port city flipped the entire peninsula in a week, with {unit} over the seawall first.',
    ],
    lossTemplates: [
      'The advance reached the frozen river as an army and left the reservoir as a legend with frostbite.',
      'Your coalition fought bravely in four languages, and the ridge changed hands eleven times before the map stopped caring.',
    ],
  },
  {
    id: 'vietnam',
    name: 'The Vietnam War',
    subtitle: 'The Map That Lies',
    era: '1965',
    objective: 'Outlast an enemy who wins every battle — make time your weapon.',
    role: 'defender',
    tags: ['jungle', 'night'],
    tests: ['irregular', 'intel', 'propaganda'],
    weights: { grit: 0.35, int: 0.3, log: 0.2, mob: 0.15 },
    baseD: 7.0,
    winTemplates: [
      'The enemy owned the daylight, the maps, and the metrics. {unit} owned the calendar, which is the one that decides.',
      'Every enemy report said “winning”; every enemy calendar said “still there.” {unit} was the still.',
    ],
    lossTemplates: [
      'Your patience war met an enemy with more patience, which was not in the briefing.',
      'The trail was cut in four places, and the whole strategy was the trail.',
    ],
  },
  {
    id: 'falklands',
    name: 'The Falklands War',
    subtitle: 'The 8,000-Mile Commute',
    era: '1982',
    objective: 'Project an expeditionary force to the far end of the Earth and land it in winter seas.',
    role: 'attacker',
    tags: ['naval', 'winter'],
    tests: ['naval', 'air', 'expedition', 'supply', 'amphibious'],
    weights: { log: 0.35, atk: 0.2, tech: 0.25, grit: 0.2 },
    baseD: 6.9,
    winTemplates: [
      'A task force assembled in a week sailed 8,000 miles and yomped the last fifty in sleet — {unit} arrived with dry powder and opinions.',
      'The exclusion zone held, the landing held, the ridgelines fell one bayonet assault at a time, and {unit} was on every ridge.',
    ],
    lossTemplates: [
      'The carriers had to stand off exactly one sea-skimming missile too far, and the amphibious timetable drowned in the details.',
      'Winter in the South Atlantic sank more of the plan than the enemy did, and the enemy was trying hard.',
    ],
  },
  {
    id: 'gulf',
    name: 'The Gulf War',
    subtitle: 'The Final Exam',
    era: '1991',
    objective: 'Assemble a coalition, win the air, then win the ground in 100 hours.',
    role: 'attacker',
    tags: ['desert', 'air'],
    tests: ['airsup', 'coalition', 'intel', 'logistics', 'blitz'],
    weights: { tech: 0.35, atk: 0.2, mob: 0.25, int: 0.2 },
    baseD: 7.9,
    boss: true,
    winTemplates: [
      'Thirty-eight days of air, one hundred hours of ground, one left hook through the empty desert — {unit} passed history’s final exam with time on the clock.',
      'The coalition of thirty-nine nations agreed on the plan because {unit} made the plan impossible to argue with.',
    ],
    lossTemplates: [
      'Your army fought the last war brilliantly. The enemy fought the next one, from altitude, at night, with receipts.',
      'The left hook found your flank exactly where the doctrine you didn’t update said it couldn’t.',
    ],
  },
]

/** Slate lint data — used by scripts/balance.ts to enforce the domain quotas. */
export const QUOTAS: Array<{ label: string; min: number; test: (k: CampaignKind) => boolean }> = [
  { label: 'naval', min: 12, test: (k) => k.tests.includes('naval') || k.tags.includes('naval') },
  { label: 'air', min: 10, test: (k) => k.tests.includes('air') || k.tests.includes('airsup') || k.tags.includes('air') },
  { label: 'siege/fortified', min: 10, test: (k) => k.tests.includes('siege') || k.tests.includes('trench') || k.tests.includes('defense') },
  { label: 'irregular', min: 8, test: (k) => k.tests.includes('irregular') },
  { label: 'extreme terrain/weather', min: 10, test: (k) => k.tags.some((t) => ['winter', 'desert', 'jungle', 'mountain', 'steppe'].includes(t)) },
  { label: 'severe logistics', min: 15, test: (k) => k.tests.includes('logistics') || k.tests.includes('supply') || (k.weights.log ?? 0) >= 0.3 },
  { label: 'coalition/intel', min: 10, test: (k) => k.tests.includes('coalition') || k.tests.includes('intel') },
]
