/** Campaign archetypes. 82-game seasons are drawn from these, seeded per day. */
import type { CampaignKind } from './types'

export const CAMPAIGN_KINDS: CampaignKind[] = [
  {
    id: 'open-clash',
    names: ['The Grand Melee', 'The Field of Banners', 'The Second Grand Melee', 'The Last Open Field'],
    tags: ['open'],
    weights: { atk: 0.3, def: 0.2, mob: 0.2, grit: 0.2, int: 0.1 },
    baseD: 6.2,
    desc: 'set-piece field battle',
    winTemplates: [
      'Two armies met in the open, which suited yours fine — {unit} decided it early.',
      'A classic pitched battle. {unit} treated it like a home game.',
    ],
    lossTemplates: [
      'A fair fight in an open field, which was the problem — {enemy} was simply better drilled that day.',
      'Everything held except the center, which is unfortunately where {enemy} was.',
    ],
  },
  {
    id: 'winter-march',
    names: ['The Frozen March', 'The Long Cold', 'The Second Frozen March', 'The White Silence'],
    tags: ['winter'],
    weights: { log: 0.35, grit: 0.3, mob: 0.15, def: 0.2 },
    baseD: 7.0,
    desc: 'winter offensive',
    winTemplates: [
      'The snow came early and stayed late. Your army, insultingly, thrived — {unit} led the way.',
      'While {enemy} froze to their maps, {unit} kept your army fed, moving, and smug.',
    ],
    lossTemplates: [
      'The cold defeated you before {enemy} could. The cold has now won 1,247 consecutive wars.',
      'Your supply line froze at mile forty. {enemy} just had to wait, which they did, indoors.',
    ],
  },
  {
    id: 'island-hop',
    names: ['The Archipelago Campaign', 'The Thousand-Island War', 'The Atoll Grind', 'The Far Islands'],
    tags: ['naval'],
    weights: { mob: 0.2, log: 0.3, atk: 0.2, grit: 0.15, tech: 0.15 },
    baseD: 6.8,
    desc: 'island-hopping campaign',
    winTemplates: [
      'Island by island, {unit} turned an ocean into a to-do list.',
      '{unit} made every beach a front door. {enemy} ran out of islands first.',
    ],
    lossTemplates: [
      'Your army is magnificent and was, for most of this war, on the wrong island.',
      '{enemy} simply held the water between you and everything. Boats, it turns out, matter.',
    ],
  },
  {
    id: 'urban-siege',
    names: ['The Hundred-Gate Siege', 'The Siege of the Iron City', 'The Second Hundred-Gate Siege', 'The Walls War'],
    tags: ['urban'],
    weights: { atk: 0.3, log: 0.25, grit: 0.25, tech: 0.2 },
    baseD: 7.0,
    desc: 'great city siege',
    winTemplates: [
      'The walls were rated impregnable. {unit} filed a formal disagreement.',
      'After a textbook siege, {unit} opened the gates from the inconvenient side.',
    ],
    lossTemplates: [
      'The city held. {enemy} waved from the walls, which is legal but hurtful.',
      'Your siege lasted eight months, at which point the defenders politely asked if you needed anything.',
    ],
  },
  {
    id: 'mountain-pass',
    names: ['The High Passes', 'The Roof of the World', 'The Second High Passes', 'The Knife-Edge Campaign'],
    tags: ['mountain'],
    weights: { mob: 0.3, grit: 0.3, log: 0.2, def: 0.2 },
    baseD: 6.6,
    desc: 'mountain campaign',
    winTemplates: [
      'The enemy held every pass except the one {unit} invented.',
      'Altitude, avalanches, and {enemy} — beaten in that order, mostly by {unit}.',
    ],
    lossTemplates: [
      'The mountains were neutral, which was still better odds than your army got.',
      '{enemy} held the high ground, and your assault brief said only “climb angrily.”',
    ],
  },
  {
    id: 'desert-war',
    names: ['The Sea of Sand', 'The Scorched Campaign', 'The Second Sea of Sand', 'The Dune War'],
    tags: ['desert'],
    weights: { log: 0.35, mob: 0.25, tech: 0.2, grit: 0.2 },
    baseD: 6.8,
    desc: 'desert war',
    winTemplates: [
      'Water discipline won this war. {unit} rationed like poets and fought like accountants, which is a compliment.',
      'The desert eats armies. {unit} taught yours to eat the desert first.',
    ],
    lossTemplates: [
      'Your army chased mirages for a month; {enemy} just followed you at a polite distance with water.',
      'The desert claimed your supply line, your timetable, and finally your dignity, in that order.',
    ],
  },
  {
    id: 'jungle-shadow',
    names: ['The Green Labyrinth', 'The Canopy War', 'The Second Green Labyrinth', 'The Monsoon Front'],
    tags: ['jungle'],
    weights: { grit: 0.3, int: 0.25, mob: 0.2, log: 0.25 },
    baseD: 6.9,
    desc: 'jungle campaign',
    winTemplates: [
      'The jungle picks the winner, and {unit} spoke fluent jungle.',
      '{enemy} controlled every clearing. {unit} controlled everything else, which is the jungle.',
    ],
    lossTemplates: [
      'Your maps showed roads. The jungle disagreed, and the jungle had seniority.',
      '{enemy} vanished into the treeline with your momentum and, somehow, your boots.',
    ],
  },
  {
    id: 'naval-blockade',
    names: ['The Great Blockade', 'The Strangled Sea', 'The Second Great Blockade', 'The Closed Strait'],
    tags: ['naval'],
    weights: { def: 0.25, log: 0.3, int: 0.15, atk: 0.3 },
    baseD: 6.5,
    desc: 'naval blockade',
    winTemplates: [
      '{unit} closed the sea like a shop at 5 p.m. {enemy} starved for options.',
      'Nothing entered, nothing left. {unit} ran the blockade like a subscription service {enemy} couldn’t cancel.',
    ],
    lossTemplates: [
      'Blockade-running became {enemy}’s national sport, and your navy the beloved home crowd.',
      'Your blockade had one gap. {enemy} made it a boulevard.',
    ],
  },
  {
    id: 'trench-grind',
    names: ['The Long Stalemate', 'The Mud Ledger', 'The Second Long Stalemate', 'The Hundred-Meter War'],
    tags: ['open'],
    weights: { def: 0.35, grit: 0.35, log: 0.2, tech: 0.1 },
    baseD: 6.7,
    desc: 'trench stalemate',
    winTemplates: [
      'A war measured in meters. {unit} bought them wholesale.',
      'Both sides dug in; only yours brought {unit}, which turned patience into a weapon.',
    ],
    lossTemplates: [
      'Four years, three trenches, two poets, one loss.',
      '{enemy} out-suffered you, which in trench warfare is the entire scoreboard.',
    ],
  },
  {
    id: 'blitz',
    names: ['The Lightning Week', 'The Six-Day Sprint', 'The Second Lightning Week', 'The Overnight War'],
    tags: ['open'],
    weights: { mob: 0.4, atk: 0.3, tech: 0.15, log: 0.15 },
    baseD: 6.4,
    desc: 'lightning offensive',
    winTemplates: [
      'The war was over before {enemy}’s declaration finished printing. {unit} set the pace.',
      '{unit} moved so fast the enemy’s counterattack hit last week.',
    ],
    lossTemplates: [
      '{enemy} was inside your headquarters before your army finished breakfast. Speed kills; yours strolled.',
      'Your counterblow landed with tremendous force on a field {enemy} had left on Tuesday.',
    ],
  },
  {
    id: 'air-supremacy',
    names: ['The War for the Sky', 'The High Duel', 'The Second War for the Sky', 'The Ceiling Campaign'],
    tags: ['air'],
    weights: { tech: 0.4, atk: 0.25, mob: 0.2, int: 0.15 },
    baseD: 6.9,
    desc: 'air-supremacy duel',
    winTemplates: [
      'The sky changed owners in an afternoon. {unit} kept the receipt.',
      '{unit} won the air war so thoroughly the enemy’s birds filed for neutrality.',
    ],
    lossTemplates: [
      '{enemy} owned the sky, and everything under the sky, which is — checking — everything.',
      'Your air arm fought bravely, briefly, and vertically downward.',
    ],
  },
  {
    id: 'spy-war',
    names: ['The Quiet War', 'The Paper Shadows', 'The Second Quiet War', 'The War of Whispers'],
    tags: ['night'],
    weights: { int: 0.5, tech: 0.2, grit: 0.15, mob: 0.15 },
    baseD: 6.6,
    desc: 'intelligence war',
    winTemplates: [
      'No battles were fought. {unit} won anyway, which should worry everyone.',
      '{unit} read every enemy plan pre-draft. The war was a formality with casualties of zero.',
    ],
    lossTemplates: [
      'Every plan you made was on {enemy}’s desk by morning, annotated, with a smiley face.',
      'Your codes were broken; worse, your crossword was completed.',
    ],
  },
  {
    id: 'night-ambush',
    names: ['The Midnight War', 'The Long Night', 'The Second Midnight War', 'The Hour of the Wolf'],
    tags: ['night'],
    weights: { int: 0.3, grit: 0.25, mob: 0.25, atk: 0.2 },
    baseD: 6.5,
    desc: 'night campaign',
    winTemplates: [
      'The decisive battle happened at 3 a.m., and only your side had {unit} awake for it.',
      '{unit} owned the dark. {enemy} kept lighting torches, which mostly helped you aim.',
    ],
    lossTemplates: [
      '{enemy} attacked at night, which your sentries had filed under “rude” rather than “possible.”',
      'The password was compromised, the geese were asleep, and the rest is a very short chapter.',
    ],
  },
  {
    id: 'supply-race',
    names: ['The Hunger Games of Logistics', 'The Long Road War', 'The Great Supply Race', 'The Depot Derby'],
    tags: ['open'],
    weights: { log: 0.45, mob: 0.3, grit: 0.1, int: 0.15 },
    baseD: 6.6,
    desc: 'logistics race',
    winTemplates: [
      'Amateurs talk tactics; {unit} won this entire war with timetables.',
      'The army that eats, wins. {unit} catered; {enemy} foraged; the end.',
    ],
    lossTemplates: [
      'Your spearhead was unstoppable right up until it checked its fuel gauge.',
      '{enemy}’s supply columns ran like clockwork; yours ran like folklore.',
    ],
  },
  {
    id: 'amphibious',
    names: ['The Stormed Shore', 'The Landing', 'The Second Stormed Shore', 'The Contested Coast'],
    tags: ['naval'],
    weights: { atk: 0.3, log: 0.3, grit: 0.2, tech: 0.2 },
    baseD: 7.1,
    desc: 'amphibious invasion',
    winTemplates: [
      'The beach was rated impossible. {unit} took it before the tide changed its mind.',
      'First wave ashore, {unit} made the shoreline a formality.',
    ],
    lossTemplates: [
      'The landing met the one thing amphibious planners fear: {enemy}, on time.',
      'Your invasion fleet performed beautifully in every respect except arriving where the plan said.',
    ],
  },
  {
    id: 'steppe-raid',
    names: ['The Endless Steppe', 'The Horizon War', 'The Second Endless Steppe', 'The Grass Sea'],
    tags: ['steppe'],
    weights: { mob: 0.45, atk: 0.2, log: 0.2, int: 0.15 },
    baseD: 6.4,
    desc: 'steppe war',
    winTemplates: [
      'On the open steppe there is nowhere to hide, which was {enemy}’s problem, because {unit} was faster.',
      '{unit} fought the horizon to a draw and {enemy} to a rout.',
    ],
    lossTemplates: [
      '{enemy} refused battle for six weeks, then accepted it, all at once, from four directions.',
      'Your army won every engagement it could catch, which was none of them.',
    ],
  },
  {
    id: 'great-defense',
    names: ['The Unbreakable Line', 'The Home Stand', 'The Second Unbreakable Line', 'The Last Wall'],
    tags: ['urban'],
    weights: { def: 0.4, grit: 0.3, log: 0.2, int: 0.1 },
    baseD: 6.3,
    desc: 'heroic defense',
    winTemplates: [
      '{enemy} broke against your line like weather. {unit} was the line.',
      'They came in waves. {unit} was the beach. The metaphor holds up; the enemy didn’t.',
    ],
    lossTemplates: [
      'The unbreakable line broke, which is a branding issue on top of a military one.',
      '{enemy} found the seam between your units — the seam’s name is on the court-martial docket.',
    ],
  },
  {
    id: 'two-front',
    names: ['THE TWO-FRONT NIGHTMARE', 'THE VISE', 'THE SECOND TWO-FRONT NIGHTMARE', 'THE PINCER OF AGES'],
    tags: ['open', 'winter'],
    weights: { atk: 0.15, def: 0.15, mob: 0.15, log: 0.2, grit: 0.2, int: 0.15 },
    baseD: 8.2,
    desc: 'two-front war',
    winTemplates: [
      'Two fronts, one army, zero panic. {unit} commuted between wars and won both.',
      'The textbook says never fight on two fronts. {unit} wrote a correction in the margins.',
    ],
    lossTemplates: [
      'Two fronts, as advertised, was one too many.',
      'You held the east magnificently while losing the west, then rotated, symmetrically, forever.',
    ],
  },
  {
    id: 'long-retreat',
    names: ['The Fighting Withdrawal', 'The Long Walk Back', 'The Second Fighting Withdrawal', 'The Rearguard Epic'],
    tags: ['winter'],
    weights: { mob: 0.35, grit: 0.3, def: 0.2, log: 0.15 },
    baseD: 6.2,
    desc: 'fighting withdrawal',
    winTemplates: [
      'You retreated 300 miles, destroyed everything of value, and {enemy} conquered a souvenir shop.',
      'The rearguard, led by {unit}, made the pursuit so expensive {enemy} asked to stop pursuing.',
    ],
    lossTemplates: [
      'The organized withdrawal lost the word “organized” around mile sixty.',
      'The rearguard became the vanguard, which is retreat-ese for “it went badly.”',
    ],
  },
  {
    id: 'propaganda',
    names: ['The War of Words', 'The Morale Front', 'The Second War of Words', 'The Hearts-and-Banners Campaign'],
    tags: ['urban'],
    weights: { int: 0.4, grit: 0.35, tech: 0.1, mob: 0.15 },
    baseD: 6.3,
    desc: 'morale war',
    winTemplates: [
      'Not a shot fired. {unit} convinced the enemy army it had already lost, and it agreed.',
      '{unit} won the story of the war, after which the war itself was a formality.',
    ],
    lossTemplates: [
      '{enemy}’s pamphlets were funnier than yours. Wars have been lost over less. This one, for instance.',
      'Your troops read the enemy’s leaflets, and, worse, subscribed.',
    ],
  },
  {
    id: 'absurd',
    names: ['THE ABSURD FRONT', 'The War Nobody Believes Happened', 'THE SECOND ABSURD FRONT', 'The Great Nonsense'],
    tags: ['open'],
    weights: { grit: 0.4, int: 0.3, mob: 0.3 },
    baseD: 6.0,
    desc: 'a war historians refuse to footnote',
    winTemplates: [
      'Nothing about this war made sense, which favored the army with {unit} on the roster.',
      'Chaos was the terrain, and {unit} was born there.',
    ],
    lossTemplates: [
      'You lost a war that officially never happened, to {enemy}, who officially doesn’t exist. Painful either way.',
      'The fog of war became a full absurdist theater season, and {enemy} had better reviews.',
    ],
  },
  {
    id: 'river-crossing',
    names: ['The Contested Crossing', 'The River War', 'The Second Contested Crossing', 'The Bridgehead'],
    tags: ['open'],
    weights: { log: 0.3, mob: 0.3, atk: 0.2, grit: 0.2 },
    baseD: 6.5,
    desc: 'river-crossing operation',
    winTemplates: [
      'The river was the border until {unit} decided it was a road.',
      'Under fire, over water, on schedule — {unit} made the far bank a fait accompli.',
    ],
    lossTemplates: [
      'Your pontoon bridge was flawless for the first two-thirds of the river.',
      '{enemy} let half your army cross, which you briefly interpreted as generosity.',
    ],
  },
  {
    id: 'high-seas',
    names: ['The Cannonade of the Century', 'The Great Fleet Action', 'The Second Cannonade', 'The Trafalgar Rematch'],
    tags: ['naval'],
    weights: { atk: 0.35, mob: 0.2, tech: 0.2, grit: 0.15, int: 0.1 },
    baseD: 6.6,
    desc: 'grand fleet battle',
    winTemplates: [
      'Two fleets, one horizon, no doubt: {unit} owned the weather gauge and the afternoon.',
      'The enemy line broke in the smoke, and {unit} sailed through the gap into legend.',
    ],
    lossTemplates: [
      '{enemy} crossed your T, which sounds friendly and is the opposite.',
      'Your fleet fought the sea and {enemy} simultaneously, splitting effort between two undefeated opponents.',
    ],
  },
  {
    id: 'airborne-drop',
    names: ['The Sky Landing', 'The Vertical Envelopment', 'The Second Sky Landing', 'The Drop Zone War'],
    tags: ['air', 'night'],
    weights: { mob: 0.35, grit: 0.25, tech: 0.2, int: 0.2 },
    baseD: 7.0,
    desc: 'airborne operation',
    winTemplates: [
      'Your army skipped the front line entirely — {unit} arrived from the ceiling.',
      'Dawn found {unit} behind every enemy position at once, holding the bridges and the punchline.',
    ],
    lossTemplates: [
      'The drop scattered your elite across nine counties, where they fought nine excellent, unrelated wars.',
      '“A bridge too far,” the report says, though the bridge would argue you were an army too few.',
    ],
  },
]

/** Silly enemy factions your army faces across the season. */
export const ENEMIES: string[] = [
  'The Coalition of the Mildly Concerned',
  'The Eternal Horde',
  'The Grand Duchy of Spite',
  'The League of Extremely Armed Neutrals',
  'The Second-Best Empire',
  'The Confederated Warlords of the Bureaucracy',
  'The Kingdom of Two Rivers and a Grudge',
  'The Sunless Tsardom',
  'The Free Company of Invoice Collectors',
  'The Empire on Which the Sun Politely Sets',
  'The Republic of the Perpetual Emergency',
  'The Host of a Thousand Banners (Discount Store)',
  'The Sublime Porteʼs Angriest Cousins',
  'The Alliance of People Your Commander Insulted',
  'The Old Enemy (You Know the One)',
  'The Serene and Furious Republic',
  'The Khanate of the Wrong Steppe',
  'The Principality of Ambush Valley',
  'The Iron Pact of the Discount Blacksmiths',
  'The Navy of the Landlocked Kingdom',
  'The Twelve Angry Fiefdoms',
  'The Empire of the Recently Insulted',
  'The Glorious Union of Rival Twins',
  'The Dread Fleet of the Inland Sea',
  'The Duchy of Suspiciously Good Archers',
  'The Winter Court (Away Game)',
  'The Union of Concerned Siege Engineers',
  'The Most Serene Pirate Concern',
  'The Grand Army of the Neighboring Timeline',
  'The Federation of Everyone You Beat Earlier',
  'The Emirate of the Endless Dunes',
  'The Committee of Public Safety (Reformed)',
  'The Legion of the Unpaid Mercenaries',
  'The Dynasty of the Uphill Fortress',
  'The Queendom of the Long Memory',
  'The Syndicate of Rented Elephants',
  'The Order of the Inverted Map',
  'The Tribunal of Retired Conquerors',
  'The Riders of the Borrowed Horses',
  'The Fog Itself (Contains Soldiers)',
]
