/**
 * Phase 1b expansion, support arms: INTELLIGENCE, LOGISTICS, WILD CARD.
 *
 * Opens INTEL into medieval/gunpowder/sail/WWI, LOGISTICS into
 * gunpowder/sail/industrial/WWI/cold war, and WILD CARD into
 * medieval/sail/WWI/WWII/cold war (finally making the Emu War dealable).
 *
 * Stats follow RATINGS.md (era-relative; every 8+/≤3 citable). Attested
 * absurdities are rated as what they literally were — the Emu War standard.
 * New bridge fields (doctrine/comms glue) only on true signal systems:
 * the Chappe Telegraph, the Beacon Line, the Hotline.
 */
import type { Pick, Stats } from './types'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const INTEL_1B: Pick[] = [
  // ── MEDIEVAL (depth, joins Bureau of Intrigue + Yam) ─────────────────────
  {
    id: 'int-assassins',
    slot: 'intel',
    name: 'The Assassins of Alamut',
    origin: 'Nizari Persia',
    year: 1090,
    blurb: 'Operated from a mountain fortress for 150 years. Deliverables: guaranteed. References: nervous.',
    stats: s(6, 7, 6, 4, 5, 9, 9),
    terrain: { mountain: 2, night: 2 },
    special: { trigger: 'night', bonus: 1.2, label: 'The appointment keeps itself' },
    lines: {
      win: 'The enemy commander found the dagger pinned to his tent flap as a courtesy, and negotiations opened at dawn.',
      loss: 'The contract lapsed. Alamut has issued a rare refund and a rarer apology.',
      ana: 'The Assassins reviewed the encrypted messaging app and asked why anyone would write the plan down at all.',
    },
  },
  {
    id: 'int-beacons',
    slot: 'intel',
    name: 'The Beacon Line',
    origin: 'Great Wall of China',
    year: 1211,
    blurb: 'Smoke by day, fire by night, news of the frontier moving faster than any horse for a thousand miles.',
    stats: s(2, 6, 8, 5, 6, 6, 8),
    terrain: { mountain: 1, night: 1 },
    bridge: 1,
    special: { trigger: 'defense', bonus: 1.2, label: 'The wall sees first' },
    lines: {
      win: 'The beacons lit one by one, and the capital knew before the invaders had finished breakfast.',
      loss: 'The third tower overslept, and the message arrived as the enemy, in person.',
      ana: 'The beacon crews were shown fiber optics and nodded: light in a line, brothers, light in a line.',
    },
  },
  // ── GUNPOWDER (depth, joins Walsingham + Iga Shinobi) ────────────────────
  {
    id: 'int-tencouncil',
    slot: 'intel',
    name: 'The Council of Ten',
    origin: 'Venice',
    year: 1570,
    blurb: 'A republic run on ciphers, informants, and a mailbox shaped like a lion’s mouth. For tips.',
    stats: s(4, 7, 5, 7, 8, 6, 9),
    terrain: { naval: 1, urban: 1 },
    special: { trigger: 'naval', bonus: 1.2, label: 'Every port has a correspondent' },
    lines: {
      win: 'The Council knew the enemy fleet’s sailing date before its own admiral did, and priced the war accordingly.',
      loss: 'The Council lost the battle but has already recruited the enemy’s clerk, so technically this is an onboarding.',
      ana: 'The Council examined the anonymous tip line and asked where the marble lion’s mouth goes.',
    },
  },
  {
    id: 'int-greatcipher',
    slot: 'intel',
    name: 'The Great Cipher',
    origin: 'France',
    year: 1670,
    blurb: 'The Rossignol family code. Unbroken for two hundred years. Password hint: none.',
    stats: s(2, 9, 4, 5, 9, 6, 9),
    terrain: {},
    special: { trigger: 'siege', bonus: 1.2, label: 'The fortress orders stay sealed' },
    lines: {
      win: 'The dispatches crossed enemy country in plain sight, smugly, and the siege orders arrived still virgin.',
      loss: 'The courier was taken; the cipher held; the enemy now owns a very confident piece of paper.',
      ana: 'The Rossignols reviewed modern encryption, sniffed, and asked how long “until the computers get bored.”',
    },
  },
  // ── SAIL & EMPIRE (depth, joins Culper Ring + Balloon Corps) ─────────────
  {
    id: 'int-scovell',
    slot: 'intel',
    name: 'Scovell’s Guides',
    origin: 'Britain',
    year: 1812,
    blurb: 'Broke Napoleon’s Great Paris Cipher with patience, captured mail, and one extremely tidy notebook.',
    stats: s(3, 6, 6, 5, 7, 6, 10),
    terrain: {},
    special: { trigger: 'intel', bonus: 1.3, label: 'Reads the enemy’s mail at breakfast' },
    lines: {
      win: 'Wellington fought the battle having already read the enemy’s orders, twice, with marginal notes.',
      loss: 'The intercepts were perfect; the cavalry sent to exploit them stopped for lunch.',
      ana: 'Scovell audited the code-breaking supercomputer and found it thorough but showy.',
    },
  },
  {
    id: 'int-chappe',
    slot: 'intel',
    name: 'The Chappe Telegraph',
    origin: 'France',
    year: 1794,
    blurb: 'Semaphore towers relaying Paris to the frontier in minutes. The internet, powered by arms and clerks.',
    stats: s(1, 5, 9, 6, 9, 5, 8),
    terrain: {},
    bridge: 1,
    special: { trigger: 'blitz', bonus: 1.2, label: 'Orders outrun horses' },
    lines: {
      win: 'Paris asked a question at nine and moved the army at ten, and the enemy is still blaming witchcraft.',
      loss: 'Fog. The republic’s entire command system was defeated by fog.',
      ana: 'The Chappe operators saw the smartphone and asked only one question: “what is your fog policy?”',
    },
  },
  // ── WWI (new cell around the Carrier Pigeon Corps) ───────────────────────
  {
    id: 'int-room40',
    slot: 'intel',
    name: 'Room 40',
    origin: 'Britain',
    year: 1917,
    blurb: 'Read the Zimmermann Telegram before its intended recipient did. Changed the war with a memo.',
    stats: s(3, 7, 4, 6, 9, 6, 10),
    terrain: { naval: 1 },
    special: { trigger: 'naval', bonus: 1.3, label: 'The enemy fleet RSVPs to us' },
    lines: {
      win: 'Room 40 decoded the sortie order with time to spare and the ambush was catered.',
      loss: 'The intercept was perfect and the distribution list was not; the fleet learned of it in the newspaper.',
      ana: 'Room 40 toured the signals-intelligence agency and left a note: “bigger room, same job.”',
    },
  },
  {
    id: 'int-dameblanche',
    slot: 'intel',
    name: 'La Dame Blanche',
    origin: 'Occupied Belgium',
    year: 1917,
    blurb: 'A thousand-agent network counting enemy trains from kitchen windows. History’s politest surveillance state.',
    stats: s(2, 6, 5, 5, 5, 9, 10),
    terrain: {},
    special: { trigger: 'intel', bonus: 1.3, label: 'Every timetable, hand-copied' },
    lines: {
      win: 'Every troop train was counted, logged, and reported by observers the occupation had rated “harmless.”',
      loss: 'The network went quiet for a week, which the network wishes noted was itself a message.',
      ana: 'La Dame Blanche examined the spy satellite and asked whether it also notes when the soldiers look tired.',
    },
  },
  {
    id: 'int-choctaw',
    slot: 'intel',
    name: 'The Choctaw Code Talkers',
    origin: 'Choctaw Nation / United States',
    year: 1918,
    altSlot: 'ground',
    blurb: 'Put the phone lines back in play in a language no eavesdropper on Earth had a dictionary for.',
    stats: s(5, 6, 6, 4, 6, 8, 10),
    terrain: {},
    special: { trigger: 'trench', bonus: 1.2, label: 'The wire is safe again' },
    lines: {
      win: 'The orders went over open lines, the enemy transcribed every word, and the words remained a mystery.',
      loss: 'The message got through perfectly; command declined to believe it, in English.',
      ana: 'The Choctaw talkers met the encryption chip and congratulated it on finally catching up to 1918.',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'int-mincemeat',
    slot: 'intel',
    name: 'Operation Mincemeat',
    origin: 'Britain',
    year: 1943,
    blurb: 'A briefcase of fake plans delivered by tide. The enemy moved an army for a man who never was.',
    stats: s(2, 5, 3, 4, 7, 6, 10),
    terrain: { naval: 1 },
    special: { trigger: 'intel', bonus: 1.3, label: 'The decoy documents are load-bearing' },
    lines: {
      win: 'The enemy reinforced the wrong island with total confidence, citing documents of impeccable fiction.',
      loss: 'The briefcase was believed; the follow-up landing, unfortunately, still had to be real.',
      ana: 'The Mincemeat team reviewed deepfakes and sighed: “in our day, forgery required a typewriter and nerve.”',
    },
  },
]

export const LOGISTICS_1B: Pick[] = [
  // ── GUNPOWDER (new cell around the Inca Runners) ─────────────────────────
  {
    id: 'log-spanishroad',
    slot: 'logistics',
    name: 'The Spanish Road',
    origin: 'Spain',
    year: 1580,
    blurb: 'A thousand-kilometer military corridor with staging inns. The original deployment pipeline.',
    stats: s(2, 6, 7, 9, 6, 6, 5),
    terrain: { mountain: 1 },
    special: { trigger: 'supply', bonus: 1.2, label: 'The army walks in, pre-fed' },
    lines: {
      win: 'The tercios arrived from Milan fed, paid, and rested, which in this century constitutes a war crime of competence.',
      loss: 'A bridge closed in the Alps, and the entire strategy of a global empire queued behind one mule.',
      ana: 'The Road’s quartermasters studied the airlift manifest and asked where the inns are. There are no inns. Barbaric.',
    },
  },
  {
    id: 'log-voc',
    slot: 'logistics',
    name: 'The Dutch East India Company',
    origin: 'Dutch Republic',
    year: 1650,
    blurb: 'A corporation with a navy, an army, and a spreadsheet that outranks both.',
    stats: s(5, 6, 7, 10, 7, 5, 7),
    terrain: { naval: 2 },
    special: { trigger: 'supply', bonus: 1.2, label: 'War, freight included' },
    lines: {
      win: 'The Company won the campaign and booked it as a quarterly result, with the victory as a line item.',
      loss: 'The Company lost the battle and immediately shorted the province.',
      ana: 'The VOC reviewed the defense contractor’s invoice and wept with pride at what the child had become.',
    },
  },
  {
    id: 'log-grainfleet',
    slot: 'logistics',
    name: 'The Grand Canal Grain Fleet',
    origin: 'Ming China',
    year: 1460,
    blurb: 'Eleven thousand barges moving an empire’s calories on schedule. The canal is the constitution.',
    stats: s(1, 6, 5, 10, 6, 6, 4),
    terrain: { naval: 1 },
    special: { trigger: 'supply', bonus: 1.3, label: 'The rice arrives regardless' },
    lines: {
      win: 'The grain arrived, the army ate, the war continued on schedule. The fleet considers this the entire art of war.',
      loss: 'The canal silted at mile four hundred, and strategy became a negotiation with mud.',
      ana: 'The barge masters audited the container ship and approved: “a barge that found the ocean. Good for her.”',
    },
  },
  // ── SAIL & EMPIRE (new cell around the Foraging Corps) ───────────────────
  {
    id: 'log-appert',
    slot: 'logistics',
    name: 'Appert’s Cannery',
    origin: 'France',
    year: 1810,
    blurb: 'Won Napoleon’s food-preservation prize by inventing canning. The tin opener arrives 45 years later.',
    stats: s(1, 7, 5, 9, 8, 5, 3),
    terrain: {},
    special: { trigger: 'supply', bonus: 1.2, label: 'Summer, sealed in glass' },
    lines: {
      win: 'The army marched through winter eating June, and the enemy’s foragers found only empty jars and despair.',
      loss: 'The supply held perfectly; the bayonet-as-can-opener situation has been referred to a committee.',
      ana: 'Monsieur Appert inspected the MRE, tasted one, and requested his prize back.',
    },
  },
  {
    id: 'log-victualling',
    slot: 'logistics',
    name: 'The Royal Victualling Board',
    origin: 'Britain',
    year: 1795,
    blurb: 'Beat scurvy with lemon juice and paperwork, doubling the effective size of the fleet for free.',
    stats: s(2, 7, 5, 9, 6, 6, 5),
    terrain: { naval: 2 },
    special: { trigger: 'blockade', bonus: 1.2, label: 'The blockade stays healthy' },
    lines: {
      win: 'The fleet held station for two years, teeth intact, while the enemy’s crews dissolved into medical history.',
      loss: 'The victory was lost ashore; the Board notes the sailors, at least, were magnificently hydrated.',
      ana: 'The Board examined the vitamin supplement aisle and declared the entire modern world “our doing, you’re welcome.”',
    },
  },
  {
    id: 'log-muletrain',
    slot: 'logistics',
    name: 'Wellington’s Mule Trains',
    origin: 'Britain / Portugal',
    year: 1812,
    blurb: 'Nine thousand mules, paid in cash, on time. The enemy forages; we invoice.',
    stats: s(1, 6, 6, 9, 4, 8, 4),
    terrain: { mountain: 2 },
    special: { trigger: 'mountain', bonus: 1.2, label: 'The mules know the pass' },
    lines: {
      win: 'The mules delivered through country the enemy’s wagons rated impossible, and were paid before the infantry.',
      loss: 'The mules are fine. The mules are always fine. The plan that outran the mules is not.',
      ana: 'The muleteers watched the cargo drone struggle uphill in the wind and patted their mules meaningfully.',
    },
  },
  // ── INDUSTRIAL (new cell) ────────────────────────────────────────────────
  {
    id: 'log-haupt',
    slot: 'logistics',
    name: 'Haupt’s Railroad Corps',
    origin: 'United States',
    year: 1863,
    blurb: 'Rebuilt burned bridges faster than the enemy could burn them, to the enemy’s documented despair.',
    stats: s(3, 7, 8, 10, 8, 7, 5),
    terrain: {},
    special: { trigger: 'supply', bonus: 1.2, label: 'The bridge is back by Thursday' },
    lines: {
      win: 'The enemy burned the bridge, rode away satisfied, and heard the train cross it that evening.',
      loss: 'The line was cut faster than even Haupt could lay it, and the general has gone to yell at a map.',
      ana: 'Haupt’s crews studied the prefab bridge kit and asked why it took everyone a century and a half.',
    },
  },
  {
    id: 'log-prussianrail',
    slot: 'logistics',
    name: 'The Prussian Railway Section',
    origin: 'Prussia',
    year: 1870,
    blurb: 'Mobilization as a train schedule: three armies, one timetable, zero excuses accepted.',
    stats: s(2, 7, 9, 10, 8, 6, 6),
    terrain: {},
    special: { trigger: 'logistics', bonus: 1.2, label: 'H-hour is printed' },
    lines: {
      win: 'Three hundred thousand men arrived at the frontier on schedule, and the war was half-won at the platform.',
      loss: 'A junction jammed, the timetable slipped nine minutes, and the Section has opened a formal mourning period.',
      ana: 'The Section reviewed the modern deployment software and asked, coldly, where the printed fallback is.',
    },
  },
  {
    id: 'log-ponyexpress',
    slot: 'logistics',
    name: 'The Pony Express',
    origin: 'United States',
    year: 1860,
    blurb: 'Eighteen months of operation, 160 years of branding. The mail moved; the business model did not.',
    stats: s(1, 3, 10, 6, 4, 8, 6),
    terrain: { open: 2, desert: 1 },
    special: { trigger: 'expedition', bonus: 1.2, label: 'Ten days, coast to coast' },
    lines: {
      win: 'The dispatches crossed the continent in ten days, riders swapping horses like relay batons at a gallop.',
      loss: 'The mail arrived on time; the war it described had, regrettably, been rescheduled by telegraph.',
      ana: 'The riders looked at the email and asked, quietly, if it ever gets to see the mountains.',
    },
  },
  {
    id: 'log-coaling',
    slot: 'logistics',
    name: 'The Coaling Station Network',
    origin: 'Britain',
    year: 1902,
    blurb: 'An empire measured in coal piles. The fleet goes where the depots already are.',
    stats: s(2, 8, 5, 10, 6, 5, 6),
    terrain: { naval: 2 },
    special: { trigger: 'naval', bonus: 1.2, label: 'Every ocean, pre-fueled' },
    lines: {
      win: 'The fleet steamed ten thousand miles through a chain of coal piles owned since before the enemy had a navy.',
      loss: 'The enemy fleet won the battle, then spent three weeks asking neutral ports for coal, politely, in defeat.',
      ana: 'The coaling masters studied underway replenishment and conceded the ocean itself is now a depot. Well played.',
    },
  },
  // ── WWI (new cell) ───────────────────────────────────────────────────────
  {
    id: 'log-voiesacree',
    slot: 'logistics',
    name: 'La Voie Sacrée',
    origin: 'France',
    year: 1916,
    blurb: 'One road into Verdun, one truck every fourteen seconds, for months. The road held. So did Verdun.',
    stats: s(2, 9, 6, 10, 6, 9, 4),
    terrain: {},
    special: { trigger: 'defense', bonus: 1.3, label: 'The road does not close' },
    lines: {
      win: 'A truck passed every fourteen seconds, day and night, and the fortress ate, fired, and held.',
      loss: 'The road held; the plan it fed did not; the drivers would like that distinction minuted.',
      ana: 'The Voie Sacrée drivers reviewed the autonomous convoy and asked who the trucks are holding the line FOR.',
    },
  },
  {
    id: 'log-hoover',
    slot: 'logistics',
    name: 'Hoover’s Food Administration',
    origin: 'United States',
    year: 1917,
    blurb: 'Fed an alliance by asking a continent to skip meatless Mondays. The continent said yes.',
    stats: s(1, 7, 5, 10, 6, 7, 6),
    terrain: {},
    special: { trigger: 'coalition', bonus: 1.2, label: 'The allies eat too' },
    lines: {
      win: 'The convoys sailed full because forty million kitchens quietly agreed, and the alliance stayed standing.',
      loss: 'The food arrived; the ports jammed; somewhere a warehouse holds victory, pending a forklift.',
      ana: 'The Administration reviewed the meal-kit startup and noted it invented wartime rationing with venture funding.',
    },
  },
  {
    id: 'log-camelcorps',
    slot: 'logistics',
    name: 'The Camel Transport Corps',
    origin: 'Egypt',
    year: 1917,
    blurb: 'Tens of thousands of camels hauling a desert campaign, one bad mood at a time.',
    stats: s(2, 6, 7, 9, 3, 8, 4),
    terrain: { desert: 3 },
    special: { trigger: 'desert', bonus: 1.3, label: 'The desert is a supply route now' },
    lines: {
      win: 'The camels crossed the waterless miles with the army’s entire war on their backs, unimpressed throughout.',
      loss: 'The camels delivered everything and regret nothing; the operation they supplied has been asked to reflect.',
      ana: 'The camel handlers watched the helicopter sling-load and agreed it is a camel with worse manners.',
    },
  },
  {
    id: 'log-trenchrail',
    slot: 'logistics',
    name: 'The Trench Railways',
    origin: 'Britain / France',
    year: 1917,
    blurb: 'Toy-sized trains hauling real-sized war the last two miles nothing else could cross.',
    stats: s(2, 7, 6, 9, 6, 6, 4),
    terrain: {},
    special: { trigger: 'trench', bonus: 1.3, label: 'The last two miles run on rails' },
    lines: {
      win: 'The little trains fed the guns through ground that ate mules and trucks alike, ding-dinging politely.',
      loss: 'A shell found the junction, and the front learned what the little trains had been carrying: everything.',
      ana: 'The trench railwaymen rode the theme-park train in silence, then said, “so this is what peace does with us.”',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'log-seabees',
    slot: 'logistics',
    name: 'The Seabees',
    origin: 'United States',
    year: 1943,
    altSlot: 'ground',
    blurb: 'We build, we fight. The airstrip will be done before the argument about whether it’s possible.',
    stats: s(5, 7, 6, 10, 8, 8, 4),
    terrain: { jungle: 2 },
    special: { trigger: 'amphibious', bonus: 1.2, label: 'The beach becomes a base' },
    lines: {
      win: 'The bombers landed on an island that had been jungle nine days earlier, and the Seabees were already elsewhere.',
      loss: 'The runway was finished on time; the situation it was built for was not.',
      ana: 'The Seabees looked at the Roman road network and issued the only compliment they have: “crews like us.”',
    },
  },
  // ── COLD WAR (new cell around Airlift Command) ───────────────────────────
  {
    id: 'log-sealift',
    slot: 'logistics',
    name: 'Military Sealift Command',
    origin: 'United States',
    year: 1990,
    blurb: 'Moved a half-million-person army and its parking lot across the planet in five months.',
    stats: s(2, 7, 7, 10, 8, 6, 5),
    terrain: { naval: 2 },
    special: { trigger: 'expedition', bonus: 1.3, label: 'The army ships as cargo' },
    lines: {
      win: 'The heavy division arrived on the far side of the world with its fuel, its ammo, and its coffee service intact.',
      loss: 'The army arrived complete and magnificent, two weeks after the moment it was needed.',
      ana: 'Sealift Command audited Xerxes’ bridge of boats and stamped it “approved, with notes.”',
    },
  },
  {
    id: 'log-reforger',
    slot: 'logistics',
    name: 'Exercise REFORGER',
    origin: 'NATO',
    year: 1983,
    blurb: 'An annual rehearsal for moving America to Europe, so the real thing would be boring.',
    stats: s(3, 8, 7, 9, 7, 6, 6),
    terrain: {},
    special: { trigger: 'coalition', bonus: 1.3, label: 'The reinforcements are pre-rehearsed' },
    lines: {
      win: 'The reinforcement flowed exactly like the seventeen rehearsals, and the enemy plan quietly retired.',
      loss: 'The convoys performed flawlessly toward a front that had inconveniently moved.',
      ana: 'The REFORGER planners reviewed the Mongol remount system and requested a joint exercise, sincerely.',
    },
  },
  {
    id: 'log-c5',
    slot: 'logistics',
    name: 'C-5 Galaxy Fleet',
    origin: 'United States',
    year: 1970,
    blurb: 'Swallows tanks whole. The nose opens like it’s about to complain, then delivers an armored battalion.',
    stats: s(2, 6, 9, 10, 9, 5, 4),
    terrain: { air: 2 },
    special: { trigger: 'blitz', bonus: 1.2, label: 'Armor, airmailed' },
    lines: {
      win: 'The tanks arrived by air before the crisis finished being declared, which is the entire sales pitch.',
      loss: 'The Galaxy delivered everything perfectly and is not responsible for what the cargo then decided to do.',
      ana: 'Hannibal inspected the C-5’s cargo bay, measured it against an elephant, and sat down, overcome.',
    },
  },
]

export const WILDCARD_1B: Pick[] = [
  // ── MEDIEVAL (new cell around Longbows + Greek Fire) ─────────────────────
  {
    id: 'wld-mansamusa',
    slot: 'wildcard',
    name: 'Mansa Musa’s Gold Caravan',
    origin: 'Mali Empire',
    year: 1324,
    altSlot: 'logistics',
    blurb: 'Crashed Cairo’s economy by walking through it generously. Economic warfare, allegedly by accident.',
    stats: s(2, 5, 6, 10, 5, 8, 6),
    terrain: { desert: 2 },
    special: { trigger: 'propaganda', bonus: 1.4, label: 'The flex is the campaign' },
    lines: {
      win: 'The caravan arrived, distributed gold, and the enemy’s war budget stopped making sense by Friday.',
      loss: 'The war was lost; the exchange rate was won; economists still argue which mattered.',
      ana: 'Mansa Musa’s stewards reviewed quantitative easing and said, “ah, our technique, without the camels.”',
    },
  },
  {
    id: 'wld-warwolf',
    slot: 'wildcard',
    name: 'The Warwolf',
    origin: 'England',
    year: 1304,
    altSlot: 'armor',
    blurb: 'The greatest trebuchet ever built. The castle surrendered first; the king made them wait to be hit anyway.',
    stats: s(9, 3, 1, 4, 8, 6, 2),
    terrain: { urban: 2 },
    special: { trigger: 'siege', bonus: 1.3, label: 'Surrender not accepted (yet)' },
    lines: {
      win: 'The Warwolf was assembled in view of the walls, and the garrison surrendered to the construction schedule.',
      loss: 'The Warwolf arrived in fifty carts, two months late, magnificent and moot.',
      ana: 'The Warwolf crew watched the cruise missile demo and asked if it could at least be made to loom first.',
    },
  },
  // ── SAIL & EMPIRE (new cell around the Bagpipers) ────────────────────────
  {
    id: 'wld-kettlewar',
    slot: 'wildcard',
    name: 'The Kettle War Flotilla',
    origin: 'Holy Roman Empire',
    year: 1784,
    blurb: 'A war with one cannon shot, which hit a soup kettle. Casualties: the soup. Both sides went home.',
    stats: s(2, 2, 4, 3, 3, 4, 3),
    terrain: { naval: 1 },
    authenticity: 'historical',
    special: { trigger: 'absurd', bonus: 1.4, label: 'Aim for the kettle' },
    lines: {
      win: 'One shot was fired, it struck a kettle, and the enemy — genuinely, historically — went home.',
      loss: 'The kettle was avenged. There is no other way to report this.',
      ana: 'The flotilla toured the modern destroyer and asked which gun is the kettle gun. They ALL are, son.',
    },
  },
  {
    id: 'wld-turtle',
    slot: 'wildcard',
    name: 'The Turtle',
    origin: 'Continental America',
    year: 1776,
    altSlot: 'navy',
    blurb: 'The first combat submarine: one man, one hand crank, one screw for attaching bombs. Achieved: legend.',
    stats: s(3, 3, 2, 2, 9, 9, 5),
    terrain: { naval: 2, night: 1 },
    authenticity: 'experimental',
    special: { trigger: 'night', bonus: 1.2, label: 'Invisible (slowly)' },
    lines: {
      win: 'The Turtle bobbed under the flagship, cranked heroically, and the age of the submarine began at one knot.',
      loss: 'The screw met a copper hull, declined, and the Turtle pedaled home into history anyway.',
      ana: 'The Turtle’s operator sat in the nuclear submarine’s gym, on a stationary bike, and felt seen at last.',
    },
  },
  {
    id: 'wld-rabbits',
    slot: 'wildcard',
    name: 'Napoleon’s Rabbit Ambush',
    origin: 'France',
    year: 1807,
    blurb: 'The staged rabbit hunt where the rabbits charged the Emperor. Hundreds of them. He fled to the coach.',
    stats: s(4, 1, 8, 2, 1, 9, 2),
    terrain: { open: 2 },
    authenticity: 'improvised',
    special: { trigger: 'open', bonus: 1.3, label: 'They thought he had the food' },
    lines: {
      win: 'The horde advanced without fear, formation, or the concept of retreat, and the field was theirs in minutes.',
      loss: 'The rabbits dispersed at the first cannon, having already defeated the only emperor they cared about.',
      ana: 'The rabbits surrounded the armored car in seconds. It has food, the descendants insist. It always has food.',
    },
  },
  // ── WWI & INTERWAR (new cell around the Emu Veterans) ────────────────────
  {
    id: 'wld-truce',
    slot: 'wildcard',
    name: 'The Christmas Truce XI',
    origin: 'No Man’s Land',
    year: 1914,
    blurb: 'The football match between the trenches. Final score disputed; the point, for one day, was not.',
    stats: s(1, 5, 4, 3, 2, 10, 5),
    terrain: { winter: 2 },
    special: { trigger: 'propaganda', bonus: 1.4, label: 'For one day, nobody shoots' },
    lines: {
      win: 'Both lines came out, played to a disputed final, swapped buttons, and the war blinked first.',
      loss: 'The whistle blew, the artillery resumed by order, and the XI holds the war itself entirely responsible.',
      ana: 'The XI watched the drone deliver a football to midfield and ruled it offside on principle.',
    },
  },
  {
    id: 'wld-cherami',
    slot: 'wildcard',
    name: 'Cher Ami',
    origin: 'United States / France',
    year: 1918,
    altSlot: 'intel',
    blurb: 'One pigeon, one message, one rescued battalion. Flew the last mile on determination and half a leg.',
    stats: s(1, 3, 9, 2, 2, 10, 8),
    terrain: {},
    special: { trigger: 'intel', bonus: 1.3, label: 'The message gets through' },
    lines: {
      win: 'The message arrived, the barrage lifted, and two hundred men owe the war’s smallest soldier everything.',
      loss: 'The message got through; the men reading it did not hurry; the pigeon has no comment.',
      ana: 'Cher Ami was shown the encrypted satellite uplink and pecked it once, establishing seniority.',
    },
  },
  {
    id: 'wld-maginot',
    slot: 'wildcard',
    name: 'The Maginot Line',
    origin: 'France',
    year: 1930,
    altSlot: 'armor',
    blurb: 'The finest fortifications ever built, in exactly the places the enemy chose not to visit.',
    stats: s(4, 10, 1, 7, 8, 6, 3),
    terrain: { urban: 2 },
    special: { trigger: 'defense', bonus: 1.4, label: 'Impregnable (where present)' },
    lines: {
      win: 'The enemy attacked the Line directly, an act of courtesy the garrison repaid with interest.',
      loss: 'The Line remains undefeated; the country behind it, less so. The garrison would like this noted.',
      ana: 'The Maginot garrison reviewed the cybersecurity firewall and said, softly, “they will go around, friend.”',
    },
  },
  // ── WWII (new cell) ──────────────────────────────────────────────────────
  {
    id: 'wld-wojtek',
    slot: 'wildcard',
    name: 'Corporal Wojtek',
    origin: 'Poland',
    year: 1944,
    altSlot: 'logistics',
    blurb: 'A bear, formally enlisted with rank and paybook, who carried artillery shells at Monte Cassino. All true.',
    stats: s(5, 6, 5, 8, 1, 10, 3),
    terrain: { mountain: 2 },
    authenticity: 'historical',
    special: { trigger: 'mountain', bonus: 1.3, label: 'The shells arrive, bear-carried' },
    lines: {
      win: 'Wojtek carried shells all day, never dropped one, and the battery painted him on everything they own.',
      loss: 'The position fell; Wojtek was blameless; the enlistment paperwork stands as the war’s finest document.',
      ana: 'Wojtek regarded the ammunition-handling robot, took its crate, and carried it himself. Seniority.',
    },
  },
  {
    id: 'wld-unsinkablesam',
    slot: 'wildcard',
    name: 'Unsinkable Sam',
    origin: 'The Sea (allegiance flexible)',
    year: 1941,
    blurb: 'The ship’s cat who survived three sinkings on both sides of the war, then retired ashore, done.',
    stats: s(1, 10, 6, 2, 1, 9, 7),
    terrain: { naval: 3 },
    authenticity: 'legendary',
    special: { trigger: 'naval', bonus: 1.3, label: 'The ship may sink. He won’t.' },
    lines: {
      win: 'The fleet followed the cat’s calm precisely as far as it went, which was, as always, safely to shore.',
      loss: 'The ship went down. Sam did not. The pattern, third confirmed instance, now constitutes doctrine.',
      ana: 'Sam boarded the modern carrier, selected the warmest radar console, and accepted command.',
    },
  },
  {
    id: 'wld-piper',
    slot: 'wildcard',
    name: 'The Piper of Sword Beach',
    origin: 'Scotland',
    year: 1944,
    blurb: 'Piped the invasion ashore at walking pace. Snipers reportedly held fire out of sheer disbelief.',
    stats: s(1, 4, 5, 2, 1, 10, 3),
    terrain: {},
    authenticity: 'historical',
    special: { trigger: 'amphibious', bonus: 1.4, label: 'The tune does not take cover' },
    lines: {
      win: 'The pipes walked the beach upright through everything, and the landing found its nerve to the tune.',
      loss: 'The beach was lost; the set list was completed; history has ruled these results separately.',
      ana: 'The piper auditioned the loudspeaker drone, found it adequate, and played over it on principle.',
    },
  },
  {
    id: 'wld-habakkuk',
    slot: 'wildcard',
    name: 'Project Habakkuk',
    origin: 'Britain / Canada',
    year: 1943,
    altSlot: 'navy',
    blurb: 'An aircraft carrier made of ice and sawdust. A prototype floated on a Canadian lake for a year. Really.',
    stats: s(3, 9, 1, 3, 9, 4, 2),
    terrain: { naval: 2, winter: 3 },
    authenticity: 'experimental',
    special: { trigger: 'absurd', bonus: 1.4, label: 'Torpedo-proof (also a glacier)' },
    lines: {
      win: 'The enemy torpedoed the ice ship twice, achieved two dents, and requested new physics.',
      loss: 'Spring arrived. The flagship is now a lake. The admiralty has no further questions about the lake.',
      ana: 'The Habakkuk engineers saw the climate models and observed their carrier concept now has a global fleet.',
    },
  },
  // ── COLD WAR (new cell) ──────────────────────────────────────────────────
  {
    id: 'wld-acoustickitty',
    slot: 'wildcard',
    name: 'Acoustic Kitty',
    origin: 'United States',
    year: 1967,
    altSlot: 'intel',
    blurb: 'The CIA’s twenty-million-dollar surveillance cat. Declassified, real, and famously uncooperative.',
    stats: s(1, 4, 7, 1, 9, 2, 8),
    terrain: { urban: 2, night: 1 },
    authenticity: 'experimental',
    special: { trigger: 'intel', bonus: 1.3, label: 'Nobody suspects the cat' },
    lines: {
      win: 'The cat crossed the park, sat beneath the bench, and recorded everything, mostly on purpose.',
      loss: 'The asset was deployed, saw a pigeon, and defected to the pigeon.',
      ana: 'Acoustic Kitty regarded the surveillance drone with contempt: all that budget, and it still can’t be petted.',
    },
  },
  {
    id: 'wld-atomicannie',
    slot: 'wildcard',
    name: 'Atomic Annie',
    origin: 'United States',
    year: 1953,
    altSlot: 'armor',
    blurb: 'A cannon that fires nuclear shells. Fired one, once, in Nevada. Everyone agreed that was plenty.',
    stats: s(10, 4, 3, 3, 9, 5, 2),
    terrain: { open: 1 },
    authenticity: 'experimental',
    special: { trigger: 'absurd', bonus: 1.3, label: 'One warning shot (total, ever)' },
    lines: {
      win: 'Annie was towed to the front, the front read the placard, and the front relocated by consensus.',
      loss: 'Annie was not fired, could not be fired, and must never be fired; the enemy won on a technicality of sanity.',
      ana: 'Annie met the trebuchet and they discussed, at length, careers built entirely on the one big throw.',
    },
  },
  {
    id: 'wld-campcentury',
    slot: 'wildcard',
    name: 'Camp Century',
    origin: 'United States / Greenland',
    year: 1960,
    blurb: 'A nuclear-powered city under the ice sheet, defeated in the end by its landlord: the ice.',
    stats: s(2, 8, 2, 6, 10, 5, 6),
    terrain: { winter: 3 },
    authenticity: 'experimental',
    special: { trigger: 'winter', bonus: 1.3, label: 'The base is beneath the weather' },
    lines: {
      win: 'The enemy searched the ice cap for weeks; the city hummed along beneath them, borrowing their footsteps.',
      loss: 'The ice, patient as ever, closed the tunnels a centimeter a day until the city agreed to have never existed.',
      ana: 'The Camp Century engineers reviewed the lunar base plans and said, “same job, drier snow.”',
    },
  },
  {
    id: 'wld-hotline',
    slot: 'wildcard',
    name: 'The Moscow–Washington Hotline',
    origin: 'United States / Soviet Union',
    year: 1963,
    altSlot: 'intel',
    blurb: 'The red phone is a teletype, there is no phone, and it may be history’s highest-scoring weapon.',
    stats: s(1, 9, 3, 4, 8, 5, 9),
    terrain: {},
    bridge: 1,
    authenticity: 'historical',
    special: { trigger: 'coalition', bonus: 1.3, label: 'Talk first, annihilate never' },
    lines: {
      win: 'The message crossed in minutes, the misunderstanding died in committee, and the world absent-mindedly survived.',
      loss: 'The line worked perfectly; the first draft of the message did not; diplomacy has requested an editor.',
      ana: 'The Hotline operators reviewed the leaders’ social media accounts and quietly unplugged the router to be safe.',
    },
  },
]
