/**
 * Phase 1b depth pass: one card for every cell still sitting at the 4-pick
 * minimum, flooring the whole 58-cell grid at 5 choices per menu.
 *
 * Stats follow RATINGS.md (era-relative; every 8+/≤3 citable). Attested
 * absurdities rated as what they literally were. Content policy per roster.ts.
 */
import type { Pick, Stats } from './types'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const DEPTH_1B: Pick[] = [
  // ── COMMANDERS ───────────────────────────────────────────────────────────
  {
    id: 'cmd-ieyasu',
    slot: 'commander',
    name: 'Tokugawa Ieyasu',
    origin: 'Sengoku Japan',
    year: 1600,
    blurb: 'Won Japan by outliving everyone interesting. Patience is a siege weapon.',
    conflict: 'Sengoku Period',
    descriptor:
      'The victor of Sekigahara, who founded the shogunate that ruled Japan for 250 years.',
    stats: s(7, 8, 5, 8, 7, 8, 9),
    terrain: { open: 1 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'defense', bonus: 1.2, label: 'Wait for the cuckoo to sing' },
    lines: {
      win: 'Ieyasu waited, and waited, and the enemy coalition helpfully dissolved into his victory speech.',
      loss: 'Ieyasu lost today, noted it in the ledger, and scheduled the rematch for a decade he owns.',
      ana: 'Ieyasu reviewed the twenty-year procurement plan and asked why it was in such a hurry.',
    },
  },
  {
    id: 'cmd-nelson',
    slot: 'commander',
    name: 'Horatio Nelson',
    origin: 'Britain',
    year: 1805,
    blurb: 'Breaks the line, breaks the rules, expects every man to do his duty. Signals it, too.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'The British admiral whose bold tactics destroyed the Franco-Spanish fleet at Trafalgar.',
    stats: s(10, 5, 8, 6, 7, 9, 8),
    terrain: { naval: 3 },
    leadership: 10,
    adaptability: 9,
    special: { trigger: 'naval', bonus: 1.3, label: 'Cross their line at two points' },
    lines: {
      win: 'Nelson sailed straight through the enemy line, which the enemy line had been assured was not allowed.',
      loss: 'Nelson turned his blind eye to the recall signal, which works slightly less well on defeats.',
      ana: 'Nelson read the carrier group’s signal book and issued one correction: more audacity, fewer acronyms.',
    },
  },
  {
    id: 'cmd-menelik',
    slot: 'commander',
    name: 'Menelik II',
    origin: 'Ethiopia',
    year: 1896,
    blurb: 'Bought the rifles, read the treaty’s fine print, and handed Europe its clearest defeat in Africa.',
    conflict: 'First Italo-Ethiopian War',
    descriptor:
      'The emperor who crushed an invading Italian army at Adwa, keeping Ethiopia independent.',
    stats: s(8, 7, 6, 8, 7, 9, 9),
    terrain: { mountain: 2 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'defense', bonus: 1.2, label: 'Adwa: the homeland argues back' },
    lines: {
      win: 'Menelik assembled a hundred thousand rifles the enemy’s briefing said could not exist, at Adwa, on time.',
      loss: 'Menelik withdrew to the highlands with the army intact and the enemy’s maps still wrong.',
      ana: 'Menelik reviewed the arms catalog, compared three vendors, and negotiated a bulk discount on the future.',
    },
  },
  {
    id: 'cmd-foch',
    slot: 'commander',
    name: 'Ferdinand Foch',
    origin: 'France',
    year: 1918,
    blurb: '“My center is giving way, my right retreats. Situation excellent. I attack.”',
    conflict: 'World War I',
    descriptor:
      'The Allied supreme commander who coordinated the offensives that ended the First World War.',
    stats: s(9, 6, 6, 7, 6, 10, 6),
    terrain: { open: 1 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'coalition', bonus: 1.3, label: 'One marshal, five armies' },
    lines: {
      win: 'Foch attacked from a position his own staff had classified as “surrounded,” and the classification surrendered.',
      loss: 'Foch has reviewed the defeat and identified the error: insufficient attacking. The memo is one word.',
      ana: 'Foch read the missile-defense doctrine, crossed out “defense,” and returned it improved.',
    },
  },
  {
    id: 'cmd-rickover',
    slot: 'commander',
    name: 'Hyman Rickover',
    origin: 'United States',
    year: 1958,
    blurb: 'Father of the nuclear navy. His job interviews are classified as psychological operations.',
    conflict: 'Cold War',
    descriptor:
      'The relentless admiral who drove the creation of the nuclear-powered navy.',
    stats: s(6, 8, 5, 9, 10, 8, 8),
    terrain: { naval: 2 },
    leadership: 8,
    adaptability: 6,
    special: { trigger: 'naval', bonus: 1.2, label: 'Zero reactor accidents, zero excuses' },
    lines: {
      win: 'Rickover’s fleet ran flawlessly, as designed, inspected, re-inspected, and interrogated into excellence.',
      loss: 'The defeat has been traced to a component Rickover did not personally interview. It will be.',
      ana: 'Rickover questioned the trireme’s rowing master for six hours and offered him a commission.',
    },
  },
  // ── GROUND ───────────────────────────────────────────────────────────────
  {
    id: 'grd-llaneros',
    slot: 'ground',
    name: 'Bolívar’s Llaneros',
    origin: 'Venezuela / Colombia',
    year: 1819,
    blurb: 'Plains horsemen who crossed flooded llanos and frozen Andes in one campaign, mostly barefoot.',
    conflict: 'South American Wars of Independence',
    descriptor:
      'The plains horsemen whose lancers helped Bolívar free northern South America from Spain.',
    stats: s(8, 4, 9, 4, 3, 9, 6),
    terrain: { open: 2, mountain: 1 },
    special: { trigger: 'expedition', bonus: 1.3, label: 'The impossible route is the plan' },
    lines: {
      win: 'The Llaneros arrived out of the Andes behind the enemy, who had filed that direction under “weather.”',
      loss: 'The Llaneros rode home across two climates and have already volunteered for the next impossibility.',
      ana: 'The Llaneros looked at the all-terrain vehicle, then at their horses, and politely declined the downgrade.',
    },
  },
  {
    id: 'grd-ironbrigade',
    slot: 'ground',
    name: 'The Iron Brigade',
    origin: 'United States',
    year: 1863,
    blurb: 'The black hats. Held the first morning at Gettysburg at a cost that made the nickname literal.',
    conflict: 'American Civil War',
    descriptor:
      'A hard-fighting Union brigade in black hats, known for holding its ground at terrible cost.',
    stats: s(8, 8, 6, 6, 6, 10, 5),
    terrain: { open: 1 },
    special: { trigger: 'defense', bonus: 1.2, label: 'The first day holds' },
    lines: {
      win: 'The Iron Brigade held the ridge long enough for the whole army to arrive, which was the entire war.',
      loss: 'The brigade traded ground for hours at full price, and history has ruled the exchange a bargain.',
      ana: 'The black hats inspected the body armor and asked only whether it came in wool.',
    },
  },
  {
    id: 'grd-chosin',
    slot: 'ground',
    name: 'The Chosin Few',
    origin: 'United States',
    year: 1950,
    blurb: 'Surrounded ten-to-one at thirty below. “Attacking in a different direction,” and they meant it.',
    conflict: 'Korean War',
    descriptor:
      'The US Marines who fought their way out of encirclement in the frozen Chosin Reservoir.',
    stats: s(8, 9, 6, 6, 6, 10, 5),
    terrain: { winter: 3, mountain: 2 },
    special: { trigger: 'winter', bonus: 1.3, label: 'The cold is also surrounded' },
    lines: {
      win: 'The division attacked in a different direction, and the encirclement discovered it had been holding a tiger.',
      loss: 'The column fought out with its wounded, its equipment, and its opinion of the staff who sent it there.',
      ana: 'The Chosin veterans read the Teutonic Knights’ ice report and issued a rare professional nod.',
    },
  },
  // ── ARMOR ────────────────────────────────────────────────────────────────
  {
    id: 'arm-petards',
    slot: 'armor',
    name: 'The Petard Corps',
    origin: 'France',
    year: 1620,
    blurb: 'Door-removal specialists. The phrase “hoist with his own petard” is their safety record.',
    conflict: 'Thirty Years’ War',
    descriptor:
      'Engineers who blew in fortress gates with a bell-shaped bomb — at deadly close range.',
    stats: s(7, 3, 5, 4, 6, 8, 4),
    terrain: { urban: 2 },
    special: { trigger: 'siege', bonus: 1.2, label: 'The gate is a suggestion' },
    lines: {
      win: 'The petardiers jogged to the gate, hung the charge, and the fortress acquired a second, better entrance.',
      loss: 'The petard went off early, which the corps insists is a scheduling issue rather than a physics one.',
      ana: 'The petardiers examined the breaching charge and wept: a petard that waits for you to leave.',
    },
  },
  {
    id: 'arm-carronades',
    slot: 'armor',
    name: 'Carronade Batteries',
    origin: 'Scotland',
    year: 1782,
    blurb: 'The Smasher: devastating within pistol range, decorative beyond it.',
    conflict: 'Age of Sail',
    descriptor:
      'Short, heavy naval guns — ‘smashers’ — that were devastating at close range.',
    stats: s(9, 5, 6, 5, 6, 7, 3),
    terrain: { naval: 2 },
    special: { trigger: 'naval', bonus: 1.2, label: 'Get close. Closer.' },
    lines: {
      win: 'The carronades held fire to pistol range, then removed the enemy’s broadside as a concept.',
      loss: 'The enemy stayed at long range and read a book, which the carronades could neither reach nor refute.',
      ana: 'The carronade crews measured the missile’s hundred-mile range and asked, sincerely, where the fun is.',
    },
  },
  // ── AIR ──────────────────────────────────────────────────────────────────
  {
    id: 'air-troybeacons',
    slot: 'air',
    name: 'The Beacon Relay of Agamemnon',
    origin: 'Mycenaean Greece',
    year: -1184,
    blurb: 'Troy fell at midnight; Argos knew by dawn. Eight mountaintop fires, one very good night.',
    conflict: 'Trojan War',
    descriptor:
      'The chain of signal fires said to have flashed news of Troy’s fall across the Aegean.',
    stats: s(1, 4, 9, 3, 5, 5, 8),
    terrain: { mountain: 2, night: 2 },
    authenticity: 'legendary',
    special: { trigger: 'intel', bonus: 1.2, label: 'News travels at firelight' },
    lines: {
      win: 'The beacons leapt peak to peak across the sea, and the queen knew before the ships had left the bay.',
      loss: 'A shepherd’s bonfire entered the relay, and the capital celebrated a victory scheduled for next year.',
      ana: 'The beacon keepers saw the push notification and asked what mountain it was lit on.',
    },
  },
  // ── NAVY ─────────────────────────────────────────────────────────────────
  {
    id: 'nav-rhodians',
    slot: 'navy',
    name: 'The Rhodian Navy',
    origin: 'Rhodes',
    year: -305,
    blurb: 'The professional coast guard of antiquity. Pirates filed formal complaints.',
    conflict: 'Hellenistic Era',
    descriptor:
      'The island navy whose seamanship policed piracy and defied besieging fleets.',
    stats: s(7, 7, 8, 7, 7, 7, 7),
    terrain: { naval: 3 },
    special: { trigger: 'blockade', bonus: 1.2, label: 'Sea lanes, patrolled and invoiced' },
    lines: {
      win: 'The Rhodians swept the sea lanes on schedule, and piracy relocated to a different century.',
      loss: 'Rhodes lost the battle but kept the maritime code, which is currently suing the winners.',
      ana: 'The Rhodian captains read the modern law of the sea and found their own clauses, uncredited.',
    },
  },
  {
    id: 'nav-hansa',
    slot: 'navy',
    name: 'The Hanseatic League',
    origin: 'The Baltic',
    year: 1370,
    blurb: 'A merchants’ guild with a navy. Declares war by invoice, wins by embargo.',
    conflict: 'Medieval Baltic',
    descriptor:
      'The merchant league whose fleets and trade monopolies dominated the northern seas.',
    stats: s(6, 7, 6, 9, 6, 6, 7),
    terrain: { naval: 2 },
    special: { trigger: 'blockade', bonus: 1.3, label: 'Terms and conditions apply' },
    lines: {
      win: 'The League blockaded the sound, adjusted three tariffs, and the enemy kingdom settled out of court.',
      loss: 'The League lost the battle and responded with a trade embargo the winners are still paying off.',
      ana: 'The Hansa reviewed the shipping-container manifest with tears in their eyes: standardization, at last.',
    },
  },
  {
    id: 'nav-barbarossa',
    slot: 'navy',
    name: 'Barbarossa’s Corsair Fleet',
    origin: 'Ottoman Empire',
    year: 1538,
    blurb: 'The red-bearded admiral who made the Mediterranean an Ottoman lake with borrowed ships.',
    conflict: 'Ottoman Wars',
    descriptor:
      'The corsair admiral whose fleet won Ottoman mastery of the Mediterranean at Preveza.',
    stats: s(8, 6, 9, 6, 6, 8, 8),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.2, label: 'The lake has an owner' },
    lines: {
      win: 'Barbarossa refused the pitched battle until the wind agreed with him, and then it was not a battle.',
      loss: 'Barbarossa slipped away with the fleet intact, which the enemy has been instructed to call a victory.',
      ana: 'Barbarossa studied the frigate’s radar and grinned: so it CAN see me leave.',
    },
  },
  {
    id: 'nav-blackships',
    slot: 'navy',
    name: 'Perry’s Black Ships',
    origin: 'United States',
    year: 1853,
    blurb: 'Four coal-smoking warships, zero shots fired, one country opened. Gunboat diplomacy’s showroom.',
    conflict: 'Bakumatsu Japan',
    descriptor:
      'The US steam warships whose arrival forced isolated Japan to open to the world.',
    stats: s(7, 6, 6, 7, 9, 6, 5),
    terrain: { naval: 2 },
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The smoke is the message' },
    lines: {
      win: 'The Black Ships anchored in the bay, smoked meaningfully, and the negotiation concluded before it began.',
      loss: 'The squadron’s aura was insufficient this time; the follow-up fleet will be larger and smokier.',
      ana: 'Perry’s stokers examined the nuclear carrier and asked how it smokes. It doesn’t. Then how do they KNOW?',
    },
  },
  {
    id: 'nav-zeebrugge',
    slot: 'navy',
    name: 'The Zeebrugge Raiders',
    origin: 'Britain',
    year: 1918,
    blurb: 'Rammed concrete-filled cruisers into an enemy canal, on purpose, on St. George’s Day.',
    conflict: 'World War I',
    descriptor:
      'The daring raid that tried to bottle up a German U-boat base by sinking ships in the harbor mouth.',
    stats: s(7, 5, 6, 4, 6, 10, 6),
    terrain: { naval: 2, night: 2 },
    special: { trigger: 'blockade', bonus: 1.3, label: 'The cork goes in the bottle' },
    lines: {
      win: 'The blockships settled into the channel mouth precisely, and the U-boat base became a marina.',
      loss: 'The canal reopened in days, but the raid’s nerve has been permanently lodged in the enemy’s planning.',
      ana: 'The raiders reviewed the harbor drone swarm and asked if any of the drones were filled with concrete.',
    },
  },
  {
    id: 'nav-iowas',
    slot: 'navy',
    name: 'The Iowa Recommission',
    origin: 'United States',
    year: 1984,
    blurb: 'Battleships recalled from museum duty with missiles bolted on. The shells predate the crews.',
    conflict: 'Cold War',
    descriptor:
      'The WWII battleships brought back into service with missiles for the Cold War fleet.',
    stats: s(9, 9, 5, 6, 7, 8, 4),
    terrain: { naval: 2 },
    special: { trigger: 'propaganda', bonus: 1.2, label: 'Grandpa is BACK' },
    lines: {
      win: 'The sixteen-inch guns spoke for the first time in a generation, and the shoreline conceded on principle.',
      loss: 'The battleship performed magnificently at a job the century had quietly stopped scheduling.',
      ana: 'The Iowa’s gun crews met the trireme rowers at the veterans’ reunion and split the bar tab by tonnage.',
    },
  },
  // ── INTELLIGENCE ─────────────────────────────────────────────────────────
  {
    id: 'int-frumentarii',
    slot: 'intel',
    name: 'The Frumentarii',
    origin: 'Rome',
    year: 200,
    blurb: 'Grain officers who audited the wheat, the roads, and, incidentally, everyone.',
    conflict: 'Roman Empire',
    descriptor:
      'Imperial couriers who doubled as Rome’s secret police and informers.',
    stats: s(3, 6, 7, 8, 5, 5, 9),
    terrain: { urban: 2 },
    special: { trigger: 'supply', bonus: 1.2, label: 'The ledger sees all' },
    lines: {
      win: 'The Frumentarii found the plot in the grain accounts three provinces early, filed under “inventory.”',
      loss: 'The conspiracy used cash, which the wheat ledgers, to their lasting shame, do not track.',
      ana: 'The Frumentarii reviewed the supply-chain analytics dashboard and asked who audits the auditors. They do.',
    },
  },
  {
    id: 'int-domesday',
    slot: 'intel',
    name: 'The Domesday Surveyors',
    origin: 'Norman England',
    year: 1086,
    blurb: 'Counted every pig, plough, and pond in a kingdom. Nothing has escaped a census since.',
    conflict: 'Norman Conquest',
    descriptor:
      'The great survey that catalogued England’s land and wealth for its new Norman rulers.',
    stats: s(1, 6, 5, 8, 5, 6, 9),
    terrain: {},
    special: { trigger: 'logistics', bonus: 1.2, label: 'Everything is inventory' },
    lines: {
      win: 'The surveyors knew the enemy’s carrying capacity to the pig, and the campaign was planned against the book.',
      loss: 'The invasion outran the survey, entering lands whose pigs remain, alarmingly, uncounted.',
      ana: 'The Domesday clerks opened the census database and sniffed: no field for beehives. Amateurs.',
    },
  },
  {
    id: 'int-cabinetnoir',
    slot: 'intel',
    name: 'The Cabinet Noir',
    origin: 'France',
    year: 1635,
    blurb: 'Richelieu’s mail room. Every letter arrives sealed, informative, and slightly late.',
    conflict: 'Grand Siècle',
    descriptor:
      'The French ‘black chamber’ that secretly opened, read, and resealed the mail.',
    stats: s(2, 7, 4, 6, 7, 5, 10),
    terrain: { urban: 1 },
    special: { trigger: 'intel', bonus: 1.3, label: 'Steamed, read, resealed, delivered' },
    lines: {
      win: 'The Cardinal read the enemy alliance’s letters a week before the allies did, and priced his war accordingly.',
      loss: 'The enemy switched couriers; the Cabinet is opening everyone’s mail until morale improves.',
      ana: 'The Cabinet Noir examined end-to-end encryption and lit a candle for the death of the steam kettle.',
    },
  },
  {
    id: 'int-alienoffice',
    slot: 'intel',
    name: 'The Alien Office',
    origin: 'Britain',
    year: 1798,
    blurb: 'The world’s first modern secret service, run from a back room with tea and total recall.',
    conflict: 'French Revolutionary Wars',
    descriptor:
      'Britain’s early secret service, set up to watch foreign agents and revolutionaries.',
    stats: s(2, 8, 5, 6, 6, 6, 10),
    terrain: { urban: 1 },
    special: { trigger: 'intel', bonus: 1.3, label: 'Every visitor is a file' },
    lines: {
      win: 'The invasion’s advance agents were greeted at the dock by name, offered tea, and turned by dessert.',
      loss: 'The plot succeeded abroad, where the filing system regrettably does not yet extend.',
      ana: 'The Alien Office reviewed the biometric border scanner and asked whether it also notices a nervous hat.',
    },
  },
  // ── LOGISTICS ────────────────────────────────────────────────────────────
  {
    id: 'log-xerxes',
    slot: 'logistics',
    name: 'Xerxes’ Royal Engineers',
    origin: 'Achaemenid Persia',
    year: -480,
    blurb: 'Bridged the Hellespont on boats, dug a canal through a peninsula, and flogged the sea as HR policy.',
    conflict: 'Greco-Persian Wars',
    descriptor:
      'The engineers who bridged the Hellespont with boats and cut a canal to move Xerxes’ vast army.',
    stats: s(2, 6, 5, 9, 7, 6, 4),
    terrain: { naval: 1 },
    special: { trigger: 'expedition', bonus: 1.3, label: 'The strait is now a road' },
    lines: {
      win: 'The army crossed the sea on a bridge of ships, dry-shod, while the engineers pretended not to hear the waves.',
      loss: 'The storm took the first bridge, the sea received three hundred lashes, and the schedule slipped a legend.',
      ana: 'The royal engineers studied the floating pier system and asked, professionally, how it handles discipline.',
    },
  },
  {
    id: 'log-manilagalleon',
    slot: 'logistics',
    name: 'The Manila Galleon Run',
    origin: 'Spain / The Philippines',
    year: 1600,
    blurb: 'One ship a year, six months at sea, half the world’s silver aboard. The original supply chain.',
    conflict: 'Age of Sail',
    descriptor:
      'The trans-Pacific treasure ships that linked Asia and the Americas for 250 years.',
    stats: s(3, 6, 5, 9, 7, 6, 4),
    terrain: { naval: 2 },
    special: { trigger: 'supply', bonus: 1.2, label: 'The annual ship arrives' },
    lines: {
      win: 'The galleon made port on schedule, and two empires’ economies exhaled at once.',
      loss: 'The galleon is late, and both hemispheres are refreshing the horizon.',
      ana: 'The galleon’s pilots studied the container ship’s six-month schedule and said, warmly, “ours too.”',
    },
  },
  {
    id: 'log-corpsdiscovery',
    slot: 'logistics',
    name: 'The Corps of Discovery',
    origin: 'United States',
    year: 1804,
    blurb: 'Crossed an uncharted continent and back, losing one man and gaining one very large map.',
    conflict: 'American Frontier',
    descriptor:
      'The Lewis and Clark expedition that mapped a route across the continent to the Pacific.',
    stats: s(3, 5, 7, 8, 5, 9, 8),
    terrain: { mountain: 2 },
    special: { trigger: 'expedition', bonus: 1.3, label: 'The map draws itself' },
    lines: {
      win: 'The Corps arrived at the far ocean with the journals full and the expedition, impossibly, still on budget.',
      loss: 'The route proved impassable; the Corps has renamed it, mapped it, and recommended a better one.',
      ana: 'The Corps opened the satellite map, traced their route with a finger, and quietly closed the laptop.',
    },
  },
  {
    id: 'log-transsib',
    slot: 'logistics',
    name: 'The Trans-Siberian Railway',
    origin: 'Russia',
    year: 1904,
    blurb: 'The longest supply line ever built. The war at the far end of it was not consulted.',
    conflict: 'Russo-Japanese War',
    descriptor:
      'The railway that hauled Russian armies clear across Siberia to the Pacific front.',
    stats: s(2, 6, 7, 9, 7, 6, 3),
    terrain: { winter: 2, steppe: 2 },
    special: { trigger: 'supply', bonus: 1.2, label: 'Five thousand miles of track' },
    lines: {
      win: 'The trains ran five thousand miles through winter and delivered an army to the edge of the map, intact.',
      loss: 'The single track jammed at Lake Baikal, and the war waited at the far end like an unpaid bill.',
      ana: 'The railway engineers examined the strategic airlift and conceded the sky has fewer icicles.',
    },
  },
  {
    id: 'log-landarmy',
    slot: 'logistics',
    name: 'The Women’s Land Army',
    origin: 'Britain',
    year: 1917,
    blurb: 'Took over the farms of a starving island and out-harvested the U-boat blockade.',
    conflict: 'World War I',
    descriptor:
      'The women who took over Britain’s farms to keep the nation fed through the war.',
    stats: s(1, 8, 4, 10, 5, 9, 4),
    terrain: {},
    special: { trigger: 'blockade', bonus: 1.3, label: 'The harvest breaks the siege' },
    lines: {
      win: 'The harvest came in over quota, and the blockade discovered it had been starving no one.',
      loss: 'The front lost ground; the farms did not; the ration books have never once missed a week.',
      ana: 'The Land Army inspected the autonomous tractor and assigned it to the field nobody likes.',
    },
  },
  {
    id: 'log-deepfreeze',
    slot: 'logistics',
    name: 'Operation Deep Freeze',
    origin: 'United States',
    year: 1955,
    blurb: 'Annual resupply of a continent that produces nothing, on purpose, in the dark, at sixty below.',
    conflict: 'Cold War',
    descriptor:
      'The US operation that built and supplied research bases across Antarctica.',
    stats: s(1, 7, 6, 9, 8, 7, 4),
    terrain: { winter: 3 },
    special: { trigger: 'winter', bonus: 1.3, label: 'Winter is the route, not the obstacle' },
    lines: {
      win: 'The convoy reached the ice shelf in polar night, unloaded a year of civilization, and left before the sea closed.',
      loss: 'The ice won this season, as the ice occasionally must, and the winter-over crew has extended its book club.',
      ana: 'The Deep Freeze planners read Hannibal’s Alpine logistics and mailed him a sympathy card across time.',
    },
  },
  // ── WILD CARD ────────────────────────────────────────────────────────────
  {
    id: 'wld-herrings',
    slot: 'wildcard',
    name: 'The Battle of the Herrings',
    origin: 'France (the fish were neutral)',
    year: 1429,
    blurb: 'An actual battle fought over a convoy of Lenten fish. The barrel fort held. The fish were avenged.',
    conflict: 'Hundred Years’ War',
    descriptor:
      'The odd skirmish fought over a supply convoy of salted fish during the siege of Orléans.',
    stats: s(4, 7, 3, 6, 3, 6, 3),
    terrain: { open: 1 },
    authenticity: 'historical',
    special: { trigger: 'supply', bonus: 1.3, label: 'Circle the fish wagons' },
    lines: {
      win: 'The convoy formed a fort of herring barrels, repelled an army, and delivered the fish on schedule.',
      loss: 'The barrels broke, the herrings scattered, and Lent has entered a state of emergency.',
      ana: 'The convoy masters inspected the refrigerated truck and declared the herring finally safe from history.',
    },
  },
  {
    id: 'wld-wiperstimes',
    slot: 'wildcard',
    name: 'The Wipers Times',
    origin: 'The Ypres Salient',
    year: 1916,
    blurb: 'A satirical newspaper printed in a shelled cellar by serving soldiers. The jokes held the line.',
    conflict: 'World War I',
    descriptor:
      'The satirical trench newspaper written by British soldiers under shellfire.',
    stats: s(1, 6, 3, 4, 3, 10, 7),
    terrain: {},
    authenticity: 'historical',
    special: { trigger: 'propaganda', bonus: 1.4, label: 'Morale by deadline' },
    lines: {
      win: 'The paper went to press under bombardment, and the trench laughed loudest the night before the push.',
      loss: 'The position fell; the editorial about it is already typeset and unprintably funny.',
      ana: 'The Wipers editors reviewed the military meme page and extended, at last, professional recognition.',
    },
  },
  {
    id: 'wld-panjandrum',
    slot: 'wildcard',
    name: 'The Great Panjandrum',
    origin: 'Britain',
    year: 1943,
    altSlot: 'armor',
    blurb: 'A rocket-propelled explosive cartwheel that chased its own test audience down the beach. Cancelled. Beloved.',
    conflict: 'World War II',
    descriptor:
      'A giant rocket-driven explosive wheel that careened wildly out of control in testing.',
    stats: s(6, 2, 7, 2, 4, 3, 1),
    terrain: {},
    authenticity: 'experimental',
    special: { trigger: 'absurd', bonus: 1.4, label: 'Direction is a suggestion' },
    lines: {
      win: 'The Panjandrum rolled at the enemy, changed its mind twice, and arrived anyway, to universal astonishment.',
      loss: 'The Panjandrum executed a flawless U-turn, and the beach cleared with remarkable interservice cooperation.',
      ana: 'The Panjandrum met the guided missile and asked, spinning gently, what “guided” is like.',
    },
  },
  {
    id: 'wld-paulbunyan',
    slot: 'wildcard',
    name: 'Operation Paul Bunyan',
    origin: 'United States / South Korea',
    year: 1976,
    blurb: 'One tree removed by task force: engineers, an infantry escort, artillery on call, and air cover. The tree lost.',
    conflict: 'Korean DMZ Conflict',
    descriptor:
      'The overwhelming show of force mounted just to cut down one tree in the DMZ.',
    stats: s(3, 7, 4, 8, 7, 6, 6),
    terrain: {},
    authenticity: 'historical',
    special: { trigger: 'propaganda', bonus: 1.3, label: 'Overwhelming gardening' },
    lines: {
      win: 'The tree came down in forty-two minutes under more air cover than most invasions, and the message landed.',
      loss: 'The tree is down; the meeting about the tree continues; the stump has been promoted to a landmark.',
      ana: 'The task force reviewed the robot lawnmower and asked where its fighter escort was.',
    },
  },
  {
    id: 'wld-evergiven',
    slot: 'wildcard',
    name: 'The Ever Given',
    origin: 'The Suez Canal (temporarily)',
    year: 2021,
    altSlot: 'logistics',
    blurb: 'Parked sideways in the Suez Canal and paused the global economy. One ship. Six days. Everyone watched.',
    conflict: 'The 2020s',
    descriptor:
      'The container ship that wedged sideways and blocked the Suez Canal, snarling global trade.',
    stats: s(1, 9, 1, 2, 7, 3, 2),
    terrain: { naval: 2 },
    authenticity: 'historical',
    special: { trigger: 'blockade', bonus: 1.4, label: 'Parks in the canal' },
    lines: {
      win: 'The ship settled gently across the channel, and the world’s supply chains formed an orderly, screaming queue.',
      loss: 'The tugs and the tide finally won, and global commerce resumed, visibly shaken by one boat.',
      ana: 'The Ever Given’s pilots studied ancient blockade doctrine and noted they achieved it by accident, larger.',
    },
  },
]
