/**
 * The draft pool. Every entry is playable, rated, and written to be quoted.
 *
 * Content policy: mythologized, long-past, or celebratory picks only. No 20th-century
 * genocidal figures, no extremist organizations, no active conflicts, no atrocity content.
 * This is a parody of fantasy sports, not a history exam.
 *
 * Stat rubric: RATINGS.md is the source of truth — read it before adding or
 * re-rating any card. Every stat is 1–10 RELATIVE TO THE UNIT'S OWN ERA (5 =
 * era-standard, 8+ = attested era-best, 1–3 = famous documented weakness).
 * Numbers must survive a history nerd's audit; the blurbs carry the jokes.
 * Stats are scoring inputs: any change here or to engine scoring re-runs
 * scripts/balance.ts and updates RATINGS.md together (see its Change control).
 */
import type { Pick, Stats } from './types'
import { EXPANSION } from './roster2'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const COMMANDERS: Pick[] = [
  {
    id: 'cmd-genghis',
    slot: 'commander',
    name: 'Genghis Khan',
    origin: 'Mongol Empire',
    year: 1206,
    blurb: 'Has personally conquered more land than the rest of your draft class combined.',
    stats: s(9, 6, 10, 8, 5, 9, 9),
    terrain: { steppe: 3, open: 2, naval: -2 },
    leadership: 10,
    adaptability: 9,
    special: { trigger: 'steppe', bonus: 1.2, label: 'Home turf: the entire steppe' },
    lines: {
      win: 'Genghis accepted the enemy’s surrender before their declaration of war cleared processing.',
      loss: 'Genghis demanded the ocean be annexed to the steppe. The ocean declined.',
      ana: 'Genghis kept calling the jets “sky horses,” and by week three the pilots had it stitched on their jackets.',
    },
  },
  {
    id: 'cmd-napoleon',
    slot: 'commander',
    name: 'Napoleon Bonaparte',
    origin: 'France',
    year: 1805,
    blurb: 'Undefeated anywhere reachable by road. Do not ask about the winter thing.',
    stats: s(9, 6, 8, 5, 7, 8, 7),
    terrain: { open: 2, winter: -3 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'open', bonus: 1.0, label: 'Grande Armée doctrine' },
    lines: {
      win: 'Napoleon won the battle, crowned himself Employee of the Month, and painted it.',
      loss: 'Napoleon filed the retreat as a “strategic redeployment.” Backwards. In December.',
      ana: 'Napoleon spent the entire briefing renaming the aircraft carriers after himself.',
    },
  },
  {
    id: 'cmd-alexander',
    slot: 'commander',
    name: 'Alexander the Great',
    origin: 'Macedon',
    year: -331,
    blurb: 'Retired undefeated at 32, still visibly upset there wasn’t more map.',
    stats: s(10, 4, 9, 5, 6, 9, 7),
    terrain: { open: 2, desert: 1, mountain: 1 },
    leadership: 10,
    adaptability: 8,
    lines: {
      win: 'Alexander won, then immediately asked the cartographers if they were hiding continents from him.',
      loss: 'Alexander wept — this time because there WAS a world left to conquer and it said no.',
      ana: 'Alexander tried to name three carrier strike groups “Alexandria” and had to be physically stopped.',
    },
  },
  {
    id: 'cmd-suntzu',
    slot: 'commander',
    name: 'Sun Tzu',
    origin: 'State of Wu',
    year: -506,
    blurb: 'Wrote the book on this. Literally brings it to meetings.',
    stats: s(6, 8, 7, 7, 4, 7, 10),
    terrain: { night: 2 },
    leadership: 8,
    adaptability: 10,
    special: { trigger: 'night', bonus: 1.0, label: 'All warfare is deception' },
    lines: {
      win: 'Sun Tzu won this war six months before it started and simply let the calendar catch up.',
      loss: 'Sun Tzu called the defeat “a teachable moment” and added a chapter.',
      ana: 'Sun Tzu skimmed the satellite feed and muttered that he had predicted this in chapter one.',
    },
  },
  {
    id: 'cmd-joan',
    slot: 'commander',
    name: 'Joan of Arc',
    origin: 'France',
    year: 1429,
    blurb: 'Nineteen years old, zero doubts. The morale bump is not a rounding error.',
    stats: s(8, 7, 7, 5, 4, 10, 5),
    terrain: { urban: 2 },
    leadership: 9,
    adaptability: 6,
    special: { trigger: 'urban', bonus: 1.0, label: 'Lifts any siege, asks nothing' },
    lines: {
      win: 'Joan pointed at the walls, and the walls, sensing how this goes, apologized.',
      loss: 'Joan was fine. The men who ignored her orders have been assigned to latrine history.',
      ana: 'Joan blessed each stealth bomber individually, and nobody had the heart to explain radar.',
    },
  },
  {
    id: 'cmd-hannibal',
    slot: 'commander',
    name: 'Hannibal Barca',
    origin: 'Carthage',
    year: -218,
    blurb: 'Took elephants over the Alps out of spite. Supply plan pending since 218 BCE.',
    stats: s(9, 6, 8, 5, 5, 8, 9),
    terrain: { mountain: 3, winter: 1 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'mountain', bonus: 1.2, label: 'There is always a pass' },
    lines: {
      win: 'Hannibal attacked from the one direction the enemy had labeled “geographically impossible.”',
      loss: 'Hannibal won every battle in this war and still lost the war. Classic Hannibal.',
      ana: 'Hannibal asked whether the transport planes could carry elephants, and would not accept “why” as an answer.',
    },
  },
  {
    id: 'cmd-yi',
    slot: 'commander',
    name: 'Admiral Yi Sun-sin',
    origin: 'Joseon Korea',
    year: 1597,
    blurb: 'Thirteen ships against 133. It was not close. The 133 lost.',
    stats: s(8, 9, 7, 8, 8, 10, 8),
    terrain: { naval: 3 },
    leadership: 10,
    adaptability: 7,
    special: { trigger: 'naval', bonus: 1.3, label: 'The sea obeys' },
    lines: {
      win: 'Admiral Yi counted the enemy fleet, laughed once, and filed the victory paperwork in advance.',
      loss: 'Admiral Yi lost only because the war was, regrettably, on land.',
      ana: 'Admiral Yi inspected the nuclear submarine and asked, very quietly, why it had taken everyone so long.',
    },
  },
  {
    id: 'cmd-patton',
    slot: 'commander',
    name: 'George S. Patton',
    origin: 'United States',
    year: 1944,
    blurb: 'Advances faster than his supply line, his air cover, and occasionally his orders.',
    stats: s(9, 5, 9, 6, 7, 8, 6),
    terrain: { open: 2, desert: 1 },
    leadership: 8,
    adaptability: 6,
    special: { trigger: 'blitz', bonus: 1.2, label: 'Always be advancing' },
    lines: {
      win: 'Patton arrived at the objective forty minutes before the war did.',
      loss: 'Patton has personally slapped the after-action report.',
      ana: 'Patton reviewed the phalanx, pronounced it “acceptable armor,” and requested it be painted faster.',
    },
  },
  {
    id: 'cmd-boudica',
    slot: 'commander',
    name: 'Boudica',
    origin: 'Iceni Britain',
    year: 61,
    blurb: 'Burned Londinium to the ground once. Rome still flinches at red hair.',
    stats: s(9, 3, 7, 2, 3, 10, 4),
    terrain: { open: 2 },
    leadership: 8,
    adaptability: 5,
    special: { trigger: 'grit', bonus: 0, label: '' }, // replaced below — no empty specials
    lines: {
      win: 'Boudica’s pre-battle speech was so effective the enemy briefly considered joining.',
      loss: 'Boudica lost the field but won the grudge, which she is still holding.',
      ana: 'Boudica adopted the attack helicopters as “iron chariots” and demanded they be painted woad blue.',
    },
  },
  {
    id: 'cmd-zhukov',
    slot: 'commander',
    name: 'Georgy Zhukov',
    origin: 'Soviet Union',
    year: 1943,
    blurb: 'Never lost a battle he planned. Plans involve an amount of artillery you’re not ready for.',
    stats: s(8, 9, 6, 8, 6, 9, 7),
    terrain: { winter: 3, urban: 2 },
    leadership: 9,
    adaptability: 6,
    special: { trigger: 'winter', bonus: 1.2, label: 'Winter is a staff officer' },
    lines: {
      win: 'Zhukov’s artillery preparation was audible in three neighboring centuries.',
      loss: 'Zhukov requested more artillery. There was no more artillery. He requested it again.',
      ana: 'Zhukov looked at the trebuchet, nodded slowly, and said “artillery is artillery.”',
    },
  },
]

// Boudica placeholder special cleanup — she gets a real one.
COMMANDERS.find((c) => c.id === 'cmd-boudica')!.special = {
  trigger: 'propaganda',
  bonus: 1.2,
  label: 'The speech. You know the one.',
}

export const GROUND: Pick[] = [
  {
    id: 'grd-spartans',
    slot: 'ground',
    name: 'Spartan Hoplites',
    origin: 'Sparta',
    year: -480,
    blurb: 'Three hundred guys who never stopped talking about it.',
    stats: s(8, 9, 4, 3, 3, 10, 3),
    terrain: { mountain: 2, open: 1, winter: -1 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Excellent at doorways' },
    lines: {
      win: 'The Spartans held the line like it was a group photo.',
      loss: 'The Spartans requested the enemy come back and lose properly in a narrow doorway.',
      ana: 'The Spartans called the tanks “cowards’ shields” and then quietly asked for a ride.',
    },
  },
  {
    id: 'grd-legions',
    slot: 'ground',
    altSlot: 'logistics',
    name: 'Roman Legions',
    origin: 'Roman Republic',
    year: -52,
    blurb: 'They show up, build a wall around your city, then a wall around their wall. Rude. Effective.',
    stats: s(8, 9, 6, 8, 7, 8, 5),
    terrain: { urban: 2, open: 2 },
    special: { trigger: 'urban', bonus: 1.0, label: 'Siegecraft, notarized' },
    lines: {
      win: 'The legions won and immediately built a road to the next war.',
      loss: 'The legions lost, but the fortifications they left behind got excellent reviews.',
      ana: 'The legions unionized briefly upon learning the helicopters would not also be digging trenches.',
    },
  },
  {
    id: 'grd-mongol-horse',
    slot: 'ground',
    name: 'Mongol Horse Archers',
    origin: 'Mongol Empire',
    year: 1220,
    blurb: 'The retreat is fake. It is always fake. They know you know. It still works.',
    stats: s(9, 5, 10, 8, 5, 8, 8),
    terrain: { steppe: 3, open: 2, naval: -3, urban: -2 },
    special: { trigger: 'steppe', bonus: 1.2, label: 'The feigned retreat (patented)' },
    lines: {
      win: 'The horse archers won the battle while technically riding away from it.',
      loss: 'The horse archers were finally caught — by a wall, their one natural predator.',
      ana: 'The horse archers challenged the motorized infantry to a race and, upsettingly, tied.',
    },
  },
  {
    id: 'grd-hussars',
    slot: 'ground',
    name: 'Winged Hussars',
    origin: 'Poland–Lithuania',
    year: 1683,
    blurb: 'Arrive late, wearing literal wings, win instantly. The soundtrack is implied.',
    stats: s(10, 7, 8, 5, 5, 9, 4),
    terrain: { open: 3 },
    special: { trigger: 'defense', bonus: 1.3, label: 'Then the winged hussars arrived' },
    lines: {
      win: 'Then the Winged Hussars arrived, exactly as the song requires.',
      loss: 'The Winged Hussars arrived late, which usually works, but this time the war had also left.',
      ana: 'The Winged Hussars refused night-vision goggles on the grounds that the wings “must be seen.”',
    },
  },
  {
    id: 'grd-janissaries',
    slot: 'ground',
    name: 'Ottoman Janissaries',
    origin: 'Ottoman Empire',
    year: 1520,
    blurb: 'Elite, professional, and unionized enough to overthrow you if payroll slips.',
    stats: s(8, 8, 6, 7, 7, 7, 6),
    terrain: { urban: 2 },
    lines: {
      win: 'The Janissaries performed flawlessly and have submitted an invoice.',
      loss: 'The Janissaries lost, checked their contracts, and found a clause saying they hadn’t.',
      ana: 'The Janissaries adopted the machine gun immediately, which historically is very on-brand.',
    },
  },
  {
    id: 'grd-marines',
    slot: 'ground',
    altSlot: 'navy',
    name: 'US Marines',
    origin: 'United States',
    year: 1945,
    blurb: 'Will take the island. The island does not get a vote.',
    stats: s(9, 8, 7, 8, 7, 10, 6),
    terrain: { naval: 2, jungle: 2 },
    special: { trigger: 'amphibious', bonus: 1.3, label: 'The beach is a doorway' },
    lines: {
      win: 'The Marines took the objective, then took the next one “since we were up.”',
      loss: 'The Marines have declared this loss a tie pending appeal.',
      ana: 'The Marines taught the phalanx to do a fireman’s carry, creating history’s most confusing formation.',
    },
  },
  {
    id: 'grd-vietcong',
    slot: 'ground',
    altSlot: 'intel',
    name: 'Viet Cong',
    origin: 'Vietnam',
    year: 1968,
    blurb: 'You control everything you can see. You can see nothing.',
    stats: s(6, 7, 8, 6, 4, 10, 9),
    terrain: { jungle: 3, night: 3, open: -2 },
    special: { trigger: 'jungle', bonus: 1.4, label: 'The jungle votes last' },
    lines: {
      win: 'The enemy secured every position on the map except the ones that mattered: all of them.',
      loss: 'Open field, high noon, no tree line — someone in scheduling owes the tunnels an apology.',
      ana: 'They dug a tunnel network under the Bronze Age and nobody noticed for a millennium.',
    },
  },
  {
    id: 'grd-swiss',
    slot: 'ground',
    name: 'Swiss Pikemen',
    origin: 'Swiss Confederacy',
    year: 1476,
    blurb: 'The reason Switzerland gets to be “neutral” is that everyone else asked nicely.',
    stats: s(9, 8, 6, 5, 4, 9, 3),
    terrain: { mountain: 3 },
    special: { trigger: 'mountain', bonus: 1.0, label: 'Alpine home advantage' },
    lines: {
      win: 'The pikemen formed a square, and the cavalry formed a queue.',
      loss: 'The pikemen were defeated but, crucially, not discounted.',
      ana: 'The pikemen billed the jet age by the hour and got it.',
    },
  },
  {
    id: 'grd-zulu',
    slot: 'ground',
    name: 'Zulu Impi',
    origin: 'Zulu Kingdom',
    year: 1879,
    blurb: 'Buffalo-horns formation. You are the buffalo’s problem now.',
    stats: s(9, 4, 9, 4, 2, 9, 6),
    terrain: { open: 2 },
    special: { trigger: 'blitz', bonus: 1.0, label: 'Encirclement at sprint speed' },
    lines: {
      win: 'The horns closed before the enemy finished deploying, which is the whole idea.',
      loss: 'The impi ran out of enemy to encircle and, unsatisfied, encircled the debrief.',
      ana: 'The impi outpaced the supply trucks on foot and pretended not to be smug about it.',
    },
  },
  {
    id: 'grd-varangian',
    slot: 'ground',
    name: 'Varangian Guard',
    origin: 'Byzantine Empire',
    year: 988,
    blurb: 'Viking severance package: guard the emperor, get paid in gold, never retreat.',
    stats: s(9, 8, 5, 4, 4, 9, 4),
    terrain: { urban: 2, winter: 2 },
    lines: {
      win: 'The Varangians won and were paid in gold, which was the plan all along.',
      loss: 'The Varangians did not retreat. The battlefield retreated around them.',
      ana: 'The Varangians accepted direct deposit but insisted the axes stay.',
    },
  },
]

export const ARMOR: Pick[] = [
  {
    id: 'arm-elephants',
    slot: 'armor',
    altSlot: 'ground',
    name: 'War Elephants',
    origin: 'Carthage',
    year: -218,
    blurb: 'Terrifying until startled. Then equally terrifying, less selective.',
    stats: s(9, 7, 4, 2, 2, 5, 2),
    terrain: { open: 2, mountain: -2, winter: -2 },
    special: { trigger: 'open', bonus: 1.0, label: 'Stampede (directional, usually)' },
    lines: {
      win: 'The elephants charged forward, which was, luckily, the direction of the enemy.',
      loss: 'The elephants startled, reversed, and executed a devastating charge on our own paperwork.',
      ana: 'The elephants saw the tanks and trumpeted a formal challenge, which the tanks declined.',
    },
  },
  {
    id: 'arm-trebuchet',
    slot: 'armor',
    name: 'The Trebuchet',
    origin: 'France',
    year: 1204,
    blurb: 'Hurls a 90 kg projectile over 300 meters. The superior siege engine. This is settled.',
    stats: s(8, 3, 2, 4, 7, 4, 2),
    terrain: { urban: 3 },
    special: { trigger: 'urban', bonus: 1.2, label: '90 kg / 300 m (superior)' },
    lines: {
      win: 'The trebuchet crew would like the record to show: 90 kilograms, 300 meters, no notes.',
      loss: 'The trebuchet performed perfectly; the war was simply not a castle.',
      ana: 'The trebuchet crew reviewed the cruise missile and rated it “a trebuchet with anxiety.”',
    },
  },
  {
    id: 'arm-bombard',
    slot: 'armor',
    name: 'The Great Bombard',
    origin: 'Ottoman Empire',
    year: 1453,
    blurb: 'Ended the Roman Empire. Reload time: one hour. Worth it.',
    stats: s(10, 3, 1, 2, 8, 4, 2),
    terrain: { urban: 3, naval: -2 },
    special: { trigger: 'urban', bonus: 1.3, label: 'Walls are negotiable now' },
    lines: {
      win: 'The bombard fired twice. The second one was for emphasis.',
      loss: 'The bombard was still reloading when the war ended, and frankly, when the next one started.',
      ana: 'The bombard crew called the howitzers “impatient” and stand by it.',
    },
  },
  {
    id: 'arm-grande-batterie',
    slot: 'armor',
    name: 'La Grande Batterie',
    origin: 'France',
    year: 1809,
    blurb: 'Napoleon’s actual love language.',
    stats: s(9, 5, 6, 6, 7, 6, 4),
    terrain: { open: 2 },
    lines: {
      win: 'The Grande Batterie opened the battle, and also closed it.',
      loss: 'The guns ran out of targets, then powder, then excuses.',
      ana: 'The gunners saluted the rocket artillery as “the future,” then quietly repositioned to be in the photo.',
    },
  },
  {
    id: 'arm-mark4',
    slot: 'armor',
    name: 'Mark IV Tanks',
    origin: 'Britain',
    year: 1917,
    blurb: 'Top speed: walking. Effect on morale: immeasurable.',
    stats: s(7, 8, 3, 4, 8, 6, 2),
    terrain: { open: 1, urban: 1 },
    special: { trigger: 'trench', bonus: 1.3, label: 'Trenches are speed bumps' },
    lines: {
      win: 'The Mark IVs crossed no-man’s-land at a stately 6 km/h, and nothing on Earth could stop them politely enough.',
      loss: 'The Mark IVs were outmaneuvered by, among other things, the concept of turning.',
      ana: 'The Mark IV crews called the Abrams “showing off” and had tea inside their own engine smoke.',
    },
  },
  {
    id: 'arm-t34',
    slot: 'armor',
    name: 'T-34 Tank Armada',
    origin: 'Soviet Union',
    year: 1943,
    blurb: 'Not elegant. Not comfortable. There are sixty thousand of them.',
    stats: s(9, 8, 7, 6, 8, 8, 3),
    terrain: { winter: 3, open: 2 },
    special: { trigger: 'winter', bonus: 1.0, label: 'Starts in any weather' },
    lines: {
      win: 'The T-34s won by arriving continuously for eleven days.',
      loss: 'The T-34s lost the battle but won the production report.',
      ana: 'The T-34 crews fixed the war elephants’ morale with a wrench, somehow.',
    },
  },
  {
    id: 'arm-katyusha',
    slot: 'armor',
    name: 'Katyusha Rocket Batteries',
    origin: 'Soviet Union',
    year: 1944,
    blurb: 'Screams for eight seconds, deletes a grid square.',
    stats: s(10, 3, 7, 5, 7, 6, 2),
    terrain: { open: 2 },
    lines: {
      win: 'The Katyushas played their signature piece, and the enemy left before the encore.',
      loss: 'The Katyushas deleted the wrong grid square, which contained our lunch.',
      ana: 'The Katyusha crews heard the bagpipes and recognized a fellow psychological weapon.',
    },
  },
  {
    id: 'arm-abrams',
    slot: 'armor',
    name: 'M1 Abrams Battalion',
    origin: 'United States',
    year: 1991,
    blurb: 'Drinks jet fuel like a suggestion. Your medieval supply corps is crying.',
    stats: s(10, 10, 8, 3, 10, 7, 6),
    terrain: { desert: 3, jungle: -2 },
    special: { trigger: 'desert', bonus: 1.3, label: '73 Easting energy' },
    lines: {
      win: 'The Abrams battalion won the engagement in four minutes and spent the rest of the day idling expensively.',
      loss: 'The Abrams battalion ran dry 400 years from the nearest refinery, which the quartermaster calls “a you problem.”',
      ana: 'The Abrams crews let the ancients touch the armor, creating three new religions.',
    },
  },
  {
    id: 'arm-warwagons',
    slot: 'armor',
    name: 'Hussite War Wagons',
    origin: 'Bohemia',
    year: 1420,
    blurb: 'Invented the armored column 500 years early, out of farm carts and audacity.',
    stats: s(7, 9, 5, 6, 6, 8, 3),
    terrain: { open: 2 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Instant fortress, just add wagons' },
    lines: {
      win: 'The war wagons circled up, and the enemy cavalry discovered the concept of a wall that shoots.',
      loss: 'The war wagons were defeated by terrain rated “too silly for wagons.”',
      ana: 'The Hussites inspected the APCs and asked only, “where do the flails mount?”',
    },
  },
  {
    id: 'arm-hwacha',
    slot: 'armor',
    name: 'Hwacha Batteries',
    origin: 'Joseon Korea',
    year: 1593,
    blurb: 'Two hundred rockets per cart. The question was never “why.”',
    stats: s(8, 4, 4, 5, 7, 5, 2),
    terrain: { urban: 2 },
    special: { trigger: 'defense', bonus: 1.1, label: '200 answers per cart' },
    lines: {
      win: 'The hwachas asked the sky to be arrows for a moment, and the sky agreed.',
      loss: 'The hwachas ran out of rockets, which took longer than the enemy expected, but still.',
      ana: 'The hwacha crews watched the MLRS demonstration and said, “yes, that’s ours, with money.”',
    },
  },
]

export const AIR: Pick[] = [
  {
    id: 'air-balloons',
    slot: 'air',
    altSlot: 'intel',
    name: 'The Balloon Corps',
    origin: 'Revolutionary France',
    year: 1794,
    blurb: 'The first air force: one balloon, infinite audacity.',
    stats: s(1, 2, 3, 3, 5, 4, 7),
    special: { trigger: 'intel', bonus: 1.0, label: 'The original eye in the sky' },
    lines: {
      win: 'The balloon saw everything, told everyone, and accepted no follow-up questions.',
      loss: 'The wind changed, and with it, our entire air doctrine.',
      ana: 'The balloon crew waved at the satellites, who, to their credit, waved back.',
    },
  },
  {
    id: 'air-zeppelins',
    slot: 'air',
    name: 'Zeppelin Squadron',
    origin: 'Germany',
    year: 1915,
    blurb: 'Majestic, flammable, punctual.',
    stats: s(4, 2, 5, 5, 7, 4, 6),
    terrain: { night: 1 },
    lines: {
      win: 'The zeppelins arrived on schedule, which for 1915 air power was the victory.',
      loss: 'The zeppelins were asked to please stop being the largest target in history, and could not.',
      ana: 'The zeppelin crews call the C-130 “the little one.”',
    },
  },
  {
    id: 'air-flying-circus',
    slot: 'air',
    name: 'The Flying Circus',
    origin: 'Germany',
    year: 1917,
    blurb: 'Eighty confirmed victories and a paint job that says “come find out.”',
    stats: s(7, 4, 8, 4, 7, 8, 4),
    terrain: { air: 3 },
    special: { trigger: 'airsup', bonus: 1.2, label: 'Dogfighting, the artisanal way' },
    lines: {
      win: 'The Flying Circus won the duel with style points the judges hadn’t invented yet.',
      loss: 'The Flying Circus lost the war but won every individual argument inside it.',
      ana: 'The Red Baron flew the jet once and called it “cheating, but gorgeous.”',
    },
  },
  {
    id: 'air-spitfires',
    slot: 'air',
    name: 'RAF Spitfire Wings',
    origin: 'Britain',
    year: 1940,
    blurb: 'Never was so much owed by so many to so few — these few, specifically.',
    stats: s(8, 7, 8, 6, 8, 9, 7),
    terrain: { air: 3 },
    special: { trigger: 'airsup', bonus: 1.3, label: 'Their finest hour, on repeat' },
    lines: {
      win: 'The Spitfires held the sky like it was a promise.',
      loss: 'The few were, on this occasion, too few.',
      ana: 'The Spitfire pilots taught the balloon corps a victory roll, with mixed but beautiful results.',
    },
  },
  {
    id: 'air-pigeons',
    slot: 'air',
    altSlot: 'intel',
    name: 'Carrier Pigeon Corps',
    origin: 'France',
    year: 1914,
    blurb: 'Cher Ami flew 25 miles shot through the chest and still delivered. Your Wi-Fi drops in rain.',
    stats: s(1, 2, 7, 6, 2, 6, 8),
    bridge: 1,
    special: { trigger: 'intel', bonus: 1.2, label: 'Unjammable. Unbribable. Bird.' },
    lines: {
      win: 'The pigeons delivered the decisive order through fog, flak, and a hawk with opinions.',
      loss: 'The message arrived; the general it was addressed to had been reassigned in 1911.',
      ana: 'The pigeons regard the communications satellite as a very large, very lazy pigeon.',
    },
  },
  {
    id: 'air-migs',
    slot: 'air',
    name: 'MiG-15 Regiments',
    origin: 'Soviet Union',
    year: 1951,
    blurb: 'Showed up over Korea and instantly obsoleted everyone’s paperwork.',
    stats: s(8, 6, 9, 5, 8, 6, 5),
    terrain: { air: 2 },
    lines: {
      win: 'The MiGs turned the enemy air plan into a memo about MiGs.',
      loss: 'The MiGs flew home in formation, which is the dignified version of losing.',
      ana: 'The MiG pilots asked the Sopwith Camel what it does about jet wash, and the Camel said “about what?”',
    },
  },
  {
    id: 'air-hueys',
    slot: 'air',
    altSlot: 'ground',
    name: 'Air Cavalry Hueys',
    origin: 'United States',
    year: 1968,
    blurb: 'The sound of the 20th century clearing its throat.',
    stats: s(7, 5, 10, 7, 7, 7, 5),
    terrain: { jungle: 3 },
    special: { trigger: 'jungle', bonus: 1.2, label: 'The LZ is wherever we say' },
    lines: {
      win: 'The Hueys put a company anywhere on the map in eleven minutes, and the map gave up.',
      loss: 'The one valley without a landing zone contained, regrettably, the war.',
      ana: 'The Hueys gave the Mongol horse archers a lift, creating the most alarming cavalry in history.',
    },
  },
  {
    id: 'air-blackbird',
    slot: 'air',
    altSlot: 'intel',
    name: 'SR-71 Blackbird',
    origin: 'United States',
    year: 1966,
    blurb: 'Outran every missile ever fired at it. Standard evasive maneuver: accelerate.',
    stats: s(1, 9, 10, 3, 10, 5, 10),
    special: { trigger: 'intel', bonus: 1.4, label: 'Sees everything, apologizes never' },
    lines: {
      win: 'The Blackbird photographed the enemy’s entire plan, including the parts they hadn’t admitted to themselves.',
      loss: 'The Blackbird saw the defeat coming in perfect detail and could do absolutely nothing about it, which it calls “someone else’s job.”',
      ana: 'The Blackbird did a flyby for the Oracle at Delphi, who rated the prophecy “accurate.”',
    },
  },
  {
    id: 'air-usaf91',
    slot: 'air',
    name: 'US Air Force',
    origin: 'United States',
    year: 1991,
    blurb: 'Achieved air supremacy in 38 minutes, then spent the rest of the war showing off.',
    stats: s(10, 8, 9, 6, 10, 7, 8),
    terrain: { air: 3, night: 2 },
    special: { trigger: 'airsup', bonus: 1.4, label: 'The sky is a home game' },
    lines: {
      win: 'The Air Force won the war before breakfast and spent the afternoon doing donuts in the stratosphere.',
      loss: 'The Air Force was flawless; unfortunately the war was in a basement.',
      ana: 'Ground crews spent six centuries explaining to the supply corps what “jet fuel” is.',
    },
  },
]

export const NAVY: Pick[] = [
  {
    id: 'nav-triremes',
    slot: 'navy',
    name: 'Athenian Trireme Fleet',
    origin: 'Athens',
    year: -480,
    blurb: 'Democracy’s first flex. Rowed by citizens with opinions.',
    stats: s(7, 4, 8, 4, 6, 8, 6),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.0, label: 'Ramming speed (democratically ratified)' },
    lines: {
      win: 'The triremes voted 6,000 to 12 to ram, and carried the motion.',
      loss: 'The fleet lost the battle but won the subsequent assembly debate about whose fault it was.',
      ana: 'The rowers saw the nuclear carrier and immediately demanded it also hold elections.',
    },
  },
  {
    id: 'nav-longships',
    slot: 'navy',
    altSlot: 'ground',
    name: 'Viking Longship Fleet',
    origin: 'Scandinavia',
    year: 865,
    blurb: 'Draft so shallow they can raid a river, a lake, or your feelings.',
    stats: s(6, 4, 9, 5, 5, 9, 6),
    terrain: { naval: 2, night: 1 },
    special: { trigger: 'amphibious', bonus: 1.2, label: 'Any beach is a port' },
    lines: {
      win: 'The longships appeared 400 miles inland via a river no one had bothered to guard.',
      loss: 'The longships lost, wrote a saga about it, and in the saga they won.',
      ana: 'The Vikings rated the landing craft “acceptable” but missed the dragon heads.',
    },
  },
  {
    id: 'nav-turtleships',
    slot: 'navy',
    name: 'Turtle Ship Squadron',
    origin: 'Joseon Korea',
    year: 1597,
    blurb: 'An ironclad 250 years early, with a dragon head that breathes smoke. Overkill? Correct.',
    stats: s(9, 10, 5, 5, 8, 8, 5),
    terrain: { naval: 3 },
    special: { trigger: 'blockade', bonus: 1.3, label: 'The strait is closed' },
    lines: {
      win: 'The turtle ships sailed through the enemy line, then turned around and did it again for the historians.',
      loss: 'The turtle ships were unbeatable at sea, which is why the enemy rudely stayed ashore.',
      ana: 'The turtle ship captains inspected the destroyer and asked where the spikes were.',
    },
  },
  {
    id: 'nav-armada',
    slot: 'navy',
    name: 'The Spanish Armada',
    origin: 'Spain',
    year: 1588,
    blurb: '130 ships, unbeatable on paper. Do not check the weather. Do not.',
    stats: s(7, 7, 3, 3, 5, 5, 3),
    terrain: { naval: 2 },
    lines: {
      win: 'The Armada won! Nobody checked the weather and NOTHING went wrong. Historic.',
      loss: 'The Armada was defeated by the enemy fleet, the wind, the rain, and a strongly worded pamphlet.',
      ana: 'The Armada requested a weather satellite 400 years early, and honestly, fair.',
    },
  },
  {
    id: 'nav-royal-navy',
    slot: 'navy',
    name: 'The Royal Navy',
    origin: 'Britain',
    year: 1805,
    blurb: 'England expects. The rest is cannon smoke and paperwork.',
    stats: s(10, 8, 7, 9, 7, 9, 7),
    terrain: { naval: 3 },
    special: { trigger: 'blockade', bonus: 1.3, label: 'The blockade is a lifestyle' },
    lines: {
      win: 'The Royal Navy crossed the enemy’s T, dotted their i’s, and impounded their alphabet.',
      loss: 'The Admiralty has classified this loss as “weather.”',
      ana: 'The Royal Navy boarded the aircraft carrier to check its paperwork, out of habit.',
    },
  },
  {
    id: 'nav-treasure-fleet',
    slot: 'navy',
    altSlot: 'logistics',
    name: 'Zheng He’s Treasure Fleet',
    origin: 'Ming China',
    year: 1421,
    blurb: 'Ships so large historians still argue. Came back with giraffes. GIRAFFES.',
    stats: s(6, 7, 6, 10, 7, 6, 7),
    terrain: { naval: 2 },
    special: { trigger: 'supply', bonus: 1.3, label: 'The fleet IS the supply line' },
    lines: {
      win: 'The treasure fleet won the campaign and returned with two new trade routes and a giraffe.',
      loss: 'The treasure fleet lost gracefully and still out-catered every navy involved.',
      ana: 'The treasure fleet took one look at the container ship and said, “finally, a student.”',
    },
  },
  {
    id: 'nav-uboats',
    slot: 'navy',
    name: 'U-boat Wolfpack',
    origin: 'Germany',
    year: 1917,
    blurb: 'Rude in a way the ocean had not previously experienced.',
    stats: s(8, 3, 6, 5, 7, 6, 7),
    terrain: { naval: 2, night: 2 },
    special: { trigger: 'night', bonus: 1.0, label: 'Surfaces only for drama' },
    lines: {
      win: 'The wolfpack turned the enemy’s shipping lanes into a rumor.',
      loss: 'The wolfpack was out-sneaked, which they have taken extremely personally.',
      ana: 'The U-boat crews call the nuclear submarine “the trust-fund nephew.”',
    },
  },
  {
    id: 'nav-carriers',
    slot: 'navy',
    altSlot: 'air',
    name: 'US Pacific Carrier Fleet',
    origin: 'United States',
    year: 1944,
    blurb: 'A floating city that launches the end of your empire in waves.',
    stats: s(10, 8, 8, 9, 9, 8, 7),
    terrain: { naval: 3, air: 2 },
    special: { trigger: 'amphibious', bonus: 1.4, label: 'Islands are stepping stones' },
    lines: {
      win: 'The carriers won a battle nobody on either side could technically see.',
      loss: 'The carriers lost the one engagement that happened indoors.',
      ana: 'The flight deck crew adopted the trireme rowers as “propulsion interns.”',
    },
  },
  {
    id: 'nav-pirates',
    slot: 'navy',
    name: 'Blackbeard’s Pirate Fleet',
    origin: 'The Caribbean',
    year: 1717,
    blurb: 'Lit fuses in his beard before meetings. HR was not consulted.',
    stats: s(6, 4, 8, 3, 3, 7, 7),
    terrain: { naval: 2, night: 1 },
    special: { trigger: 'supply', bonus: 1.2, label: 'Your supplies now (finders keepers)' },
    lines: {
      win: 'The pirates won and, more importantly, kept the enemy’s stuff.',
      loss: 'The pirates lost the battle but stole the enemy’s victory party.',
      ana: 'Blackbeard lit the afterburner fuse in his beard. Medical was furious. Morale was not.',
    },
  },
  {
    id: 'nav-baltic',
    slot: 'navy',
    name: 'The Russian Baltic Fleet',
    origin: 'Imperial Russia',
    year: 1905,
    blurb: 'Sailed 18,000 miles to lose in 45 minutes. Legendary commitment to the bit.',
    stats: s(3, 4, 2, 4, 4, 5, 2),
    terrain: { naval: 1 },
    special: { trigger: 'expedition', bonus: 1.5, label: 'Extremely experienced travelers' },
    lines: {
      win: 'The Baltic Fleet WON?! The crew is as surprised as you are. The band has been playing for nine hours.',
      loss: 'The Baltic Fleet arrived on time, which is to say, seven months late, and performed as scheduled.',
      ana: 'The Baltic Fleet asked the GPS satellite where it was in 1905, and the satellite said “please stop.”',
    },
  },
]

export const INTEL: Pick[] = [
  {
    id: 'int-bletchley',
    slot: 'intel',
    name: 'Bletchley Park',
    origin: 'Britain',
    year: 1942,
    blurb: 'Reads the enemy’s mail before the enemy does. Shortened a world war from a cottage.',
    stats: s(1, 5, 3, 6, 9, 6, 10),
    bridge: 2,
    special: { trigger: 'intel', bonus: 1.4, label: 'Your codes are our newsletter' },
    lines: {
      win: 'Bletchley decrypted the enemy’s battle plan, lunch order, and group chat.',
      loss: 'Bletchley knew we would lose, but the memo was classified above our own clearance.',
      ana: 'Bletchley decoded the smoke signals in four minutes and called it “a nice warm-up.”',
    },
  },
  {
    id: 'int-yam',
    slot: 'intel',
    altSlot: 'logistics',
    name: 'The Yam Courier Network',
    origin: 'Mongol Empire',
    year: 1240,
    blurb: 'Pony Express, but terrifying, and two centuries earlier.',
    stats: s(2, 3, 10, 9, 2, 7, 8),
    terrain: { steppe: 2 },
    bridge: 2,
    special: { trigger: 'supply', bonus: 1.2, label: 'The message always arrives' },
    lines: {
      win: 'The yam riders moved the order 300 miles overnight, and the enemy is still blaming spies.',
      loss: 'The rider arrived, on time, with the wrong scroll, which contained a recipe.',
      ana: 'A yam rider raced the email and lost by seconds, demanding a rematch on real terrain.',
    },
  },
  {
    id: 'int-walsingham',
    slot: 'intel',
    name: 'Walsingham’s Spy Ring',
    origin: 'Elizabethan England',
    year: 1587,
    blurb: 'Elizabeth I’s inbox zero. Every plot, pre-read.',
    stats: s(1, 4, 4, 4, 3, 5, 10),
    special: { trigger: 'intel', bonus: 1.2, label: 'Your conspiracy has a subscriber' },
    lines: {
      win: 'Walsingham’s agents joined the enemy plot, rose to management, and scheduled its failure.',
      loss: 'Walsingham knew everything except, on this one occasion, the thing.',
      ana: 'Walsingham infiltrated the satellite uplink with a quill, somehow.',
    },
  },
  {
    id: 'int-culper',
    slot: 'intel',
    name: 'The Culper Ring',
    origin: 'Revolutionary America',
    year: 1778,
    blurb: 'Invisible ink, numbered agents, and a laundry line that beat an empire.',
    stats: s(1, 4, 5, 4, 3, 7, 9),
    special: { trigger: 'night', bonus: 1.0, label: 'The laundry knows' },
    lines: {
      win: 'Agent 355 flagged the ambush two days early via a clothesline, as one does.',
      loss: 'The invisible ink worked too well; the decisive order is still blank.',
      ana: 'The Culper Ring rated the encrypted radio “showy” and went back to petticoats.',
    },
  },
  {
    id: 'int-codetalkers',
    slot: 'intel',
    altSlot: 'ground',
    name: 'Navajo Code Talkers',
    origin: 'United States',
    year: 1944,
    blurb: 'The only battlefield code never broken. Not once. Not ever.',
    stats: s(3, 5, 6, 5, 6, 9, 10),
    special: { trigger: 'intel', bonus: 1.3, label: 'Unbroken, unbreakable' },
    lines: {
      win: 'The Code Talkers moved the entire plan in the open, and the enemy heard only weather.',
      loss: 'Communications were flawless; the plan they carried, regrettably, was not.',
      ana: 'The enemy cryptographers surrendered a decade later, citing “still no idea.”',
    },
  },
  {
    id: 'int-shinobi',
    slot: 'intel',
    altSlot: 'ground',
    name: 'Iga Shinobi',
    origin: 'Sengoku Japan',
    year: 1580,
    blurb: 'You have already hired them. You found out just now.',
    stats: s(5, 4, 8, 3, 5, 8, 9),
    terrain: { night: 3 },
    special: { trigger: 'night', bonus: 1.4, label: 'The night shift' },
    lines: {
      win: 'The shinobi ended the war on a Tuesday; the enemy noticed the following spring.',
      loss: 'The shinobi were never found — unfortunately, this included by our own payroll.',
      ana: 'A shinobi shadowed the stealth bomber for a week and left it a polite note about its posture.',
    },
  },
  {
    id: 'int-ghost-army',
    slot: 'intel',
    name: 'The Ghost Army',
    origin: 'United States',
    year: 1944,
    blurb: 'Inflatable tanks, fake radio traffic, sound trucks. Modern art’s greatest military victory.',
    stats: s(1, 6, 6, 5, 7, 6, 9),
    special: { trigger: 'propaganda', bonus: 1.4, label: 'The army that isn’t there' },
    lines: {
      win: 'The enemy carefully destroyed 400 balloons while the actual army took the actual objective.',
      loss: 'A goat bit the flagship tank, and doctrine does not cover deflation.',
      ana: 'The Ghost Army inflated a trebuchet for morale, and the real trebuchet crew saluted it.',
    },
  },
  {
    id: 'int-byzantine',
    slot: 'intel',
    name: 'The Bureau of Intrigue',
    origin: 'Byzantine Empire',
    year: 1000,
    blurb: 'Wins wars at dinner parties, three emperors deep.',
    stats: s(1, 6, 3, 5, 4, 5, 10),
    terrain: { urban: 2 },
    special: { trigger: 'propaganda', bonus: 1.2, label: 'It’s complicated (byzantine, even)' },
    lines: {
      win: 'The Bureau convinced the enemy coalition to invoice each other, and the alliance dissolved in committee.',
      loss: 'The Bureau’s plot succeeded perfectly, for a war that had been rescheduled.',
      ana: 'The Bureau read the modern org chart and pronounced it “adorably sincere.”',
    },
  },
  {
    id: 'int-u2',
    slot: 'intel',
    name: 'The U-2 Program',
    origin: 'United States',
    year: 1960,
    blurb: 'Photographs your secrets from 70,000 feet, files them alphabetically.',
    stats: s(1, 4, 8, 4, 10, 4, 10),
    special: { trigger: 'intel', bonus: 1.0, label: 'Sees the whole board' },
    lines: {
      win: 'The U-2 photographed the enemy’s reserves, then their reserves’ reserves, then their diary.',
      loss: 'The photos were perfect; the interpretation, notably, was vibes.',
      ana: 'The U-2 pilot and the Oracle at Delphi compared notes and agreed on everything, which scared both agencies.',
    },
  },
  {
    id: 'int-oracle',
    slot: 'intel',
    altSlot: 'wildcard',
    name: 'The Oracle at Delphi',
    origin: 'Ancient Greece',
    year: -550,
    blurb: 'Intelligence briefings, technically. Accuracy varies. Vibes immaculate.',
    stats: s(1, 3, 2, 2, 1, 5, 7),
    special: { trigger: 'absurd', bonus: 2.0, label: 'A great empire will fall (unspecified)' },
    lines: {
      win: 'The Oracle said “a great empire will fall,” and for once it was the other one.',
      loss: 'The Oracle’s briefing was, in hindsight, a riddle about the loss we were currently having.',
      ana: 'The Oracle reviewed the satellite imagery and said, “yes, this matches the fumes.”',
    },
  },
]

export const LOGISTICS: Pick[] = [
  {
    id: 'log-roman-roads',
    slot: 'logistics',
    name: 'The Roman Road Network',
    origin: 'Roman Empire',
    year: 100,
    blurb: 'All roads lead to your supply depot. Still under warranty, 2,000 years later.',
    stats: s(2, 6, 7, 10, 7, 6, 4),
    special: { trigger: 'supply', bonus: 1.3, label: 'Paved. Straight. Forever.' },
    lines: {
      win: 'Supplies arrived early, on roads that will outlive every empire in this fight.',
      loss: 'The roads were perfect; the map of which roads, less so.',
      ana: 'The engineers inspected the highway system and issued Rome a partial credit.',
    },
  },
  {
    id: 'log-remounts',
    slot: 'logistics',
    name: 'The Mongol Remount System',
    origin: 'Mongol Empire',
    year: 1220,
    blurb: 'Five horses per rider. The original unlimited data plan.',
    stats: s(3, 3, 10, 9, 3, 7, 5),
    terrain: { steppe: 2, naval: -2 },
    special: { trigger: 'blitz', bonus: 1.2, label: 'The army IS the supply line' },
    lines: {
      win: 'The army moved 80 miles a day and the enemy’s planners resigned in protest.',
      loss: 'Five horses per rider, zero boats per horse — the ocean remains undefeated.',
      ana: 'The remount herders counted the fuel trucks and asked, “where are their spares?”',
    },
  },
  {
    id: 'log-redball',
    slot: 'logistics',
    name: 'The Red Ball Express',
    origin: 'United States',
    year: 1944,
    blurb: 'Drove supplies to the front 24/7 until the front couldn’t outrun them.',
    stats: s(3, 4, 8, 9, 6, 7, 3),
    special: { trigger: 'blitz', bonus: 1.3, label: 'The front never waits' },
    lines: {
      win: 'The trucks delivered fuel to the spearhead faster than the spearhead could spend it.',
      loss: 'The trucks were flawless; the road, unfortunately, was a rumor drawn by cartographers.',
      ana: 'The drivers taught the camel caravan to convoy, and the camels taught them to nap.',
    },
  },
  {
    id: 'log-liberty',
    slot: 'logistics',
    altSlot: 'navy',
    name: 'Liberty Shipyards',
    origin: 'United States',
    year: 1943,
    blurb: 'Builds a cargo ship in four days. The ocean is a conveyor belt now.',
    stats: s(2, 5, 4, 10, 7, 6, 3),
    terrain: { naval: 2 },
    special: { trigger: 'supply', bonus: 1.2, label: 'Ships faster than sinkings' },
    lines: {
      win: 'The enemy sank three ships; the yards built five during the meeting about it.',
      loss: 'The ships arrived in glorious numbers at the wrong hemisphere.',
      ana: 'The shipwrights watched a trireme being built and offered, gently, to “take a look.”',
    },
  },
  {
    id: 'log-inca',
    slot: 'logistics',
    name: 'The Inca Runner Relay',
    origin: 'Inca Empire',
    year: 1470,
    blurb: 'Messages over the Andes at a dead sprint, in knots. Literal knots.',
    stats: s(2, 3, 9, 8, 3, 8, 7),
    terrain: { mountain: 3 },
    special: { trigger: 'mountain', bonus: 1.2, label: 'The Andes are a hallway' },
    lines: {
      win: 'The order crossed two mountain ranges by lunch, tied in knots only we can read.',
      loss: 'The message arrived in perfect condition; the knot for “retreat” looks a lot like “party.”',
      ana: 'A runner paced the helicopter through the pass and beat it to the far side on the switchbacks.',
    },
  },
  {
    id: 'log-royal-road',
    slot: 'logistics',
    name: 'The Persian Royal Road',
    origin: 'Achaemenid Persia',
    year: -500,
    blurb: 'Neither snow nor rain nor 2,500 kilometers. The original express shipping.',
    stats: s(2, 4, 7, 9, 3, 5, 6),
    terrain: { desert: 2 },
    special: { trigger: 'desert', bonus: 1.2, label: 'Ninety days to anywhere' },
    lines: {
      win: 'The couriers were neither stayed by snow, nor rain, nor the entire enemy cavalry screen.',
      loss: 'The road ran out 40 miles from the war, which is a postal issue, not a military one.',
      ana: 'The couriers rated two-day shipping “a good start.”',
    },
  },
  {
    id: 'log-airlift',
    slot: 'logistics',
    name: 'Airlift Command',
    origin: 'Berlin Airlift',
    year: 1948,
    blurb: 'Supplied an entire city by air. Included candy. Especially the candy.',
    stats: s(1, 4, 8, 10, 8, 7, 4),
    terrain: { air: 2, winter: 1 },
    special: { trigger: 'supply', bonus: 1.3, label: 'Gravity is a supply route' },
    lines: {
      win: 'A plane landed every 45 seconds until the siege gave up out of embarrassment.',
      loss: 'The airlift was perfect; the army below kept moving the city.',
      ana: 'The pilots dropped candy for the Roman legions, instantly creating history’s most loyal auxiliary.',
    },
  },
  {
    id: 'log-foraging',
    slot: 'logistics',
    name: 'Napoleonic Foraging Corps',
    origin: 'France',
    year: 1807,
    blurb: 'The plan is: the land will provide. The land has other plans.',
    stats: s(3, 3, 6, 4, 3, 5, 4),
    terrain: { winter: -3 },
    lines: {
      win: 'The land provided! Nobody is more surprised than the land.',
      loss: 'The army ate through the countryside, and then the countryside, in a stunning reversal, was Russia.',
      ana: 'The foragers looked at the MRE, said “the land will provide,” and were handed the land, freeze-dried.',
    },
  },
  {
    id: 'log-alpine',
    slot: 'logistics',
    name: 'Hannibal’s Alpine Baggage Train',
    origin: 'Carthage',
    year: -218,
    blurb: 'Thirty-seven elephants enter the Alps. The number that exits is a sore subject.',
    stats: s(3, 4, 4, 3, 2, 8, 3),
    terrain: { mountain: 2, winter: -2 },
    special: { trigger: 'mountain', bonus: 1.0, label: 'Has done this before, barely' },
    lines: {
      win: 'The baggage train made it over the pass, and morale over the sheer nerve of it carried the war.',
      loss: 'The supply plan was, verbatim, “the elephants know the way.”',
      ana: 'The muleteers watched the cargo helicopter cross the Alps in an hour and sat down for a long time.',
    },
  },
  {
    id: 'log-camels',
    slot: 'logistics',
    name: 'The Camel Caravan Network',
    origin: 'Ayyubid Sultanate',
    year: 1187,
    blurb: 'Ships of the desert. Spit-based morale system.',
    stats: s(2, 4, 7, 8, 3, 7, 5),
    terrain: { desert: 3, winter: -2 },
    special: { trigger: 'desert', bonus: 1.3, label: 'The desert is a highway' },
    lines: {
      win: 'The caravans crossed the erg on schedule, smug the entire way.',
      loss: 'The camels declined the tundra, in writing, via spit.',
      ana: 'The camels regarded the supply trucks with the smugness of a species that runs on grass.',
    },
  },
]

export const WILDCARD: Pick[] = [
  {
    id: 'wld-greek-fire',
    slot: 'wildcard',
    altSlot: 'navy',
    name: 'Greek Fire Siphons',
    origin: 'Byzantine Empire',
    year: 900,
    blurb: 'Burns on water. Recipe lost. Warranty void.',
    stats: s(9, 6, 3, 3, 8, 5, 3),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.4, label: 'The sea is flammable now' },
    lines: {
      win: 'The siphons set the sea on fire, which the enemy navy considered against the rules. There are no rules.',
      loss: 'The one engineer who knew the recipe retired mid-war, as is tradition.',
      ana: 'The napalm chemists asked for the recipe, and Byzantium, dead for 500 years, still said no.',
    },
  },
  {
    id: 'wld-archimedes',
    slot: 'wildcard',
    altSlot: 'armor',
    name: 'Archimedes’ War Machines',
    origin: 'Syracuse',
    year: -212,
    blurb: 'Give him a lever and he will flip your flagship.',
    stats: s(8, 8, 2, 2, 9, 4, 8),
    terrain: { naval: 2, urban: 2 },
    special: { trigger: 'defense', bonus: 1.4, label: 'Do not disturb his circles' },
    lines: {
      win: 'The Claw lifted the enemy flagship out of the water, and the rest of the fleet remembered other appointments.',
      loss: 'Archimedes solved the war on paper an hour after it was lost, and the proof is elegant.',
      ana: 'Archimedes saw the naval crane, shouted “EUREKA,” and had to be escorted from the port.',
    },
  },
  {
    id: 'wld-geese',
    slot: 'wildcard',
    altSlot: 'intel',
    name: 'The Sacred Geese of Rome',
    origin: 'Roman Republic',
    year: -390,
    blurb: 'Woke up once, saved the Republic. Undefeated since 390 BCE.',
    stats: s(2, 6, 4, 2, 1, 9, 9),
    terrain: { night: 3 },
    special: { trigger: 'night', bonus: 1.6, label: 'The geese are awake' },
    lines: {
      win: 'The night attack was foiled at 3 a.m. by an unpayable, unbribable, extremely loud security system.',
      loss: 'The geese slept through it. After 2,400 years, they felt they’d earned one.',
      ana: 'The geese outperformed the motion sensors in trials and demanded to be paid in grain, up front.',
    },
  },
  {
    id: 'wld-emus',
    slot: 'wildcard',
    name: 'Emu War Veterans',
    origin: 'Australia',
    year: 1932,
    blurb: 'Australia deployed machine guns against these birds. Australia lost. Twice.',
    stats: s(5, 7, 9, 2, 1, 10, 3),
    terrain: { desert: 2, open: 1 },
    special: { trigger: 'absurd', bonus: 2.2, label: 'Undefeated vs. machine guns' },
    lines: {
      win: 'The emus employed the tactics that defeated a machine-gun corps: running, mostly, but with conviction.',
      loss: 'The emus were beaten for the first time in recorded history, and ornithologists are demanding an inquiry.',
      ana: 'The emus watched the armored column break down in the outback and offered no assistance. They remember.',
    },
  },
  {
    id: 'wld-warpigs',
    slot: 'wildcard',
    name: 'The War Pigs of Megara',
    origin: 'Ancient Greece',
    year: -275,
    blurb: 'Ancient anti-elephant weapon. Elephants hate them. Everyone hates them a little.',
    stats: s(6, 4, 5, 2, 1, 7, 2),
    terrain: { open: 1 },
    special: { trigger: 'absurd', bonus: 1.6, label: 'Chaos, deployed squealing' },
    lines: {
      win: 'The war pigs were released, and the enemy line discovered it had somewhere else to be.',
      loss: 'The war pigs defected to the enemy camp, which had better snacks. Betrayal was always on the menu.',
      ana: 'The war pigs were issued tiny flak jackets, and the quartermaster refuses to discuss the fitting.',
    },
  },
  {
    id: 'wld-bagpipers',
    slot: 'wildcard',
    name: 'Highland Bagpipers',
    origin: 'Scotland',
    year: 1746,
    blurb: 'Classified as a weapon of war. By the losing side.',
    stats: s(4, 4, 5, 3, 2, 10, 2),
    terrain: { mountain: 2, open: 1 },
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The Drone of Dread' },
    lines: {
      win: 'The pipes began at dawn, and the enemy, reasonably, concluded the hills themselves were angry.',
      loss: 'The pipers played on through the defeat, which made it sound suspiciously like a victory.',
      ana: 'The pipers plugged into the carrier’s PA system, and three destroyers surrendered before anyone could explain.',
    },
  },
  {
    id: 'wld-longbows',
    slot: 'wildcard',
    altSlot: 'ground',
    name: 'The Longbow Corps',
    origin: 'England',
    year: 1415,
    blurb: 'Six arrows a minute, per archer, forever. The sky is a suggestion.',
    stats: s(9, 4, 6, 4, 4, 7, 4),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.2, label: 'It is raining. It is arrows.' },
    lines: {
      win: 'The sky went dark at Agincourt o’clock, and the enemy’s cavalry charge became a cavalry apology.',
      loss: 'The longbowmen ran out of arrows, at which point they were, administratively, a choir.',
      ana: 'The archers watched the artillery barrage and said, “slower than us, but louder, granted.”',
    },
  },
]

const BASE: Record<string, Pick[]> = {
  commander: COMMANDERS,
  ground: GROUND,
  armor: ARMOR,
  air: AIR,
  navy: NAVY,
  intel: INTEL,
  logistics: LOGISTICS,
  wildcard: WILDCARD,
}

/** Base pools plus the Phase 1a expansion, keyed by primary slot. */
export const POOLS: Record<string, Pick[]> = Object.fromEntries(
  Object.entries(BASE).map(([slot, arr]) => [
    slot,
    [...arr, ...EXPANSION.filter((p) => p.slot === slot)],
  ]),
)

export const ALL_PICKS: Pick[] = Object.values(POOLS).flat()

export function yearLabel(year: number): string {
  return year < 0 ? `${-year} BCE` : `${year} CE`
}
