/**
 * Phase 1b commander pack: the Supreme Commander chair was the marquee slot
 * with the shallowest bench — four fixed menus that never changed. This file
 * opens five new commander eras (GUNPOWDER, SAIL, INDUSTRIAL, WWI, COLD WAR)
 * and deepens ANTIQUITY, MEDIEVAL, and WWII by two seats each.
 *
 * All stats follow the era-relative rubric in RATINGS.md (source of truth):
 * 5 = era-standard, 8+ = attested era-best, 1–3 = famous documented weakness.
 * Every number ≥8 or ≤3 has a citable fact behind it. Content policy per
 * roster.ts: celebratory or long-past figures only.
 */
import type { Pick, Stats } from './types'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const COMMANDERS_1B: Pick[] = [
  // ── ANTIQUITY (depth: 4 → 6) ─────────────────────────────────────────────
  {
    id: 'cmd-caesar',
    slot: 'commander',
    name: 'Julius Caesar',
    origin: 'Rome',
    year: -52,
    blurb: 'Builds a fortified camp every single night. Writes about it in the third person.',
    stats: s(9, 8, 8, 7, 7, 8, 7),
    terrain: { urban: 2, open: 1 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'siege', bonus: 1.2, label: 'Build a second wall' },
    lines: {
      win: 'Caesar came, saw, and had the victory dispatch drafted before the cavalry got back.',
      loss: 'Caesar has already written the account of this defeat, and in his account it is a victory.',
      ana: 'Caesar dictated his commentary on the drone strike in the third person before it landed.',
    },
  },
  {
    id: 'cmd-scipio',
    slot: 'commander',
    name: 'Scipio Africanus',
    origin: 'Rome',
    year: -202,
    blurb: 'Studied Hannibal’s homework, corrected it, and handed it back at Zama.',
    stats: s(9, 6, 7, 7, 6, 8, 8),
    terrain: { open: 2, desert: 1 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'expedition', bonus: 1.2, label: 'Take the war to their house' },
    lines: {
      win: 'Scipio used the enemy’s own playbook against them, then returned it after the battle with annotations.',
      loss: 'Scipio lost, an event so rare the Senate assumed the messenger was drunk.',
      ana: 'Scipio watched the amphibious landing craft for an hour and whispered, “so that’s how you get the elephants back.”',
    },
  },
  // ── MEDIEVAL (depth: 4 → 6) ──────────────────────────────────────────────
  {
    id: 'cmd-khalid',
    slot: 'commander',
    name: 'Khalid ibn al-Walid',
    origin: 'Rashidun Caliphate',
    year: 636,
    blurb: 'Career record: forty-and-oh across two empires. Files “retreat” under “arriving somewhere else first.”',
    stats: s(10, 6, 9, 6, 5, 9, 7),
    terrain: { desert: 3, open: 1 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'expedition', bonus: 1.2, label: 'Arrives before the news of his departure' },
    lines: {
      win: 'Khalid won his forty-somethingth straight, and the chroniclers quietly retired the word “upset.”',
      loss: 'Khalid checked the record, found no precedent for this result, and ruled the defeat inadmissible.',
      ana: 'Khalid asked only whether the armored division could go five days without water. It could not. He sighed.',
    },
  },
  {
    id: 'cmd-tran',
    slot: 'commander',
    name: 'Tran Hung Dao',
    origin: 'Dai Viet',
    year: 1288,
    blurb: 'The Mongols went three-for-three against the planet, except at his house.',
    stats: s(8, 9, 7, 6, 7, 9, 9),
    terrain: { naval: 2, jungle: 2 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'defense', bonus: 1.3, label: 'Ask the tide when to attack' },
    lines: {
      win: 'Tran Hung Dao consulted the tide tables and scheduled the enemy’s defeat for high water.',
      loss: 'The invaders won this round. He has beaten that exact army twice before; he is not worried, and they are.',
      ana: 'He asked when the carrier group planned to enter the river, and everyone got very quiet about drafts.',
    },
  },
  // ── GUNPOWDER (new cell: 1 → 4) ──────────────────────────────────────────
  {
    id: 'cmd-nobunaga',
    slot: 'commander',
    name: 'Oda Nobunaga',
    origin: 'Sengoku Japan',
    year: 1575,
    blurb: 'Unified half of Japan by being the only person taking the arquebus seriously.',
    stats: s(9, 6, 7, 8, 9, 7, 7),
    terrain: { open: 2 },
    leadership: 8,
    adaptability: 9,
    special: { trigger: 'open', bonus: 1.1, label: 'Three ranks, no reloading gap' },
    lines: {
      win: 'Nobunaga rotated three ranks of arquebusiers, and the enemy cavalry rotated into history.',
      loss: 'Nobunaga has narrowed the list of betrayal suspects to everyone.',
      ana: 'Nobunaga looked at the assault rifle, said nothing, and ordered nine hundred by Thursday.',
    },
  },
  {
    id: 'cmd-suleiman',
    slot: 'commander',
    name: 'Suleiman the Magnificent',
    origin: 'Ottoman Empire',
    year: 1529,
    blurb: 'Thirteen campaigns, one nickname, zero modesty required. The Magnificent is a job title.',
    stats: s(8, 7, 6, 8, 8, 7, 7),
    terrain: { urban: 2 },
    leadership: 9,
    adaptability: 6,
    special: { trigger: 'siege', bonus: 1.2, label: 'The artillery train is also magnificent' },
    lines: {
      win: 'Suleiman accepted the city’s surrender, codified it into law, and had it set to verse by Thursday.',
      loss: 'The siege was called on account of October. October has been formally annexed instead.',
      ana: 'Suleiman inspected the howitzer with genuine warmth and asked why it was so small.',
    },
  },
  {
    id: 'cmd-gustavus',
    slot: 'commander',
    name: 'Gustavus Adolphus',
    origin: 'Sweden',
    year: 1631,
    blurb: 'Invented combined arms, then personally led every cavalry charge, over written staff objection.',
    stats: s(9, 6, 8, 6, 9, 8, 6),
    terrain: { open: 2, winter: 1 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'blitz', bonus: 1.2, label: 'The guns keep up' },
    lines: {
      win: 'Gustavus moved the artillery like cavalry and the cavalry like a rumor, and the enemy line moved like furniture.',
      loss: 'The king led the charge personally again. The staff has requested, in writing, that he stop doing that.',
      ana: 'Gustavus wept openly at the self-propelled howitzer. It can KEEP UP.',
    },
  },
  // ── SAIL & EMPIRE (new cell: 1 → 4) ──────────────────────────────────────
  {
    id: 'cmd-washington',
    slot: 'commander',
    name: 'George Washington',
    origin: 'Continental America',
    year: 1781,
    blurb: 'Tactical record: mixed. Strategic record: there is a country now.',
    stats: s(5, 7, 6, 4, 5, 10, 8),
    terrain: { winter: 2 },
    leadership: 10,
    adaptability: 8,
    special: { trigger: 'coalition', bonus: 1.2, label: 'Wait for the French' },
    lines: {
      win: 'Washington lost the early battles and won the last one, which turns out to be the entire sport.',
      loss: 'The army survives, which Washington counts as the win. Congress has been invoiced for shoes regardless.',
      ana: 'Washington reviewed the satellite intercepts, nodded slowly, and asked where his spies should row.',
    },
  },
  {
    id: 'cmd-suvorov',
    slot: 'commander',
    name: 'Alexander Suvorov',
    origin: 'Russia',
    year: 1799,
    blurb: 'Sixty-three battles, sixty-three wins. Train hard, fight easy, bayonets non-negotiable.',
    stats: s(9, 6, 9, 6, 4, 10, 6),
    terrain: { mountain: 2, winter: 2 },
    leadership: 10,
    adaptability: 8,
    special: { trigger: 'mountain', bonus: 1.2, label: 'The Alps are a training exercise' },
    lines: {
      win: 'Suvorov attacked immediately, as always, and won immediately, as always.',
      loss: 'Suvorov won every battle in this war; the allies lost the war around him. His complaint to the Tsar rhymes.',
      ana: 'Suvorov made the paratroopers do the jump again, uphill this time.',
    },
  },
  {
    id: 'cmd-wellington',
    slot: 'commander',
    name: 'Duke of Wellington',
    origin: 'Britain',
    year: 1815,
    blurb: 'Beat everyone Napoleon ever sent, then Napoleon, then entered politics — the true defeat.',
    stats: s(7, 10, 6, 9, 6, 8, 8),
    terrain: { open: 2 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'defense', bonus: 1.3, label: 'The reverse slope' },
    lines: {
      win: 'Wellington hid the entire army behind the hill, and the enemy discovered it the traditional way.',
      loss: 'It was a damned near-run thing, minus the near-run part.',
      ana: 'Wellington called the tank “a creature of some utility” and asked it to kindly hold the ridge.',
    },
  },
  // ── INDUSTRIAL (new cell: 0 → 4) ─────────────────────────────────────────
  {
    id: 'cmd-grant',
    slot: 'commander',
    name: 'Ulysses S. Grant',
    origin: 'United States',
    year: 1864,
    blurb: 'Accepts three surrender terms: unconditional, unconditional, and unconditional.',
    stats: s(8, 6, 7, 9, 7, 9, 5),
    terrain: { urban: 2 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'siege', bonus: 1.2, label: 'Unconditional terms, available on request' },
    lines: {
      win: 'Grant proposed to fight it out on this line if it took all summer. It took the afternoon.',
      loss: 'Grant was whipped today and is entirely unbothered; see tomorrow’s schedule, first item: lick ’em.',
      ana: 'Grant found the drone feed useful and the drone briefing resistible.',
    },
  },
  {
    id: 'cmd-moltke',
    slot: 'commander',
    name: 'Moltke the Elder',
    origin: 'Prussia',
    year: 1870,
    blurb: 'Runs wars off a train timetable. Silent in seven languages; this blurb annoys him.',
    stats: s(8, 6, 9, 9, 8, 6, 7),
    terrain: { open: 1 },
    leadership: 8,
    adaptability: 9,
    bridge: 1,
    special: { trigger: 'logistics', bonus: 1.2, label: 'War by timetable' },
    lines: {
      win: 'Moltke mobilized three armies by rail and encircled the enemy at the printed arrival time.',
      loss: 'No plan survives contact with the enemy. He told you that BEFORE handing you the plan. In writing.',
      ana: 'Moltke read the entire GPS specification in silence, then allowed himself one nod.',
    },
  },
  {
    id: 'cmd-garibaldi',
    slot: 'commander',
    name: 'Giuseppe Garibaldi',
    origin: 'Italy',
    year: 1860,
    blurb: 'Liberated two continents on zero budget. The supply plan is, famously, a shirt.',
    stats: s(8, 5, 8, 3, 4, 10, 6),
    terrain: { mountain: 1, jungle: 1 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'irregular', bonus: 1.3, label: 'A thousand volunteers, one shirt color' },
    lines: {
      win: 'Garibaldi conquered a kingdom with a thousand volunteers, handed it over for free, and went home to farm.',
      loss: 'The volunteers fought magnificently and invoiced nothing; the logistics were, as documented, a shirt.',
      ana: 'Garibaldi recruited half the carrier crew into the Redshirts during the safety briefing.',
    },
  },
  {
    id: 'cmd-togo',
    slot: 'commander',
    name: 'Togo Heihachiro',
    origin: 'Meiji Japan',
    year: 1905,
    blurb: 'Turned the Baltic Fleet’s 18,000-mile cruise into a forty-minute appointment.',
    stats: s(9, 7, 8, 7, 8, 8, 8),
    terrain: { naval: 3 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'naval', bonus: 1.3, label: 'Cross the T, sign the treaty' },
    lines: {
      win: 'Togo crossed the T so cleanly the enemy column filed into history in order of tonnage.',
      loss: 'Togo lost at sea, an outcome previously available only to opponents of Togo.',
      ana: 'Togo studied the carrier deck and grasped it instantly, which frightened everyone, including the carrier.',
    },
  },
  // ── WWI & INTERWAR (new cell: 0 → 4) ─────────────────────────────────────
  {
    id: 'cmd-pershing',
    slot: 'commander',
    name: 'John J. Pershing',
    origin: 'United States',
    year: 1918,
    blurb: 'Built a two-million-man army from a standing start. Parking it in France remains in progress.',
    stats: s(7, 6, 4, 7, 6, 8, 6),
    terrain: { open: 1 },
    leadership: 9,
    adaptability: 5,
    special: { trigger: 'coalition', bonus: 1.1, label: 'Allied, not amalgamated' },
    lines: {
      win: 'Pershing declined to loan out the army, used it whole, and returned the war fixed.',
      loss: 'The offensive succeeded at mile one and queued at mile two; the road remains the true enemy.',
      ana: 'Pershing approved of the helicopter immediately: finally, a vehicle exempt from the road network.',
    },
  },
  {
    id: 'cmd-kemal',
    slot: 'commander',
    name: 'Mustafa Kemal',
    origin: 'Ottoman Empire',
    year: 1915,
    blurb: 'Held Gallipoli against three empires’ worth of landings. His pocket watch is a decorated veteran.',
    stats: s(7, 10, 6, 5, 5, 10, 7),
    terrain: { mountain: 2 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'defense', bonus: 1.3, label: 'Not one step off the ridge' },
    lines: {
      win: 'Kemal read the landing beaches off the map a week early and was standing on the ridge when the boats arrived.',
      loss: 'The line held; the empire behind it did not. He has started drafting a replacement.',
      ana: 'Kemal synchronized the drones to his pocket watch. The watch has prior combat experience.',
    },
  },
  {
    id: 'cmd-lawrence',
    slot: 'commander',
    name: 'T. E. Lawrence',
    origin: 'Britain / Arab Revolt',
    year: 1917,
    blurb: 'Archaeology postdoc, accidental colonel. Demolishes one specific railway with scholarly precision.',
    stats: s(6, 4, 9, 5, 6, 7, 9),
    terrain: { desert: 3 },
    leadership: 8,
    adaptability: 9,
    special: { trigger: 'irregular', bonus: 1.3, label: 'The desert is an ocean you raid from' },
    lines: {
      win: 'Lawrence took the port from the landward side, the one direction it had no guns, because everyone said not to.',
      loss: 'The raid succeeded; the seven-hundred-page report about it is the real casualty.',
      ana: 'Lawrence befriended the helicopter squadron in their own dialect within a week and now co-owns the helicopters.',
    },
  },
  {
    id: 'cmd-monash',
    slot: 'commander',
    name: 'John Monash',
    origin: 'Australia',
    year: 1918,
    blurb: 'Civil engineer. Plans battles like bridge projects: on time, under budget, catered.',
    stats: s(8, 6, 6, 9, 9, 7, 7),
    terrain: { open: 1 },
    leadership: 8,
    adaptability: 8,
    special: { trigger: 'logistics', bonus: 1.2, label: 'The battle plan includes lunch' },
    lines: {
      win: 'Monash planned the battle down to the minute and the hot lunch; the battle ran three minutes over, the lunch did not.',
      loss: 'The plan was perfect; the war declined to attend the rehearsal.',
      ana: 'Monash reviewed the cargo-drop manifest and added dessert.',
    },
  },
  // ── WORLD WAR II (depth: 4 → 6) ──────────────────────────────────────────
  {
    id: 'cmd-montgomery',
    slot: 'commander',
    name: 'Bernard Montgomery',
    origin: 'Britain',
    year: 1942,
    blurb: 'Will not attack until victory is a foregone conclusion, then holds a press conference to confirm it.',
    stats: s(7, 8, 5, 9, 7, 8, 8),
    terrain: { desert: 2 },
    leadership: 8,
    adaptability: 5,
    special: { trigger: 'supply', bonus: 1.2, label: 'No battle before its dumps' },
    lines: {
      win: 'Monty attacked only after stockpiling everything twice, and the enemy line discovered arithmetic.',
      loss: 'It was one bridge too far, which he will explain was, in a very real sense, someone else’s bridge.',
      ana: 'Monty issued the phalanx a morale address and a beret each. Effectiveness up nine percent; modesty unchanged.',
    },
  },
  {
    id: 'cmd-slim',
    slot: 'commander',
    name: 'William Slim',
    origin: 'Britain / India',
    year: 1944,
    blurb: 'Took the worst defeat in British history and filed the rematch. The Forgotten Army remembers him.',
    stats: s(8, 8, 7, 9, 6, 9, 7),
    terrain: { jungle: 3 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'jungle', bonus: 1.2, label: 'Defeat into victory, scheduled' },
    lines: {
      win: 'Slim supplied the surrounded boxes by air until “surrounded” became the enemy’s problem.',
      loss: 'The Fourteenth Army has been forgotten again; Slim has added this defeat to the list of things to reverse.',
      ana: 'Slim learned every legionary’s name by Tuesday; by Wednesday the phalanx was calling him Uncle Bill.',
    },
  },
  // ── COLD WAR (new cell: 0 → 4) ───────────────────────────────────────────
  {
    id: 'cmd-macarthur',
    slot: 'commander',
    name: 'Douglas MacArthur',
    origin: 'United States',
    year: 1950,
    blurb: 'Promised to return and did, with cameras. Intelligence estimates sold separately.',
    stats: s(9, 5, 8, 7, 7, 8, 3),
    terrain: { naval: 1, urban: 1 },
    leadership: 8,
    adaptability: 6,
    special: { trigger: 'amphibious', bonus: 1.3, label: 'The tide tables say don’t. Do.' },
    lines: {
      win: 'MacArthur landed where the tide tables said no army could, holding a corncob pipe and a press release.',
      loss: 'MacArthur has identified the party responsible for this defeat, and it is, remarkably, not MacArthur.',
      ana: 'MacArthur waded ashore for the cameras. It was a trebuchet range. He shall return anyway.',
    },
  },
  {
    id: 'cmd-ridgway',
    slot: 'commander',
    name: 'Matthew Ridgway',
    origin: 'United States',
    year: 1951,
    blurb: 'Inherited a routed army in December, returned it in January, fixed. Wears grenades as jewelry.',
    stats: s(7, 8, 7, 7, 6, 9, 7),
    terrain: { winter: 2, mountain: 1 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'defense', bonus: 1.2, label: 'The line stops here' },
    lines: {
      win: 'Ridgway arrived, patrolled the front personally with a grenade on his chest, and the retreat reversed out of embarrassment.',
      loss: 'The army fell back in good order, which, given last month, counts as a miracle with paperwork.',
      ana: 'Ridgway issued the Varangian Guard one grenade each for morale. Morale is now a safety hazard.',
    },
  },
  {
    id: 'cmd-giap',
    slot: 'commander',
    name: 'Vo Nguyen Giap',
    origin: 'Viet Minh',
    year: 1954,
    blurb: 'History teacher. Assigned Dien Bien Phu as homework; France did not do the reading.',
    stats: s(8, 7, 8, 9, 5, 9, 8),
    terrain: { jungle: 2, mountain: 2 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'siege', bonus: 1.2, label: 'The guns arrive by bicycle' },
    lines: {
      win: 'Giap carried the artillery uphill in pieces by bicycle, and the fortress discovered its guns pointed the wrong way.',
      loss: 'The offensive has been postponed while the bicycles are re-inventoried.',
      ana: 'Giap asked how many bicycles the cargo helicopter replaced. Nobody knew. He did.',
    },
  },
  {
    id: 'cmd-schwarzkopf',
    slot: 'commander',
    name: 'Norman Schwarzkopf',
    origin: 'United States',
    year: 1991,
    blurb: 'Briefed the fastest land victory in modern history with a pointer and visible delight.',
    stats: s(9, 6, 9, 8, 9, 7, 7),
    terrain: { desert: 3 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'coalition', bonus: 1.2, label: 'Thirty-four flags, one map' },
    lines: {
      win: 'Schwarzkopf briefed the war like a weather report: one hundred hours of left hook with scattered surrenders.',
      loss: 'The briefing was flawless. The war has requested a copy of the slides.',
      ana: 'The phalanx attempted the Left Hook and is now a Left Rhombus. He has diagrams.',
    },
  },
]
