/**
 * Phase 1b expansion, combat arms: GROUND, ARMOR, AIR, NAVY.
 *
 * Goal (owner directive): no more four-card menus, no more unreachable eras.
 * Every previously active cell deepens toward 6; ground/armor/navy open into
 * SAIL, INDUSTRIAL, WWI and COLD WAR; stranded cards (La Grande Batterie,
 * Mark IV Tanks, M1 Abrams, U-boats, the Baltic Fleet…) get cellmates so
 * their eras can actually be dealt.
 *
 * Stats follow RATINGS.md (era-relative; every 8+/≤3 citable). Content policy
 * per roster.ts. Jokes stay on the record, not the victims.
 */
import type { Pick, Stats } from './types'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const GROUND_1B: Pick[] = [
  // ── ANTIQUITY (depth) ────────────────────────────────────────────────────
  {
    id: 'grd-praetorians',
    slot: 'ground',
    name: 'The Praetorian Guard',
    origin: 'Rome',
    year: 69,
    blurb: 'Elite bodyguard of the emperor. Also the leading cause of emperor.',
    conflict: 'Roman Empire',
    descriptor:
      'The emperor’s household guard, powerful enough to make and unmake emperors.',
    stats: s(7, 8, 5, 6, 6, 6, 8),
    terrain: { urban: 2 },
    special: { trigger: 'propaganda', bonus: 1.1, label: 'Kingmaker rates available' },
    lines: {
      win: 'The Praetorians won the battle and immediately began auctioning the credit.',
      loss: 'The Praetorians lost, then declared the defeat’s author emperor, then reconsidered.',
      ana: 'The Praetorians asked which modern officials require guarding, and everyone slowly closed their laptops.',
    },
  },
  {
    id: 'grd-sacredband',
    slot: 'ground',
    name: 'The Sacred Band of Thebes',
    origin: 'Thebes',
    year: -371,
    blurb: 'Three hundred hoplites who broke the unbreakable Spartan line at Leuctra.',
    conflict: 'Theban Hegemony',
    descriptor:
      'An elite Theban corps of picked warriors that broke Sparta’s aura of invincibility at Leuctra.',
    stats: s(8, 7, 6, 5, 5, 10, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.1, label: 'Break the best first' },
    lines: {
      win: 'The Sacred Band aimed at the enemy’s finest and the rest of the line took the hint.',
      loss: 'The Sacred Band held to the last. The tourists still visit the spot. The enemy still apologizes.',
      ana: 'The Sacred Band watched the tank duel and asked which crew was the elite one, so they could fight that one.',
    },
  },
  // ── MEDIEVAL (depth) ─────────────────────────────────────────────────────
  {
    id: 'grd-mamluks',
    slot: 'ground',
    name: 'Mamluk Heavy Cavalry',
    origin: 'Mamluk Sultanate',
    year: 1260,
    blurb: 'The professionals who finally stopped the Mongols. Enslaved soldiers who fired their empire.',
    conflict: 'Mongol Invasions',
    descriptor:
      'Slave-soldier cavalry who halted the seemingly unstoppable Mongol advance at Ain Jalut.',
    stats: s(9, 7, 8, 6, 6, 8, 7),
    terrain: { desert: 3 },
    special: { trigger: 'desert', bonus: 1.2, label: 'Ain Jalut opening' },
    lines: {
      win: 'The Mamluks feigned retreat against the inventors of feigned retreat, and it worked.',
      loss: 'The Mamluks lost the field and spent the ride home drafting a strongly worded dynasty.',
      ana: 'The Mamluks respected the helicopter cavalry but found the horses regrettably abstract.',
    },
  },
  {
    id: 'grd-teutonic',
    slot: 'ground',
    name: 'The Teutonic Knights',
    origin: 'Teutonic Order',
    year: 1242,
    blurb: 'Heavily armored, heavily organized, heavily advised to check the ice first.',
    conflict: 'Northern Crusades',
    descriptor:
      'Crusading warrior-monks who colonized the Baltic — and fell through the ice at Lake Peipus.',
    stats: s(8, 8, 4, 7, 6, 7, 4),
    terrain: { winter: -2, open: 2 },
    special: { trigger: 'winter', bonus: 1.0, label: 'Dress code: plate, always' },
    lines: {
      win: 'The Order advanced in wedge formation, and the enemy line dispersed in administrative panic.',
      loss: 'The lake has been reclassified as water. The Order disputes the finding.',
      ana: 'The Knights admired the icebreaker ship with an intensity that unsettled its crew.',
    },
  },
  // ── GUNPOWDER (depth) ────────────────────────────────────────────────────
  {
    id: 'grd-tercios',
    slot: 'ground',
    name: 'The Spanish Tercios',
    origin: 'Spain',
    year: 1525,
    blurb: 'Pike, shot, and paperwork in one square. Undefeated for a century and insufferable about it.',
    conflict: 'Italian Wars',
    descriptor:
      'Spanish pike-and-shot squares that dominated European battlefields for over a century.',
    stats: s(8, 9, 5, 6, 7, 8, 6),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.1, label: 'The square holds' },
    lines: {
      win: 'The Tercio formed its square and the enemy cavalry attended their own funeral procession in formation.',
      loss: 'The Tercio was defeated, ending a century-long streak and beginning a century-long inquiry.',
      ana: 'The Tercio inspected the infantry fighting vehicle and asked where the pikes mount. There is a hatch. It counts.',
    },
  },
  {
    id: 'grd-newmodel',
    slot: 'ground',
    name: 'The New Model Army',
    origin: 'England',
    year: 1645,
    blurb: 'Promoted by merit, paid on time, sings psalms while flanking. Deeply annoying to fight.',
    conflict: 'English Civil War',
    descriptor:
      'Parliament’s professional, salaried army that defeated the king.',
    stats: s(8, 7, 6, 8, 6, 9, 6),
    terrain: { open: 1 },
    special: { trigger: 'propaganda', bonus: 1.1, label: 'The sermon before the charge' },
    lines: {
      win: 'The New Model Army won on schedule, credited providence, and filed the expense report.',
      loss: 'The New Model Army lost, held a prayer meeting about it, and emerged somehow more organized.',
      ana: 'The New Model Army approved of the drone’s work ethic but questioned its doctrine.',
    },
  },
  // ── SAIL & EMPIRE (new cell) ─────────────────────────────────────────────
  {
    id: 'grd-oldguard',
    slot: 'ground',
    name: 'Napoleon’s Old Guard',
    origin: 'France',
    year: 1815,
    blurb: 'The reserve of reserves. Grumbles constantly, retreats never. Well, once.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'Napoleon’s veteran elite, held in reserve and committed only at the decisive moment.',
    stats: s(9, 8, 5, 6, 6, 9, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.1, label: 'The Guard commits' },
    lines: {
      win: 'The Old Guard advanced, the enemy remembered every story they’d ever heard, and the stories won.',
      loss: 'The Guard recoiled, and the whole army looked up from its dinner in horror.',
      ana: 'The Old Guard grumbled about the helicopter, the rations, the century, and then boarded in perfect order.',
    },
  },
  {
    id: 'grd-redcoats',
    slot: 'ground',
    name: 'The Thin Red Line',
    origin: 'Britain',
    year: 1811,
    blurb: 'Two ranks, one volley per twenty seconds, zero visible emotions.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'Disciplined British line infantry whose steady musket volleys held firm against massed attack.',
    stats: s(8, 9, 5, 7, 6, 8, 5),
    terrain: { open: 2 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Form square' },
    lines: {
      win: 'The line fired by platoon volley until the enemy column became an enemy suggestion.',
      loss: 'The line withdrew in good order, pausing to dress ranks, which took longer than the battle.',
      ana: 'The redcoats formed square against the tank. The tank, respecting protocol, went around.',
    },
  },
  {
    id: 'grd-minutemen',
    slot: 'ground',
    name: 'The Minutemen',
    origin: 'Continental America',
    year: 1775,
    blurb: 'Ready in sixty seconds, gone in ninety. The stone wall is a load-bearing tactic.',
    conflict: 'American Revolution',
    descriptor:
      'Colonial militia ready to fight at a minute’s notice, who met the British at Lexington and Concord.',
    stats: s(6, 4, 8, 4, 5, 8, 8),
    terrain: {},
    special: { trigger: 'irregular', bonus: 1.3, label: 'Every wall is a firing line' },
    lines: {
      win: 'The Minutemen fired from behind every wall on the road, and the road complained to management.',
      loss: 'The Minutemen dispersed to their farms, which intelligence lists as “undefeated, unavailable.”',
      ana: 'The Minutemen asked if the satellite could watch the road for them. It could. Several men wept.',
    },
  },
  {
    id: 'grd-cossacks',
    slot: 'ground',
    name: 'The Don Cossacks',
    origin: 'Russia',
    year: 1812,
    blurb: 'Appear at dusk, vanish by dawn, invoice the Grande Armée for every straggler.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'Russian light horsemen who harried and bled Napoleon’s army on its retreat from Moscow.',
    stats: s(7, 4, 9, 6, 4, 8, 8),
    terrain: { winter: 2, steppe: 2 },
    special: { trigger: 'winter', bonus: 1.2, label: 'The retreat is our parade route' },
    lines: {
      win: 'The Cossacks harried the column until the retreat became a rumor of a retreat.',
      loss: 'The Cossacks declined the pitched battle and rescheduled it as forty ambushes.',
      ana: 'The Cossacks adopted the snowmobiles instantly and now the snowmobiles fear open doors.',
    },
  },
  // ── INDUSTRIAL (new cell around the Zulu Impi) ───────────────────────────
  {
    id: 'grd-bersaglieri',
    slot: 'ground',
    name: 'The Bersaglieri',
    origin: 'Italy',
    year: 1861,
    blurb: 'Elite riflemen forbidden from walking. Everywhere at a run, feathers first.',
    conflict: 'Italian Unification',
    descriptor:
      'Italy’s fast light infantry, known for their plumed hats and running pace.',
    stats: s(7, 5, 9, 5, 6, 8, 6),
    terrain: { mountain: 2 },
    special: { trigger: 'mountain', bonus: 1.1, label: 'Arrive at a sprint, uphill' },
    lines: {
      win: 'The Bersaglieri ran the entire campaign, including the parts normally done by standing still.',
      loss: 'The Bersaglieri lost, but arrived at the defeat forty minutes before everyone else.',
      ana: 'The Bersaglieri outran the armored personnel carrier on day one and now it follows them out of respect.',
    },
  },
  {
    id: 'grd-roughriders',
    slot: 'ground',
    name: 'The Rough Riders',
    origin: 'United States',
    year: 1898,
    blurb: 'Cowboys, professors, and one future president, all charging uphill toward the cameras.',
    conflict: 'Spanish-American War',
    descriptor:
      'Theodore Roosevelt’s volunteer cavalry, famed for the charge up San Juan Hill.',
    stats: s(7, 5, 7, 4, 5, 9, 6),
    terrain: { jungle: 1 },
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The correspondent is embedded' },
    lines: {
      win: 'The Rough Riders took the hill, and the newspapers took the hill again, larger, in the morning edition.',
      loss: 'The Rough Riders lost the engagement but won the memoir.',
      ana: 'The Rough Riders asked the drone to film them from the heroic angle. The drone already was.',
    },
  },
  {
    id: 'grd-prussianguard',
    slot: 'ground',
    name: 'The Prussian Guard Corps',
    origin: 'Prussia',
    year: 1870,
    blurb: 'Drilled to a metronome. The moustaches are regulation. The punctuality is a weapon.',
    conflict: 'Franco-Prussian War',
    descriptor:
      'Prussia’s elite guard corps, spearhead of the army that crushed France in 1870.',
    stats: s(8, 8, 6, 8, 7, 8, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.1, label: 'Parade-ground precision, live' },
    lines: {
      win: 'The Guard attacked at the printed hour and the enemy, checking their watches, surrendered slightly early.',
      loss: 'The Guard was repulsed and has requested the battle be re-fought due to a scheduling irregularity.',
      ana: 'The Guard found the GPS acceptable but continued navigating by timetable on principle.',
    },
  },
  // ── WWI & INTERWAR (new cell) ────────────────────────────────────────────
  {
    id: 'grd-hellfighters',
    slot: 'ground',
    name: 'The Harlem Hellfighters',
    origin: 'United States',
    year: 1918,
    blurb: '191 days in the line, no trench lost, no man captured. The band also slaps.',
    conflict: 'World War I',
    descriptor:
      'An African American regiment that spent more time under fire than any other US unit in the war.',
    stats: s(8, 8, 6, 5, 6, 9, 6),
    terrain: {},
    special: { trigger: 'trench', bonus: 1.2, label: 'This trench is not available' },
    lines: {
      win: 'The Hellfighters held the line, took the objective, and premiered a new marching arrangement about it.',
      loss: 'The Hellfighters yielded nothing personally; the flanks have been invited to explain themselves.',
      ana: 'The Hellfighters’ band absorbed the synthesizer into the regiment within a week. It has a rank now.',
    },
  },
  {
    id: 'grd-anzac',
    slot: 'ground',
    name: 'The ANZAC Corps',
    origin: 'Australia & New Zealand',
    year: 1915,
    blurb: 'Landed on the wrong beach, dug into a cliff, held it out of sheer disrespect for the situation.',
    conflict: 'World War I',
    descriptor:
      'The Australian and New Zealand troops whose landing at Gallipoli forged a national legend.',
    stats: s(7, 8, 6, 5, 5, 9, 6),
    terrain: { mountain: 1 },
    special: { trigger: 'amphibious', bonus: 1.2, label: 'Dig in where you land' },
    lines: {
      win: 'The ANZACs took the ridge and immediately brewed up, as the ridge was now home.',
      loss: 'The ANZACs were evacuated in perfect silence, the campaign’s only flawless operation.',
      ana: 'The ANZACs rated the landing craft “luxurious” and asked it to aim for the correct beach this time.',
    },
  },
  {
    id: 'grd-canadians',
    slot: 'ground',
    name: 'The Canadian Corps',
    origin: 'Canada',
    year: 1917,
    blurb: 'Rehearsed Vimy on a full-scale model until the ridge itself felt underprepared.',
    conflict: 'World War I',
    descriptor:
      'The Canadian Corps whose assault seized Vimy Ridge where others had failed.',
    stats: s(9, 7, 6, 7, 8, 9, 7),
    terrain: {},
    special: { trigger: 'blitz', bonus: 1.2, label: 'The barrage keeps the appointment' },
    lines: {
      win: 'The Canadians walked the creeping barrage like a metronome and apologized to the ridge for taking it.',
      loss: 'The Canadians fell back politely, which the enemy found more unnerving than the attack.',
      ana: 'The Canadians rehearsed the tank assault on a chalk outline of the tank until the tank felt seen.',
    },
  },
  {
    id: 'grd-alpini',
    slot: 'ground',
    name: 'The Alpini',
    origin: 'Italy',
    year: 1916,
    blurb: 'Fought a war on glaciers, in tunnels, above the clouds. The feather is load-bearing.',
    conflict: 'World War I',
    descriptor:
      'Italy’s mountain troops, who fought a brutal war among the peaks and glaciers of the Alps.',
    stats: s(6, 8, 7, 6, 6, 9, 5),
    terrain: { mountain: 3, winter: 2 },
    special: { trigger: 'mountain', bonus: 1.3, label: 'The summit is the trench' },
    lines: {
      win: 'The Alpini attacked from above the clouds, which the enemy had filed under “weather.”',
      loss: 'The Alpini lost the peak and immediately began tunneling their opinion of that.',
      ana: 'The Alpini carried the anti-tank missile up the glacier and asked, gently, if it gets cold-rated jokes.',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'grd-442nd',
    slot: 'ground',
    name: 'The 442nd Regimental Combat Team',
    origin: 'United States',
    year: 1944,
    blurb: '“Go for Broke.” The most decorated unit of its size in American history. Not close.',
    conflict: 'World War II',
    descriptor:
      'A Japanese American regiment that became the most decorated unit of its size in US history.',
    stats: s(8, 7, 6, 5, 6, 10, 6),
    terrain: { mountain: 2 },
    special: { trigger: 'mountain', bonus: 1.2, label: 'The Lost Battalion gets found' },
    lines: {
      win: 'The 442nd went for broke, and the objective, reviewing their citations, went quietly.',
      loss: 'The 442nd was stopped, briefly, and considers the word “stopped” under formal protest.',
      ana: 'The 442nd read the phalanx’s honor culture and nodded once. The phalanx has adopted the motto.',
    },
  },
  {
    id: 'grd-chindits',
    slot: 'ground',
    name: 'The Chindits',
    origin: 'Britain / India',
    year: 1944,
    blurb: 'Marched into the jungle behind the lines with mules and radios. The mules kept the radios honest.',
    conflict: 'World War II',
    descriptor:
      'British and Indian long‑range raiders who fought deep behind Japanese lines in the Burmese jungle.',
    stats: s(6, 6, 8, 4, 6, 9, 7),
    terrain: { jungle: 3 },
    special: { trigger: 'irregular', bonus: 1.2, label: 'Behind everything' },
    lines: {
      win: 'The Chindits cut the supply line so deep in the jungle the enemy assumed it was a rumor.',
      loss: 'The Chindits withdrew through terrain officially rated “no,” and are already re-infiltrating.',
      ana: 'The Chindits asked whether the helicopter could carry a mule. The mule has opinions about this.',
    },
  },
  // ── COLD WAR (new cell around the Viet Cong + Air Cav) ───────────────────
  {
    id: 'grd-legion',
    slot: 'ground',
    name: 'The French Foreign Legion',
    origin: 'France (all nationalities welcome)',
    year: 1978,
    blurb: 'Marches at 88 paces per minute, asks no questions, files no biographies.',
    conflict: 'Modern Era',
    descriptor:
      'France’s volunteer corps of foreign nationals — a professional expeditionary force in service since 1831.',
    stats: s(8, 7, 7, 6, 6, 9, 6),
    terrain: { desert: 2 },
    special: { trigger: 'expedition', bonus: 1.2, label: 'Anywhere, by Tuesday' },
    lines: {
      win: 'The Legion dropped in with no notice, took the town, and resumed marching at exactly 88 paces per minute.',
      loss: 'The Legion withdrew singing, slowly, which regulations classify as advancing in a different direction.',
      ana: 'The Legion accepted the trebuchet crew’s enlistment without asking a single question about the trebuchet.',
    },
  },
  {
    id: 'grd-royalmarines',
    slot: 'ground',
    name: 'Royal Marine Commandos',
    origin: 'Britain',
    year: 1982,
    blurb: 'Yomped across an island carrying their body weight, uphill, in Antarctic weather, on schedule.',
    conflict: 'Falklands War',
    descriptor:
      'British commandos who yomped across the Falklands to retake the islands.',
    stats: s(8, 7, 8, 6, 7, 9, 6),
    terrain: { winter: 2, mountain: 1 },
    special: { trigger: 'amphibious', bonus: 1.2, label: 'Ashore, then everywhere' },
    lines: {
      win: 'The Commandos yomped eighty kilometers and arrived meaner than the weather, which was the plan.',
      loss: 'The Commandos gave ground at a pace the enemy found suspiciously voluntary.',
      ana: 'The Commandos rated the Roman roads “decent yomping” and the legionaries quietly doubled their pack weight.',
    },
  },
]

export const ARMOR_1B: Pick[] = [
  // ── ANTIQUITY (depth) ────────────────────────────────────────────────────
  {
    id: 'arm-assyrian',
    slot: 'armor',
    name: 'Assyrian Siege Corps',
    origin: 'Assyria',
    year: -701,
    blurb: 'Invented the siege industry: rams, ramps, towers, and the org chart to run them.',
    conflict: 'Assyrian Conquests',
    descriptor:
      'The ancient world’s first great siege corps, with battering rams and mobile siege towers.',
    stats: s(8, 7, 4, 7, 8, 7, 5),
    terrain: { urban: 3 },
    special: { trigger: 'siege', bonus: 1.2, label: 'The ramp is already scheduled' },
    lines: {
      win: 'The Assyrians built a ramp to the battlements and walked in like the wall owed them money.',
      loss: 'The walls held, an event the Assyrians will be commemorating with a much larger ramp.',
      ana: 'The siege corps studied the bulldozer for one hour and now the ramp schedule has improved by centuries.',
    },
  },
  // ── MEDIEVAL (depth) ─────────────────────────────────────────────────────
  {
    id: 'arm-mongolsiege',
    slot: 'armor',
    name: 'The Mongol Siege Train',
    origin: 'Mongol Empire',
    year: 1273,
    blurb: 'Imported the best engineers on two continents and gave them an unlimited walls budget.',
    conflict: 'Mongol Conquests',
    descriptor:
      'Engineers who gave the horse-borne Mongols the power to crack the walls of any city.',
    stats: s(9, 5, 7, 8, 8, 7, 6),
    terrain: { urban: 2 },
    special: { trigger: 'siege', bonus: 1.2, label: 'Engineers from everywhere' },
    lines: {
      win: 'The counterweight trebuchets arrived, and the city’s five-year defense plan became a five-hour one.',
      loss: 'The walls held. The engineers have been gathered. The whiteboard sessions have begun.',
      ana: 'The siege train measured the artillery piece, nodded, and asked where its engineers were from.',
    },
  },
  {
    id: 'arm-cataphracts',
    slot: 'armor',
    name: 'Byzantine Cataphracts',
    origin: 'Byzantium',
    year: 965,
    blurb: 'Rider and horse both in full mail. The heater of the medieval world.',
    conflict: 'Byzantine Wars',
    descriptor:
      'Fully armored Byzantine lancers, both rider and horse encased in mail.',
    stats: s(8, 9, 5, 5, 7, 7, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.1, label: 'The wedge does not negotiate' },
    lines: {
      win: 'The cataphracts advanced at a trot, and the enemy line performed a spontaneous reorganization to elsewhere.',
      loss: 'The cataphracts were lured onto bad ground, where the armor became a very confident anchor.',
      ana: 'The cataphracts circled the main battle tank twice and formally requested it as a mount.',
    },
  },
  // ── GUNPOWDER (depth, joins Great Bombard + Hwacha) ──────────────────────
  {
    id: 'arm-tsarcannon',
    slot: 'armor',
    name: 'The Tsar Cannon',
    origin: 'Russia',
    year: 1586,
    blurb: 'The largest bombard ever cast. Shots fired: zero. Deterrence achieved: total.',
    conflict: 'Tsardom of Russia',
    descriptor:
      'A giant Russian bombard, among the largest cannon ever cast — and never fired in anger.',
    stats: s(9, 3, 1, 2, 8, 6, 2),
    terrain: { urban: 1 },
    authenticity: 'historical',
    special: { trigger: 'absurd', bonus: 1.3, label: 'It has never fired. Would you test it?' },
    lines: {
      win: 'The Tsar Cannon was rolled to the front and the siege ended by unanimous vote of the other side.',
      loss: 'The Tsar Cannon did not fire, maintaining its perfect record through yet another defeat.',
      ana: 'The Tsar Cannon met the railgun and both agreed, silently, that reputation is a munition.',
    },
  },
  {
    id: 'arm-elephantguns',
    slot: 'armor',
    name: 'Mughal Elephant Artillery',
    origin: 'Mughal Empire',
    year: 1560,
    blurb: 'Light cannon, heavy elephant. Recoil management by the only crew member who never signed off.',
    conflict: 'Mughal Conquests',
    descriptor:
      'Mughal siege artillery and war elephants that battered the fortresses of India.',
    stats: s(8, 6, 6, 5, 7, 6, 4),
    terrain: { open: 1, jungle: 1 },
    special: { trigger: 'siege', bonus: 1.1, label: 'The battery repositions itself' },
    lines: {
      win: 'The elephant guns advanced firing, a sentence the enemy needed to hear twice and see zero more times.',
      loss: 'The elephants have reviewed the recoil situation and submitted their resignation in trumpet form.',
      ana: 'The elephants regarded the self-propelled gun as a rude, hairless colleague, but respected the tusks. Barrels. Whatever.',
    },
  },
  // ── SAIL & EMPIRE (new cell around La Grande Batterie) ───────────────────
  {
    id: 'arm-mysore',
    slot: 'armor',
    name: 'Mysorean Rocket Corps',
    origin: 'Kingdom of Mysore',
    year: 1780,
    blurb: 'Iron-cased rockets a generation before Europe copied the homework and misspelled it.',
    conflict: 'Anglo-Mysore Wars',
    descriptor:
      'Iron-cased war rockets that stunned British troops in southern India.',
    stats: s(8, 4, 7, 5, 8, 7, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.2, label: 'The sky is on our side' },
    lines: {
      win: 'The rockets came down shrieking and the enemy square voted to become an enemy scatter.',
      loss: 'The rockets went everywhere, including several places tactically described as “ours.”',
      ana: 'The Rocket Corps read the modern missile’s spec sheet and circled the words “iron casing — our idea.”',
    },
  },
  {
    id: 'arm-congreve',
    slot: 'armor',
    name: 'Congreve Rocket Battery',
    origin: 'Britain',
    year: 1814,
    altSlot: 'wildcard',
    blurb: 'The rockets’ red glare, as seen in the anthem. Accuracy sold separately.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'British war rockets — the ‘red glare’ — copied from Mysore and fired in mass barrages.',
    stats: s(7, 4, 6, 5, 7, 6, 3),
    terrain: {},
    special: { trigger: 'propaganda', bonus: 1.3, label: 'Terrifying from every angle, including ours' },
    lines: {
      win: 'The rockets missed the fort, hit the morale, and the morale did not get back up.',
      loss: 'The battery is pleased to report the rockets all launched, and sad to report in eleven directions.',
      ana: 'The Congreve crews watched the precision strike and whispered, “so they CAN steer.”',
    },
  },
  {
    id: 'arm-horseartillery',
    slot: 'armor',
    name: 'Royal Horse Artillery',
    origin: 'Britain',
    year: 1796,
    blurb: 'Guns that arrive at a gallop, unlimber in a minute, and leave before the thank-you note.',
    conflict: 'Napoleonic Wars',
    descriptor:
      'Light guns with every crewman mounted, able to gallop into action beside the cavalry.',
    stats: s(8, 5, 9, 6, 7, 7, 5),
    terrain: { open: 2 },
    special: { trigger: 'blitz', bonus: 1.2, label: 'Gallop the guns' },
    lines: {
      win: 'The guns galloped to the flank and the enemy learned that artillery can ambush.',
      loss: 'The battery limbered up and departed at a pace the pursuit found insulting.',
      ana: 'The Horse Artillery timed themselves against the self-propelled howitzer and demanded a rematch on grass.',
    },
  },
  // ── WWI & INTERWAR (new cell around the Mark IVs) ────────────────────────
  {
    id: 'arm-french75',
    slot: 'armor',
    name: 'French 75 Batteries',
    origin: 'France',
    year: 1914,
    blurb: 'Fifteen aimed rounds a minute in 1914. The gun so beloved it has a cocktail.',
    conflict: 'World War I',
    descriptor:
      'The quick-firing French field gun whose recoil system let it fire without re-aiming.',
    stats: s(9, 5, 7, 6, 9, 7, 5),
    terrain: { open: 2 },
    special: { trigger: 'open', bonus: 1.2, label: 'Fifteen rounds a minute, all yours' },
    lines: {
      win: 'The 75s fired until the barrels sang, and the enemy attack dissolved into a strongly worded memoir.',
      loss: 'The 75s ran dry at the worst hour; the crews have invoiced the supply column in verse.',
      ana: 'The 75 crews tasted the modern propellant, nodded like sommeliers, and asked for the 1914 vintage.',
    },
  },
  {
    id: 'arm-bigbertha',
    slot: 'armor',
    name: 'Big Bertha Siege Howitzers',
    origin: 'Germany',
    year: 1914,
    blurb: 'Forts rated “impregnable” lasted two days. The gun weighs more than the garrison’s confidence.',
    conflict: 'World War I',
    descriptor:
      'Giant German siege howitzers that smashed the concrete forts of Belgium.',
    stats: s(9, 4, 3, 5, 8, 6, 3),
    terrain: { urban: 2 },
    special: { trigger: 'siege', bonus: 1.3, label: 'Fort removal service' },
    lines: {
      win: 'Bertha spoke twice, and the fortress revised its brochure from “impregnable” to “historic site.”',
      loss: 'Bertha arrived late, as Bertha travels by committee, and the war had moved.',
      ana: 'Bertha’s crew looked at the bunker-buster and felt the particular pride of grandparents.',
    },
  },
  {
    id: 'arm-renaults',
    slot: 'armor',
    name: 'Renault FT Swarm',
    origin: 'France',
    year: 1918,
    blurb: 'The first real tank layout, in the smallest possible package, in enormous numbers. Adorable. Lethal.',
    conflict: 'World War I',
    descriptor:
      'The small, fully turreted French tank built in swarms — the template for tanks to come.',
    stats: s(7, 6, 7, 6, 9, 7, 4),
    terrain: {},
    special: { trigger: 'blitz', bonus: 1.1, label: 'A thousand small problems' },
    lines: {
      win: 'The FTs came over the ridge like a plague of very organized beetles, and the line simply ended.',
      loss: 'Half the swarm bogged in the mud; the other half formed a support group around them.',
      ana: 'The FT crews parked beside the main battle tank, produced a tape measure, and declared themselves the original.',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'arm-hellcat',
    slot: 'armor',
    name: 'M18 Hellcat Battalion',
    origin: 'United States',
    year: 1944,
    blurb: 'Fastest armored vehicle of the war. Armor thickness: motivational.',
    conflict: 'World War II',
    descriptor:
      'A fast US tank destroyer built to ambush German armor and speed away.',
    stats: s(8, 3, 10, 6, 8, 7, 6),
    terrain: { open: 2 },
    special: { trigger: 'blitz', bonus: 1.2, label: 'Shoot, scoot, repeat' },
    lines: {
      win: 'The Hellcats flanked the heavies twice in one afternoon, billing each pass as a separate engagement.',
      loss: 'A Hellcat was hit, which the manual describes in one word: “don’t.”',
      ana: 'The Hellcat crews raced the chariots and now there is a trophy neither government will acknowledge.',
    },
  },
  // ── COLD WAR (new cell around the M1 Abrams) ─────────────────────────────
  {
    id: 'arm-centurion',
    slot: 'armor',
    name: 'Centurion Squadrons',
    origin: 'Britain',
    year: 1953,
    blurb: 'Arrived too late for its war, then quietly won parts of everyone else’s for forty years.',
    conflict: 'Cold War',
    descriptor:
      'The British main battle tank that set the postwar standard and served for decades.',
    stats: s(8, 9, 6, 7, 8, 8, 5),
    terrain: { mountain: 1 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Holds the ridge, keeps the kettle on' },
    lines: {
      win: 'The Centurions held the hill against the odds, the arithmetic, and the briefing.',
      loss: 'The Centurions withdrew hull-down to the next ridge, where the argument will continue indefinitely.',
      ana: 'The Centurion crews toured the trebuchet and pronounced it “a fellow long-service design.”',
    },
  },
  {
    id: 'arm-t72',
    slot: 'armor',
    name: 'T-72 Horde',
    origin: 'Soviet Union',
    year: 1979,
    blurb: 'Quantity with a quality all its own. The factory is the true weapon system.',
    conflict: 'Cold War',
    descriptor:
      'The mass-produced Soviet tank exported to armies across the world.',
    stats: s(8, 6, 7, 8, 6, 6, 4),
    terrain: { steppe: 2, open: 1 },
    special: { trigger: 'steppe', bonus: 1.2, label: 'The horizon is also tanks' },
    lines: {
      win: 'The T-72s arrived in numbers best described as a weather system, and the front moved with the forecast.',
      loss: 'The lead battalion was stopped. Battalions two through forty have been asked to form a queue.',
      ana: 'The T-72 crews saluted the Mongol remount system as the only logistics doctrine they’ve ever respected.',
    },
  },
  {
    id: 'arm-shilka',
    slot: 'armor',
    name: 'ZSU-23-4 Shilka Battery',
    origin: 'Soviet Union',
    year: 1973,
    blurb: 'Four radar-guided barrels with one strong opinion about helicopters.',
    conflict: 'Cold War',
    descriptor:
      'A radar-guided Soviet anti-aircraft vehicle mounting four rapid-firing autocannon.',
    stats: s(7, 6, 6, 6, 8, 6, 7),
    terrain: {},
    special: { trigger: 'airsup', bonus: 1.3, label: 'The sky is closed for maintenance' },
    lines: {
      win: 'The Shilkas switched on, and the enemy air plan converted to an enemy walking plan.',
      loss: 'The Shilkas ran out of sky to argue with and were regrettably introduced to artillery.',
      ana: 'The Shilka crews met the Sacred Chickens and agreed: air defense is a calling, whatever the century.',
    },
  },
]

export const AIR_1B: Pick[] = [
  // ── WWI (depth) ──────────────────────────────────────────────────────────
  {
    id: 'air-balloonbusters',
    slot: 'air',
    name: 'The Balloon Busters',
    origin: 'United States / France',
    year: 1918,
    blurb: 'Attack the most defended objects in the sky, on purpose, repeatedly, briefly.',
    conflict: 'World War I',
    descriptor:
      'Daredevil pilots who attacked heavily defended observation balloons — among the war’s deadliest targets.',
    stats: s(9, 3, 8, 4, 6, 9, 6),
    terrain: { air: 2 },
    special: { trigger: 'intel', bonus: 1.2, label: 'Blind the guns' },
    lines: {
      win: 'The busters dove through the flak and the enemy’s eyes went down in flames, still filing reports.',
      loss: 'The balloon line survived the week, and the busters have taken it extremely personally.',
      ana: 'The busters looked at the reconnaissance satellite for a long time. “And it’s HOW high?”',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'air-nightwitches',
    slot: 'air',
    name: 'The Night Witches',
    origin: 'Soviet Union',
    year: 1943,
    blurb: 'Idle the engine, glide in silent, bomb, restart, vanish. In a crop duster. All women. All night.',
    conflict: 'World War II',
    descriptor:
      'An all-women Soviet regiment that harassed German lines in slow biplanes by night.',
    stats: s(6, 3, 8, 5, 3, 10, 8),
    terrain: { night: 3 },
    special: { trigger: 'night', bonus: 1.3, label: 'The whisper of brooms' },
    lines: {
      win: 'The Witches cut their engines and the night itself started dropping bombs, per enemy paperwork.',
      loss: 'A plywood biplane lost an argument with a searchlight; the squadron flew again twenty minutes later.',
      ana: 'The Night Witches sat in the stealth bomber, patted the console, and said “we had a quieter one.”',
    },
  },
  {
    id: 'air-flyingtigers',
    slot: 'air',
    name: 'The Flying Tigers',
    origin: 'United States / China',
    year: 1942,
    blurb: 'Volunteer pilots, shark-toothed planes, and a kill ratio the accountants double-checked twice.',
    conflict: 'World War II',
    descriptor:
      'American volunteer pilots who defended China against Japanese air raids.',
    stats: s(8, 6, 7, 4, 6, 9, 7),
    terrain: { jungle: 1, air: 1 },
    special: { trigger: 'supply', bonus: 1.2, label: 'The Road stays open' },
    lines: {
      win: 'The Tigers dove out of the sun and the raid became a lesson, then a painting on twelve more noses.',
      loss: 'The Tigers ran out of spare parts, then patience, in that order. Kills claimed anyway.',
      ana: 'The Tigers painted shark teeth on the jet before asking whose it was. It performs better now. Case closed.',
    },
  },
  // ── COLD WAR (depth) ─────────────────────────────────────────────────────
  {
    id: 'air-b52',
    slot: 'air',
    name: 'B-52 Stratofortress Wing',
    origin: 'United States',
    year: 1962,
    blurb: 'The aluminum overcast. Has outlived every aircraft designed to replace it, and several doctrines.',
    conflict: 'Cold War',
    descriptor:
      'The long-range US strategic bomber, a mainstay of carpet bombing and nuclear deterrence for generations.',
    stats: s(10, 5, 6, 8, 8, 7, 6),
    terrain: { air: 2 },
    special: { trigger: 'propaganda', bonus: 1.2, label: 'Presence is the payload' },
    lines: {
      win: 'The BUFFs arrived as scheduled weather, and the enemy discovered a sudden interest in diplomacy.',
      loss: 'The strike was postponed; the wing has rescheduled with the calm of an aircraft that will outlive the war either way.',
      ana: 'The B-52 crews heard the trebuchet was also still in service and sent it a patch.',
    },
  },
  {
    id: 'air-phantom',
    slot: 'air',
    name: 'F-4 Phantom Squadrons',
    origin: 'United States',
    year: 1972,
    blurb: 'Proof that with enough thrust, aerodynamics is a suggestion. Smokes on takeoff, wins anyway.',
    conflict: 'Vietnam War',
    descriptor:
      'A versatile US jet that flew fighter, strike, and reconnaissance missions over Vietnam.',
    stats: s(9, 6, 8, 6, 8, 7, 6),
    terrain: { air: 2, naval: 1 },
    special: { trigger: 'naval', bonus: 1.1, label: 'Flies fine off a boat, somehow' },
    lines: {
      win: 'The Phantoms arrived trailing smoke you could navigate by, which the enemy did, briefly.',
      loss: 'The Phantoms went home to argue about missiles versus guns, the squadron’s true forever war.',
      ana: 'The Phantom crews told the Wright Flyer “you’ll love it, none of it makes sense,” and meant it warmly.',
    },
  },
]

export const NAVY_1B: Pick[] = [
  // ── ANTIQUITY (new cell around the Triremes) ─────────────────────────────
  {
    id: 'nav-corvus',
    slot: 'navy',
    name: 'The Corvus Boarding Fleet',
    origin: 'Rome',
    year: -260,
    blurb: 'Rome couldn’t sail, so Rome installed a bridge and made the sea a road.',
    conflict: 'First Punic War',
    descriptor:
      'The boarding bridge that let Roman soldiers turn sea battles into land fights against Carthage.',
    stats: s(8, 6, 3, 6, 6, 8, 4),
    terrain: { naval: 2 },
    special: { trigger: 'amphibious', bonus: 1.2, label: 'Boarding is just marching' },
    lines: {
      win: 'The corvus slammed down and the naval battle was ruled a land battle, which Rome does not lose.',
      loss: 'The weather voted, the corvus tipped the ships, and the sea reminded Rome whose road it is.',
      ana: 'The legionaries measured the carrier’s flight deck and declared it the finest corvus ever built.',
    },
  },
  {
    id: 'nav-seapeoples',
    slot: 'navy',
    name: 'The Sea Peoples',
    origin: '[REDACTED]',
    year: -1177,
    blurb: 'Collapsed the Bronze Age. Identity unknown, invoice unpaid, return address: the sea.',
    conflict: 'Bronze Age Collapse',
    descriptor:
      'The mysterious sea raiders whose attacks helped topple the great Bronze Age kingdoms.',
    stats: s(8, 4, 8, 3, 4, 8, 5),
    terrain: { naval: 2 },
    special: { trigger: 'irregular', bonus: 1.3, label: 'You cannot subpoena the sea' },
    lines: {
      win: 'The Sea Peoples arrived, the records burned, and the scribes could only write “them again.”',
      loss: 'The Sea Peoples were repelled, per the pharaoh’s wall, which is admittedly the pharaoh’s wall.',
      ana: 'Intelligence ran facial recognition on the Sea Peoples and the database filed for early retirement.',
    },
  },
  // ── GUNPOWDER (new cell around Armada + Turtle Ships) ────────────────────
  {
    id: 'nav-deruyter',
    slot: 'navy',
    name: 'De Ruyter’s Raiders',
    origin: 'Dutch Republic',
    year: 1667,
    blurb: 'Sailed up the enemy’s river, burned the fleet at anchor, towed the flagship home as a souvenir.',
    conflict: 'Anglo-Dutch Wars',
    descriptor:
      'The Dutch admiral who raided up the Thames and burned the English fleet at its moorings.',
    stats: s(9, 6, 8, 7, 7, 8, 8),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.2, label: 'Their harbor is also a battlefield' },
    lines: {
      win: 'De Ruyter appeared where enemy doctrine said rivers end, and left with the doctrine and the flagship.',
      loss: 'The raid was repulsed; the Dutch have gone home to lower the insurance premiums they sell the enemy.',
      ana: 'De Ruyter’s crews studied the harbor’s cyber defenses and asked which cable, physically, is the harbor chain.',
    },
  },
  {
    id: 'nav-holyleague',
    slot: 'navy',
    name: 'The Holy League Galleys',
    origin: 'Spain / Venice / The Papacy',
    year: 1571,
    blurb: 'Half of Europe’s navies, one borrowed flag, four hours at Lepanto that ended an era.',
    conflict: 'Ottoman Wars',
    descriptor:
      'The Christian galley fleet that crushed the Ottoman navy at Lepanto.',
    stats: s(9, 7, 5, 6, 7, 8, 6),
    terrain: { naval: 2 },
    special: { trigger: 'coalition', bonus: 1.3, label: 'Everyone rows together, once' },
    lines: {
      win: 'The League’s galleys formed one line out of five grudges, and the line held for exactly long enough.',
      loss: 'The League lost and dissolved into committee before the smoke cleared, as was foretold.',
      ana: 'The League reviewed the NATO org chart with tears of recognition: so many flags, so few meetings survived.',
    },
  },
  // ── INDUSTRIAL (new cell around the Baltic Fleet) ────────────────────────
  {
    id: 'nav-monitor',
    slot: 'navy',
    name: 'USS Monitor',
    origin: 'United States',
    year: 1862,
    blurb: 'A cheesebox on a raft. Fought one duel, to a draw, and obsoleted every navy on Earth by lunch.',
    conflict: 'American Civil War',
    descriptor:
      'The Union ironclad with a revolving turret that fought the first duel of armored warships.',
    stats: s(6, 9, 4, 4, 9, 7, 4),
    terrain: { naval: 2 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Shells bounce; opinions don’t' },
    lines: {
      win: 'The Monitor’s turret turned, the enemy’s broadside bounced, and naval architecture started over from scratch.',
      loss: 'The Monitor took on water, as the Monitor does; the concept, however, remains unsinkable.',
      ana: 'The Monitor’s crew toured the Aegis destroyer and said, with feeling, “a big cheesebox. Wonderful.”',
    },
  },
  {
    id: 'nav-dreadnought',
    slot: 'navy',
    name: 'HMS Dreadnought',
    origin: 'Britain',
    year: 1906,
    blurb: 'Made every battleship obsolete on launch day, including, eventually, herself.',
    conflict: 'Edwardian Era',
    descriptor:
      'The all-big-gun battleship that made every other warship obsolete overnight.',
    stats: s(10, 8, 6, 6, 10, 7, 5),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.2, label: 'All big guns, no apologies' },
    lines: {
      win: 'Dreadnought crossed the horizon and the enemy fleet aged forty years in a single sighting.',
      loss: 'Dreadnought missed the battle, her one consistent tactic, and the era is quietly relieved.',
      ana: 'Dreadnought signaled the missile cruiser: “HOW MANY GUNS.” The reply “technically eight” has caused an incident.',
    },
  },
  {
    id: 'nav-greatwhite',
    slot: 'navy',
    name: 'The Great White Fleet',
    origin: 'United States',
    year: 1907,
    blurb: 'Sixteen battleships painted white, sailed around the world, fired nothing but salutes. Pure flex.',
    conflict: 'Edwardian Era',
    descriptor:
      'The US battle fleet sent around the globe to display American sea power.',
    stats: s(7, 6, 7, 9, 7, 7, 5),
    terrain: { naval: 2 },
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The paint job is the message' },
    lines: {
      win: 'The White Fleet anchored offshore, gleaming, and the dispute resolved itself at the sight of the coaling bill.',
      loss: 'The fleet lost, but looked so good doing it that three neutral nations placed orders.',
      ana: 'The White Fleet requested the stealth destroyer be repainted white, as invisibility “sends the wrong message.”',
    },
  },
  // ── WWI (new cell around the U-boats) ────────────────────────────────────
  {
    id: 'nav-grandfleet',
    slot: 'navy',
    name: 'The Grand Fleet',
    origin: 'Britain',
    year: 1916,
    blurb: 'The only commander who could lose the war in an afternoon, and therefore never quite fought one.',
    conflict: 'World War I',
    descriptor:
      'Britain’s main battle fleet, which met the German navy at Jutland.',
    stats: s(9, 8, 5, 8, 8, 7, 6),
    terrain: { naval: 3 },
    special: { trigger: 'blockade', bonus: 1.3, label: 'The distant blockade pays daily' },
    lines: {
      win: 'The Grand Fleet won by existing, which is cheap per battle and ruinous per year, and the enemy went first.',
      loss: 'The Grand Fleet lost an afternoon, which is the one thing it could not afford, and the admiral has aged a decade.',
      ana: 'The Grand Fleet asked the satellite where the enemy was, wept briefly into the signal logs, and steamed.',
    },
  },
  {
    id: 'nav-emden',
    slot: 'navy',
    name: 'SMS Emden',
    origin: 'Germany',
    year: 1914,
    blurb: 'The gentleman raider: sank the cargo, saved the crews, apologized for the inconvenience.',
    conflict: 'World War I',
    descriptor:
      'A German light cruiser that raided Allied shipping across the Indian Ocean while sparing captured crews.',
    stats: s(7, 4, 9, 5, 7, 8, 8),
    terrain: { naval: 2 },
    special: { trigger: 'irregular', bonus: 1.3, label: 'Politely everywhere' },
    lines: {
      win: 'Emden took the prize, transferred the crew with apologies, and vanished before the tea cooled.',
      loss: 'Emden was run aground at last, and the enemy press wrote her a eulogy warmer than her own navy’s.',
      ana: 'Emden’s captain reviewed drone warfare and asked, pained, where one sends the apology note.',
    },
  },
  {
    id: 'nav-qships',
    slot: 'navy',
    name: 'The Q-Ships',
    origin: 'Britain',
    year: 1917,
    blurb: 'Warships aggressively disguised as boring. The tramp steamer has opinions and eight guns.',
    conflict: 'World War I',
    descriptor:
      'Warships disguised as harmless merchant steamers to lure U‑boats into surfacing, then open fire.',
    stats: s(7, 5, 4, 5, 6, 8, 9),
    terrain: { naval: 2 },
    special: { trigger: 'intel', bonus: 1.2, label: 'The cargo is a broadside' },
    lines: {
      win: 'The submarine surfaced to sink a rusty freighter, and the freighter’s panels dropped with sincere regret.',
      loss: 'The disguise held perfectly; regrettably, so did the torpedo’s schedule.',
      ana: 'The Q-ship crew studied electronic warfare and concluded it is just panels, spiritually.',
    },
  },
  // ── WWII (depth) ─────────────────────────────────────────────────────────
  {
    id: 'nav-taffy3',
    slot: 'navy',
    name: 'Taffy 3',
    origin: 'United States',
    year: 1944,
    blurb: 'Escort carriers and tin cans versus battleships. They charged. This is not a metaphor.',
    conflict: 'World War II',
    descriptor:
      'Outgunned US escort carriers and destroyers that turned back a far larger Japanese battle fleet off Samar.',
    stats: s(6, 4, 7, 5, 6, 10, 7),
    terrain: { naval: 3 },
    special: { trigger: 'defense', bonus: 1.3, label: 'The tin cans turn toward' },
    lines: {
      win: 'Taffy 3 charged the battleship line making smoke and history, and the battleships, confused, withdrew.',
      loss: 'Taffy 3 was overwhelmed at last, still steaming toward the enemy, still on the radio, still polite.',
      ana: 'Taffy 3’s destroyer crews met the trireme rowers and immediately recognized fellow people who row at battleships.',
    },
  },
  // ── COLD WAR (new cell) ──────────────────────────────────────────────────
  {
    id: 'nav-nautilus',
    slot: 'navy',
    name: 'USS Nautilus',
    origin: 'United States',
    year: 1958,
    blurb: '“Underway on nuclear power.” Crossed under the North Pole to prove a point nobody had asked.',
    conflict: 'Cold War',
    descriptor:
      'The first nuclear submarine, which sailed beneath the North Pole ice cap.',
    stats: s(8, 7, 9, 9, 10, 7, 7),
    terrain: { naval: 3 },
    special: { trigger: 'naval', bonus: 1.2, label: 'Refuels never' },
    lines: {
      win: 'Nautilus surfaced where submarines cannot be, which is her entire personality, and the war followed her there.',
      loss: 'Nautilus withdrew silently, unrefueled, unbothered, already under someone else’s ice.',
      ana: 'Nautilus passed beneath the wooden fleet like a rumor, and four separate captains reported a sea monster with tonnage.',
    },
  },
  {
    id: 'nav-bige',
    slot: 'navy',
    name: 'USS Enterprise (CVN-65)',
    origin: 'United States',
    year: 1964,
    blurb: 'Eight reactors, because the design meeting never said stop. An airport that outruns its escorts.',
    conflict: 'Cold War',
    descriptor:
      'The first nuclear-powered aircraft carrier, a floating airbase of unmatched range.',
    stats: s(10, 7, 8, 8, 10, 7, 7),
    terrain: { naval: 3 },
    special: { trigger: 'airsup', bonus: 1.3, label: 'The airfield is already offshore' },
    lines: {
      win: 'The Big E turned into the wind and produced an air force, which is, legally, cheating.',
      loss: 'The strike cycle was interrupted; the eight reactors have taken it as a personal insult.',
      ana: 'The Enterprise offered the Balloon Corps a catapult launch, and the Balloon Corps is still composing the refusal.',
    },
  },
  {
    id: 'nav-typhoon',
    slot: 'navy',
    name: 'Typhoon-Class Squadron',
    origin: 'Soviet Union',
    year: 1981,
    blurb: 'The largest submarine ever built. Has a swimming pool. This is true. It is a submarine with a pool.',
    conflict: 'Cold War',
    descriptor:
      'The largest submarines ever built, Soviet giants carrying nuclear missiles under the ice.',
    stats: s(9, 8, 5, 7, 8, 6, 5),
    terrain: { naval: 2, winter: 2 },
    special: { trigger: 'defense', bonus: 1.2, label: 'Deterrence, with amenities' },
    lines: {
      win: 'The Typhoon never fired, never surfaced, and won anyway, which was always the brochure.',
      loss: 'The Typhoon was located, an outcome the designers considered impossible and the pool considered rude.',
      ana: 'The Viking crews toured the Typhoon in reverent silence until they reached the pool, then broke into applause.',
    },
  },
  {
    id: 'nav-falklands',
    slot: 'navy',
    name: 'The Falklands Task Force',
    origin: 'Britain',
    year: 1982,
    blurb: 'Eight thousand miles from home, assembled in a weekend, includes a requisitioned cruise liner.',
    conflict: 'Falklands War',
    descriptor:
      'The British task force that sailed 8,000 miles south to retake the Falkland Islands.',
    stats: s(7, 6, 7, 9, 7, 9, 6),
    terrain: { naval: 2, winter: 1 },
    special: { trigger: 'expedition', bonus: 1.3, label: 'The whole country is the supply line' },
    lines: {
      win: 'The task force arrived at the bottom of the map with a navy, an army, and a liner serving dinner at seven.',
      loss: 'The task force withdrew up eight thousand miles of ocean, every mile of which has filed a complaint.',
      ana: 'The task force asked Zheng He how he did this without satellites, and took actual notes.',
    },
  },
]
