/**
 * Phase 1a expansion cards: active-cell fillers, four historical commanders,
 * and the 2020s Commander pack (ruleset: current-affairs — LOCKED default-on,
 * owner decision; see DECISIONS.md).
 *
 * Living-figure rubric (mandatory): persona, public record, communications,
 * administration, image management, and alternate-history outcomes ONLY.
 * Never: health/disability, families, ethnicity/nationality/religion,
 * assassination, real casualties, imprisonment/torture/coercion, or current
 * battlefield losses. Stats are sharp satire with an internally consistent
 * rationale. No Overall exists anywhere.
 */
import type { Pick, Stats } from './types'

const s = (
  atk: number,
  def: number,
  mob: number,
  log: number,
  tech: number,
  grit: number,
  int: number,
): Stats => ({ atk, def, mob, log, tech, grit, int })

export const EXPANSION: Pick[] = [
  // ── COMMANDERS · MEDIEVAL ────────────────────────────────────────────────
  {
    id: 'cmd-saladin',
    slot: 'commander',
    name: 'Saladin',
    origin: 'Ayyubid Sultanate',
    year: 1187,
    blurb: 'Won the war, spared the city, invoiced only in reputation.',
    stats: s(8, 7, 8, 7, 4, 8, 8),
    terrain: { desert: 3 },
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'desert', bonus: 1.2, label: 'The desert keeps his schedule' },
    lines: {
      win: 'Saladin won so graciously that three enemy chroniclers defected to write his version.',
      loss: 'Saladin lost the field and somehow gained diplomatic leverage, which the enemy is still auditing.',
      ana: 'Saladin reviewed the drone footage and asked, gently, where the honor compartment was installed.',
    },
  },
  {
    id: 'cmd-subutai',
    slot: 'commander',
    name: 'Subutai',
    origin: 'Mongol Empire',
    year: 1220,
    blurb: 'Won 65 pitched battles on two continents. The deep cut that beats the famous pick.',
    stats: s(9, 7, 10, 8, 4, 8, 9),
    terrain: { steppe: 3, winter: 2 },
    leadership: 9,
    adaptability: 9,
    special: { trigger: 'blitz', bonus: 1.3, label: 'Two armies, one timetable' },
    lines: {
      win: 'Subutai coordinated converging columns 300 miles apart without a radio, then apologized for the four-hour variance.',
      loss: 'Subutai lost, which historians will dispute for centuries because it had literally never happened.',
      ana: 'Subutai studied the satellite map for an hour and said it confirmed what the scouts already knew.',
    },
  },
  // ── COMMANDERS · WWII ────────────────────────────────────────────────────
  {
    id: 'cmd-eisenhower',
    slot: 'commander',
    name: 'Dwight D. Eisenhower',
    origin: 'United States',
    year: 1944,
    blurb: 'Managed Patton, Montgomery, and de Gaulle simultaneously. The war was the easy part.',
    stats: s(6, 8, 6, 9, 7, 8, 7),
    leadership: 9,
    adaptability: 8,
    special: { trigger: 'coalition', bonus: 1.4, label: 'Herds allied egos' },
    lines: {
      win: 'Eisenhower won the war and, more impressively, the meeting about the war.',
      loss: 'Eisenhower had a note in his pocket taking full blame. He never got to use it until today.',
      ana: 'Eisenhower gave the war elephants a unit patch and a liaison officer, and morale doubled.',
    },
  },
  {
    id: 'cmd-nimitz',
    slot: 'commander',
    name: 'Chester Nimitz',
    origin: 'United States',
    year: 1944,
    blurb: 'Ran an ocean like a chessboard, promoted the codebreakers, said little, sank much.',
    stats: s(8, 8, 7, 8, 8, 7, 9),
    terrain: { naval: 3 },
    leadership: 9,
    adaptability: 7,
    special: { trigger: 'naval', bonus: 1.3, label: 'Calculated risk, calculated twice' },
    lines: {
      win: 'Nimitz bet the fleet on the codebreakers and collected the entire Pacific as change.',
      loss: 'Nimitz lost quietly, filed the lessons alphabetically, and the rematch is already scheduled.',
      ana: 'Nimitz asked the trireme rowers for their fuel consumption tables and got a very long song.',
    },
  },
  // ── COMMANDERS · THE 2020s (current-affairs, satirical) ──────────────────
  {
    id: 'cmd-trump',
    slot: 'commander',
    name: 'Donald Trump',
    origin: 'United States',
    year: 2025,
    blurb: 'Logistics: concepts of a plan. Morale among believers: unmeasurable by science.',
    stats: s(7, 4, 6, 2, 3, 9, 3),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 6,
    adaptability: 8,
    special: { trigger: 'propaganda', bonus: 1.4, label: 'The Rally' },
    lines: {
      win: 'Trump declared victory immediately, and for once the scoreboard agreed with the press release.',
      loss: 'Trump announced the war was rigged and demanded a recount of the casualties. Ours only.',
      ana: 'Trump asked if the trebuchet could have his name on it. It does now. It performs 20% better and no engineer can explain why.',
    },
  },
  {
    id: 'cmd-biden',
    slot: 'commander',
    name: 'Joe Biden',
    origin: 'United States',
    year: 2021,
    blurb: 'Assembles forty-nation coalitions. The briefing runs long. The alliance holds.',
    stats: s(4, 7, 5, 7, 4, 7, 6),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 7,
    adaptability: 5,
    special: { trigger: 'coalition', bonus: 1.4, label: 'The Forty-Nation Phone Tree' },
    lines: {
      win: 'Biden won by coalition: forty flags, one communiqué, and a group photo that took longer than the battle.',
      loss: 'The coalition agreed on the strategy, the funding, and the values. The start time remains under discussion.',
      ana: 'Biden told the Varangian Guard a long story about a guy from Scranton. Nobody translated it. They swore loyalty anyway.',
    },
  },
  {
    id: 'cmd-putin',
    slot: 'commander',
    name: 'Vladimir Putin',
    origin: 'Russia',
    year: 2022,
    blurb: 'Doctrine of 1979, table length of seventy feet, timetable classified.',
    stats: s(7, 8, 3, 2, 5, 6, 7),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 6,
    adaptability: 3,
    special: { trigger: 'winter', bonus: 1.2, label: 'Home-field winter (inherited, not earned)' },
    lines: {
      win: 'Putin announced the victory was phase two of the original plan. The original plan is classified. So is phase one.',
      loss: 'The forty-mile convoy has been redesignated the forty-mile parking lot and has entered its third fiscal quarter.',
      ana: 'Putin took the meeting with the Mongol couriers at the seventy-foot table. They left. Riders wait for no agenda.',
    },
  },
  {
    id: 'cmd-kim',
    slot: 'commander',
    name: 'Kim Jong Un',
    origin: 'North Korea',
    year: 2020,
    blurb: 'The parade is immaculate. All other readiness metrics are classified.',
    stats: s(6, 7, 4, 3, 5, 7, 6),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 5,
    adaptability: 4,
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The Parade' },
    lines: {
      win: 'The victory parade had been scheduled before the war began, which analysts believe explains the war.',
      loss: 'State media reported a historic triumph. The map quietly disagreed and has been reassigned.',
      ana: 'Kim toured the trebuchet works and it is now officially a missile facility. The trebuchets remain, administratively, missiles.',
    },
  },
  {
    id: 'cmd-xi',
    slot: 'commander',
    name: 'Xi Jinping',
    origin: 'China',
    year: 2021,
    blurb: 'The industrial base is the strategy. The five-year plan has a five-year plan.',
    stats: s(5, 7, 5, 9, 8, 6, 7),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 7,
    adaptability: 5,
    special: { trigger: 'supply', bonus: 1.3, label: 'Shipyard Output (see appendix C)' },
    lines: {
      win: 'Xi won without firing a shot, which the five-year plan had listed under third-quarter deliverables.',
      loss: 'The plan survived contact with the enemy. It did not survive contact with the org chart.',
      ana: 'Xi audited Zheng He’s treasure fleet and found the giraffe insufficiently documented.',
    },
  },
  {
    id: 'cmd-zelensky',
    slot: 'commander',
    name: 'Volodymyr Zelensky',
    origin: 'Ukraine',
    year: 2022,
    blurb: 'Career pivot of the century. The address is in a t-shirt; the ask is in every parliament.',
    stats: s(5, 8, 6, 5, 6, 9, 7),
    ruleset: 'current-affairs',
    tone: 'satirical',
    leadership: 8,
    adaptability: 8,
    special: { trigger: 'propaganda', bonus: 1.4, label: 'The Address' },
    lines: {
      win: 'Zelensky delivered the victory address in a t-shirt, and four visiting empires apologized for overdressing.',
      loss: 'The supplies were pledged by twelve parliaments. Eleven are in recess. The twelfth is voting on the agenda.',
      ana: 'Zelensky filmed a selfie video at the Hot Gates. The Spartans requested a second take. There are no second takes.',
    },
  },
  // ── GROUND ───────────────────────────────────────────────────────────────
  {
    id: 'grd-immortals',
    slot: 'ground',
    name: 'The Ten Thousand Immortals',
    origin: 'Achaemenid Persia',
    year: -480,
    blurb: 'Always exactly ten thousand. The paperwork is the scariest part.',
    stats: s(8, 7, 6, 7, 3, 8, 4),
    terrain: { desert: 2, open: 1 },
    lines: {
      win: 'The Immortals replaced every loss by morning muster, and the enemy began to take the name literally.',
      loss: 'The Immortals were defeated but, per doctrine, are still listed at full strength.',
      ana: 'The Immortals inspected the replacement-parts warehouse and nodded: finally, a civilization that understands.',
    },
  },
  {
    id: 'grd-82nd',
    slot: 'ground',
    name: '82nd Airborne',
    origin: 'United States',
    year: 1944,
    blurb: 'Arrives from the ceiling, holds until relieved, complains the entire time. Elite.',
    stats: s(8, 7, 9, 5, 7, 9, 5),
    terrain: { night: 2 },
    special: { trigger: 'amphibious', bonus: 1.1, label: 'Vertical envelopment' },
    lines: {
      win: 'The 82nd landed behind the enemy line, which promptly stopped being a line.',
      loss: 'The drop scattered the division across four map sheets; each squad won a private war of no strategic value.',
      ana: 'The 82nd asked the Sacred Geese to serve as jump-warning. The geese declined the parachutes but took the pay.',
    },
  },
  {
    id: 'grd-gurkhas',
    slot: 'ground',
    name: 'The Gurkha Rifles',
    origin: 'Nepal',
    year: 1944,
    blurb: 'The war cry translates roughly to "the paperwork is already filed."',
    stats: s(9, 8, 8, 5, 5, 10, 6),
    terrain: { mountain: 3, jungle: 2 },
    special: { trigger: 'terrain', bonus: 1.2, label: 'The hill is the easy part' },
    lines: {
      win: 'The Gurkhas took the ridge at night, uphill, politely, and were disappointed it ended so soon.',
      loss: 'The Gurkhas held until ordered back twice. The second order required a signature.',
      ana: 'The Gurkhas rated the mountain pass "gentle" and the Inca runners finally felt seen.',
    },
  },
  // ── ARMOR ────────────────────────────────────────────────────────────────
  {
    id: 'arm-chariots',
    slot: 'armor',
    name: 'Scythed Chariots',
    origin: 'Achaemenid Persia',
    year: -331,
    blurb: 'Terrifying on flat ground. There is a 45-degree workaround the enemy keeps finding.',
    stats: s(8, 3, 8, 3, 3, 5, 2),
    terrain: { open: 3, mountain: -3 },
    special: { trigger: 'open', bonus: 1.1, label: 'Lanes of consequence' },
    lines: {
      win: 'The chariots found flat ground and the enemy found religion.',
      loss: 'The enemy simply stepped aside, which the chariot manual lists as "illegal."',
      ana: 'The chariot crews measured the Abrams and asked where the blades mount. Nobody has told them no yet.',
    },
  },
  {
    id: 'arm-ballista',
    slot: 'armor',
    name: 'Syracusan Ballista Corps',
    origin: 'Syracuse',
    year: -212,
    blurb: 'Precision bolt delivery, invented by a man who preferred circles.',
    stats: s(8, 5, 3, 4, 6, 5, 4),
    terrain: { urban: 2 },
    special: { trigger: 'defense', bonus: 1.1, label: 'Pre-registered firing arcs' },
    lines: {
      win: 'The ballistas hit the same window twice, which the enemy took personally and correctly.',
      loss: 'The bolts were perfect; the war moved out of bolt range and stayed there.',
      ana: 'The ballista crews called the guided missile "a bolt with anxiety," continuing a proud family tradition of this joke.',
    },
  },
  {
    id: 'arm-shermans',
    slot: 'armor',
    name: 'M4 Sherman Swarm',
    origin: 'United States',
    year: 1944,
    blurb: 'Not the best tank. The most tank. Arrives in quantities the enemy calls unfair.',
    stats: s(7, 6, 8, 9, 7, 7, 3),
    terrain: { open: 2 },
    special: { trigger: 'logistics', bonus: 1.1, label: 'Factories win wars' },
    lines: {
      win: 'The Shermans lost the spec-sheet argument and won the war, which is the American doctrine in one sentence.',
      loss: 'The Shermans arrived in magnificent quantity at a battle that required quality, once, today.',
      ana: 'The Sherman crews taught the war elephants convoy discipline. The elephants now honk in formation.',
    },
  },
  {
    id: 'arm-funnies',
    slot: 'armor',
    name: 'Hobart’s Funnies',
    origin: 'Britain',
    year: 1944,
    blurb: 'Swimming tanks, flail tanks, bridge tanks, flame tanks. The beach never stood a chance.',
    stats: s(7, 8, 6, 6, 8, 6, 4),
    authenticity: 'historical',
    special: { trigger: 'amphibious', bonus: 1.3, label: 'A tank for every problem' },
    lines: {
      win: 'The Funnies swam ashore, flailed the mines, bridged the ditch, and asked the seawall to pick a personality.',
      loss: 'The one obstacle without a designated Funny appeared, as prophesied by every quartermaster.',
      ana: 'The Funnies met the Hussite war wagons and both sides immediately began sketching.',
    },
  },
  // ── AIR ──────────────────────────────────────────────────────────────────
  {
    id: 'air-lafayette',
    slot: 'air',
    name: 'Lafayette Escadrille',
    origin: 'France (American volunteers)',
    year: 1916,
    blurb: 'Volunteer pilots with two lion cub mascots named Whiskey and Soda. Historians checked. It’s true.',
    stats: s(6, 4, 8, 4, 6, 8, 4),
    terrain: { air: 2 },
    lines: {
      win: 'The Escadrille won the patrol and the after-party, in the order that mattered to them.',
      loss: 'The squadron lost the sky but kept the lions, which the treaty negotiators refused to discuss.',
      ana: 'The Escadrille asked if the F-15 came in a two-seater for the lion. Aviation has not advanced; it has narrowed.',
    },
  },
  {
    id: 'air-tuskegee',
    slot: 'air',
    name: 'The Tuskegee Airmen',
    origin: 'United States',
    year: 1944,
    blurb: 'Red tails, escort record the bombers requested by name, excellence under double fire.',
    stats: s(8, 8, 8, 5, 7, 10, 5),
    terrain: { air: 3 },
    special: { trigger: 'airsup', bonus: 1.2, label: 'The escort holds' },
    lines: {
      win: 'The Red Tails brought the bombers home again, and the request sheets started listing them by name.',
      loss: 'The escort was flawless; the plan it escorted had been drawn by someone who had never been shot at.',
      ana: 'The Red Tails checked the stealth fighter’s tail and asked, reasonably, where the red went.',
    },
  },
  {
    id: 'air-doolittle',
    slot: 'air',
    name: 'The Doolittle Raiders',
    origin: 'United States',
    year: 1942,
    blurb: 'Launched army bombers off a carrier with no plan for landing. Morale as a weapons system.',
    stats: s(6, 3, 7, 3, 7, 10, 5),
    authenticity: 'historical',
    special: { trigger: 'propaganda', bonus: 1.3, label: 'The message IS the mission' },
    lines: {
      win: 'The raid did minor damage and major history: the enemy recalled two fighter groups to guard the capital’s pride.',
      loss: 'The bombers launched early into a headwind of arithmetic.',
      ana: 'Doolittle looked at the trireme, then at the carrier deck, and asked which one was supposed to be the joke.',
    },
  },
  {
    id: 'air-chickens',
    slot: 'air',
    name: 'The Sacred Chickens',
    origin: 'Roman Republic',
    year: -249,
    blurb: 'Official air-superiority augury. If they eat, we sail. One admiral disagreed once. Once.',
    stats: s(1, 3, 2, 2, 1, 7, 8),
    authenticity: 'historical',
    special: { trigger: 'naval', bonus: 1.2, label: 'If they eat, we sail' },
    lines: {
      win: 'The chickens ate; the fleet sailed; the enemy, unconsulted by any poultry, lost on schedule.',
      loss: 'The chickens refused breakfast, the admiral sailed anyway, and the Republic has updated its HR policies.',
      ana: 'The chickens were shown the weather satellite and pecked at it, which the augurs recorded as "concurrence."',
    },
  },
  {
    id: 'air-kites',
    slot: 'air',
    name: 'The War Kites of Chu',
    origin: 'Ancient China',
    year: -200,
    blurb: 'Signals, ranging, and psychological presence, on a string. Antiquity’s entire air force.',
    stats: s(2, 2, 5, 2, 3, 5, 7),
    authenticity: 'historical',
    special: { trigger: 'intel', bonus: 1.0, label: 'Eyes above the wall' },
    lines: {
      win: 'The kites measured the siege distance to the pace, and the tunnel came up inside the granary.',
      loss: 'The wind died at the operational moment, which is the entire risk profile of a string-based air force.',
      ana: 'The kite corps flew alongside the drone swarm for one afternoon and filed a joint noise complaint about propellers.',
    },
  },
  {
    id: 'air-icarus',
    slot: 'air',
    name: 'The Icarus Program',
    origin: 'Crete (mythical)',
    year: -1300,
    blurb: 'One successful flight, one catastrophic wax failure. Program status: cautionary.',
    stats: s(1, 1, 6, 1, 5, 6, 3),
    authenticity: 'legendary',
    special: { trigger: 'absurd', bonus: 1.8, label: 'Do not exceed service ceiling' },
    lines: {
      win: 'The Icarus Program stayed strictly below the recommended altitude, which counts as its greatest victory to date.',
      loss: 'The program exceeded its service ceiling in full view of the review board.',
      ana: 'The Icarus Program requested the F-117’s heat-shielding budget and was denied, again, for wax-related reasons.',
    },
  },
  {
    id: 'air-beacons',
    slot: 'air',
    name: 'The Beacon Chain',
    origin: 'Mycenaean Greece',
    year: -1180,
    blurb: 'News of victory crossed the sea in one night, mountain to mountain, fire to fire.',
    stats: s(1, 3, 8, 3, 2, 5, 7),
    authenticity: 'legendary',
    special: { trigger: 'blitz', bonus: 1.0, label: 'The signal outruns the army' },
    lines: {
      win: 'The beacons carried the order across three straits before midnight, and the flanking corps moved at dawn.',
      loss: 'A shepherd’s bonfire entered the network, and two armies mobilized against a wedding.',
      ana: 'The beacon keepers were shown fiber optics and asked only whether the fire inside was well fed.',
    },
  },
  // ── NAVY ─────────────────────────────────────────────────────────────────
  {
    id: 'nav-ironsides',
    slot: 'navy',
    name: 'USS Constitution',
    origin: 'United States',
    year: 1812,
    blurb: 'British cannonballs bounced off the hull. The crew kept the nickname and the receipts.',
    stats: s(8, 9, 6, 5, 6, 8, 4),
    terrain: { naval: 3 },
    lines: {
      win: 'Old Ironsides shrugged off the broadside, and the enemy gunnery officer began his memoir mid-battle.',
      loss: 'The hull held; the strategy it was holding did not.',
      ana: 'Old Ironsides reviewed the carrier’s armor and said nothing, loudly.',
    },
  },
  {
    id: 'nav-corsairs',
    slot: 'navy',
    name: 'The Barbary Corsairs',
    origin: 'Barbary Coast',
    year: 1801,
    blurb: 'Speed, audacity, and an invoice. The original subscription model.',
    stats: s(6, 4, 9, 4, 3, 7, 6),
    terrain: { naval: 2, night: 1 },
    special: { trigger: 'supply', bonus: 1.1, label: 'Tribute schedule' },
    lines: {
      win: 'The corsairs won the engagement and immediately renegotiated the terms of everyone’s insurance.',
      loss: 'The corsairs met a navy that had finally read its own budget, "to the shores of Tripoli."',
      ana: 'The corsairs studied container shipping for one week and wept at the unguarded scale of it.',
    },
  },
  {
    id: 'nav-arsenal',
    slot: 'navy',
    altSlot: 'logistics',
    name: 'The Venetian Arsenal',
    origin: 'Republic of Venice',
    year: 1204,
    blurb: 'A galley a day, assembly line, six centuries before assembly lines. Dante toured it. It made the Inferno.',
    stats: s(5, 6, 5, 10, 7, 6, 6),
    terrain: { naval: 2 },
    special: { trigger: 'supply', bonus: 1.3, label: 'A galley a day' },
    lines: {
      win: 'The Arsenal launched replacements faster than the enemy could record sinkings, and the war became a clerical error.',
      loss: 'The fleet was magnificent; the admiral commanding it had been chosen by seniority.',
      ana: 'The Arsenal foremen toured the Liberty shipyards, checked the daily rate, and ordered espresso for four thousand.',
    },
  },
  {
    id: 'nav-ptboats',
    slot: 'navy',
    name: 'PT Boat Squadron',
    origin: 'United States',
    year: 1943,
    blurb: 'Plywood, torpedoes, and future senators. Fast enough to outrun consequences, mostly.',
    stats: s(6, 3, 10, 4, 6, 8, 5),
    terrain: { naval: 2, night: 2 },
    special: { trigger: 'night', bonus: 1.1, label: 'The dark is a torpedo lane' },
    lines: {
      win: 'The PT boats slipped the strait at 2 a.m. and the enemy convoy became a series of insurance claims.',
      loss: 'Plywood, it turns out, is a design philosophy with limits.',
      ana: 'The PT crews raced the Viking longships and lost the trophy on a technicality involving oars and honor.',
    },
  },
  // ── INTEL ────────────────────────────────────────────────────────────────
  {
    id: 'int-soe',
    slot: 'intel',
    name: 'Special Operations Executive',
    origin: 'Britain',
    year: 1942,
    blurb: 'The Baker Street Irregulars: sabotage, forged papers, and exploding rats. All real.',
    stats: s(5, 4, 7, 4, 7, 8, 9),
    terrain: { night: 2 },
    special: { trigger: 'irregular', bonus: 1.3, label: 'Set Europe ablaze (metaphorically, officially)' },
    lines: {
      win: 'The SOE derailed the enemy timetable with a suitcase, a bicycle, and a librarian of terrifying calm.',
      loss: 'The network was betrayed by a radio operator’s too-perfect Morse. Perfection is a tell.',
      ana: 'The SOE evaluated the shinobi curriculum and adopted all of it except the part about not invoicing.',
    },
  },
  {
    id: 'int-kingseyes',
    slot: 'intel',
    name: 'The King’s Eyes and Ears',
    origin: 'Achaemenid Persia',
    year: -500,
    blurb: 'The original inspectorate: royal officials who saw everything and reported by fast road.',
    stats: s(1, 4, 6, 6, 2, 5, 9),
    terrain: { desert: 1 },
    special: { trigger: 'logistics', bonus: 1.0, label: 'The audit rides ahead' },
    lines: {
      win: 'The Eyes reported the enemy muster three provinces early, and the war was won at the granary ledger.',
      loss: 'The report was accurate, punctual, and ignored, achieving the full bureaucratic trifecta.',
      ana: 'The King’s Eyes reviewed the spy satellite and noted, approvingly, that it cannot be bribed. The Ears remain skeptical.',
    },
  },
  {
    id: 'int-berlintunnel',
    slot: 'intel',
    name: 'The Berlin Tunnel',
    origin: 'United States / Britain',
    year: 1955,
    blurb: 'A quarter-mile eavesdropping tunnel under the border. Betrayed before groundbreaking; useful anyway.',
    stats: s(1, 5, 3, 5, 8, 5, 9),
    authenticity: 'historical',
    special: { trigger: 'intel', bonus: 1.2, label: 'The wire under everything' },
    lines: {
      win: 'The tunnel transcribed the enemy’s staff calls for eleven months, including the one about finding tunnels.',
      loss: 'The other side knew about the tunnel first and used it to schedule their most boring phone calls.',
      ana: 'The tunnel team inspected the yam courier network and conceded that horses are harder to wiretap.',
    },
  },
  // ── LOGISTICS ────────────────────────────────────────────────────────────
  {
    id: 'log-mulberry',
    slot: 'logistics',
    name: 'Mulberry Harbours',
    origin: 'Britain',
    year: 1944,
    blurb: 'Brought the harbor to the invasion. Towed a port across the Channel in pieces.',
    stats: s(2, 6, 4, 10, 8, 6, 4),
    terrain: { naval: 2 },
    special: { trigger: 'amphibious', bonus: 1.4, label: 'BYO port' },
    lines: {
      win: 'The invasion needed a harbor, so the harbor commuted, and 7,000 tons a day walked ashore behind it.',
      loss: 'The great storm off the beaches did what the defenders could not, which the weather logs as a win for neutrality.',
      ana: 'The Mulberry engineers explained "bring your own port" to Alexander, who went quiet for a genuinely long time.',
    },
  },
  {
    id: 'log-jeeps',
    slot: 'logistics',
    name: 'The Jeep Fleet',
    origin: 'United States',
    year: 1944,
    blurb: 'Goes anywhere, carries anything, breaks politely. The war’s actual MVP per every sergeant.',
    stats: s(3, 4, 9, 8, 6, 7, 3),
    lines: {
      win: 'The jeeps moved the ammunition, the wounded, the general, and the general’s dog, in that exact order of ceremony.',
      loss: 'The jeeps performed perfectly on roads that existed, a category the theater declined to provide.',
      ana: 'The camel caravans watched a jeep ford a river and spat, which handlers confirm is respect.',
    },
  },
  // ── WILD CARD · THE 2020s ────────────────────────────────────────────────
  {
    id: 'wld-droneswarm',
    slot: 'wildcard',
    altSlot: 'air',
    name: 'The Drone Swarm',
    origin: 'Everywhere, simultaneously',
    year: 2021,
    blurb: 'One operator, four hundred opinions with propellers.',
    stats: s(7, 3, 9, 4, 9, 3, 8),
    terrain: { air: 2, night: 1 },
    special: { trigger: 'intel', bonus: 1.1, label: 'Everything is footage now' },
    lines: {
      win: 'The swarm found the enemy’s hidden reserve, filmed it, tagged it, and turned it into a before picture.',
      loss: 'The jammer worked, and four hundred drones became four hundred very expensive leaves.',
      ana: 'The Sacred Geese watched the swarm with professional disgust: all that noise and not one of them can bite.',
    },
  },
  {
    id: 'wld-gps',
    slot: 'wildcard',
    name: 'The GPS Constellation',
    origin: 'Medium Earth Orbit',
    year: 2020,
    blurb: 'Knows where everything is, including your mistakes, to within one meter.',
    stats: s(1, 5, 2, 8, 10, 3, 9),
    special: { trigger: 'logistics', bonus: 1.2, label: 'Nobody is lost anymore (allegedly)' },
    lines: {
      win: 'Every convoy arrived exactly where intended, a sentence no quartermaster in 3,000 years has been able to say.',
      loss: 'The signal was spoofed, and two supply columns confidently delivered everything to a lake.',
      ana: 'The Polynesian navigators tried GPS for one voyage, handed it back, and said the stars don’t need batteries.',
    },
  },
  {
    id: 'wld-cyber',
    slot: 'wildcard',
    altSlot: 'intel',
    name: 'Cyber Command',
    origin: 'An unmarked building',
    year: 2021,
    blurb: 'Wars begin with a password reset now.',
    stats: s(6, 6, 2, 3, 10, 3, 9),
    special: { trigger: 'intel', bonus: 1.3, label: 'Have you tried turning the enemy off' },
    lines: {
      win: 'The enemy’s logistics software received one (1) update, and their artillery spent the war awaiting a loading screen.',
      loss: 'The air-gapped abacus, it turns out, is unhackable. The enemy knew this. That is why they kept the abacus.',
      ana: 'Cyber Command studied the Byzantine Bureau of Intrigue and formally acknowledged the elder discipline.',
    },
  },
  {
    id: 'wld-groupchat',
    slot: 'wildcard',
    name: 'The Group Chat',
    origin: 'Signal (allegedly)',
    year: 2025,
    blurb: 'Allied planning happens here now. Someone’s plus-one is in it. Nobody knows whose.',
    stats: s(2, 2, 9, 5, 7, 6, 7),
    authenticity: 'improvised',
    special: { trigger: 'coalition', bonus: 1.2, label: 'Reply-all diplomacy' },
    lines: {
      win: 'The entire coalition coordinated in one thread, and for six historic weeks nobody added the wrong person.',
      loss: 'The strike timing leaked when someone reacted to it with a thumbs-up from an unrecognized number.',
      ana: 'The yam couriers were added to the chat and immediately muted it, citing 800 years of message discipline.',
    },
  },
]
